#!/bin/sh

#############################################################
# HREF RUNALL 
# 02/02/2015 Binbin Zhou, create for run all scripts 
#############################################################

########################################
# Preliminary data setup step
########################################

set -xa
export PS4='$SECONDS + ' 
date

###################################
# Specify NET and RUN Name and model
####################################
export NET=${NET:-hiresw}
export RUN=${RUN:-href}

export IOBUF_PARAMS='*:size=8M:count=8'

###############################################################
# This block can be modified for different Production test
# environment. This is used for operational testings
###############################################################

## PDY not included here as pull data from PDYm1 as well

export COMINhiresw=${COMINhiresw:-$(compath.py hiresw/prod/hiresw)}
export COMINnam=${COMINnam:-$(compath.py nam/prod/nam)}
export COMINhrrr=${COMINhrrr:-$(compath.py hrrr/prod/hrrr)}

export HOMEhref=${HOMEhref:-$NWROOT/href.${href_ver}} 
export EXEChref=${EXEChref:-$HOMEhref/exec}
export PARMhref=${PARMhref:-$HOMEhref/parm}
export USHhref=${USHhref:-$HOMEhref/ush}
export FIXhref=${FIXhref:-$HOMEhref/fix}
export SCRIPTShref=${SCRIPTShref:-$HOMEhref/scripts}

###########################################################
# obtain unique process id (pid) and make temp directories
###########################################################

export pid=$$
export DATA=${DATA:-${DATAROOT}/href_ensprodpreproc_${NEST}_${cyc}_${envir}.${pid}}
mkdir -p $DATA
rm -rf $DATA/*
cd $DATA

####################################
# File To Log Msgs
####################################
export jlogfile=${jlogfile:-$COMROOT/logs/jlogfile}

####################################
# Determine Job Output Name on System
####################################
export pgmout="OUTPUT.$$"

export cycle=${cycle:-t${cyc}z}

##################################################
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
##################################################

export SENDCOM=${SENDCOM:-YES}
export SENDECF=${SENDECF:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDDBN_NTC=${SENDDBN_NTC:-NO}

###################################
# Set up the UTILITIES
###################################

msg="JOB $job HAS BEGUN"
postmsg "$jlogfile" "$msg"

#
# Run setpdy and initialize PDY variables
#

setpdy.sh
. PDY

##############################################
# Define running directory and COM directories
##############################################

if [ "$RUN_ENVIR" != nco ] ; then
  export COMOUT=${MYCOMROOT}/${NET}/${envir}/${RUN}.${PDY}_expv3
else
  export COMOUT=${COMOUT:-${COMROOT}/${NET}/${envir}/${RUN}.${PDY}}
fi

if [ ! -d $COMOUT ] ; then 
 mkdir -p $COMOUT/ensprod
 mkdir -p $COMOUT/verf_g2g
fi

#######################################################
# Pass information which is needed to run the Script
#######################################################

# export VERBOSE=YES

###################################################
# Execute the Script exhref_ensprod.sh

rm -rf poe.*


echo "#!/bin/sh  "                             >  poe.aaa
echo "$USHhref/preprocess_fv3_1h.sh ${cyc} 00 ${NEST} &" >> poe.aaa
echo "$USHhref/preprocess_fv3_1h.sh ${cyc} 01 ${NEST} &" >> poe.aaa
echo "$USHhref/preprocess_fv3_1h.sh ${cyc} 02 ${NEST} &" >> poe.aaa
echo "$USHhref/preprocess_fv3_1h.sh ${cyc} 03 ${NEST} &" >> poe.aaa
echo "$USHhref/preprocess_fv3_1h.sh ${cyc} 04 ${NEST} &" >> poe.aaa
echo "$USHhref/preprocess_fv3_1h.sh ${cyc} 05 ${NEST} &" >> poe.aaa
echo "$USHhref/preprocess_fv3_1h.sh ${cyc} 06 ${NEST} &" >> poe.aaa
echo "wait" >> poe.aaa

echo "#!/bin/sh  "                             >  poe.bbb
echo "$USHhref/preprocess_fv3_1h.sh ${cyc} 07 ${NEST} &" >> poe.bbb
echo "$USHhref/preprocess_fv3_1h.sh ${cyc} 08 ${NEST} &" >> poe.bbb
echo "$USHhref/preprocess_fv3_1h.sh ${cyc} 09 ${NEST} &" >> poe.bbb
echo "$USHhref/preprocess_fv3_1h.sh ${cyc} 10 ${NEST} &" >> poe.bbb
echo "$USHhref/preprocess_fv3_1h.sh ${cyc} 11 ${NEST} &" >> poe.bbb
echo "$USHhref/preprocess_fv3_1h.sh ${cyc} 12 ${NEST} &" >> poe.bbb
echo "wait" >> poe.bbb

echo "#!/bin/sh  "                             >  poe.ccc
echo "$USHhref/preprocess_fv3_1h.sh ${cyc} 13 ${NEST} &" >> poe.ccc
echo "$USHhref/preprocess_fv3_1h.sh ${cyc} 14 ${NEST} &" >> poe.ccc
echo "$USHhref/preprocess_fv3_1h.sh ${cyc} 15 ${NEST} &" >> poe.ccc
echo "$USHhref/preprocess_fv3_1h.sh ${cyc} 16 ${NEST} &" >> poe.ccc
echo "$USHhref/preprocess_fv3_1h.sh ${cyc} 17 ${NEST} &" >> poe.ccc
echo "$USHhref/preprocess_fv3_1h.sh ${cyc} 18 ${NEST} &" >> poe.ccc
echo "wait" >> poe.ccc

echo "#!/bin/sh  "                             >  poe.ddd
echo "$USHhref/preprocess_fv3_1h.sh ${cyc} 19 ${NEST} &" >> poe.ddd
echo "$USHhref/preprocess_fv3_1h.sh ${cyc} 20 ${NEST} &" >> poe.ddd
echo "$USHhref/preprocess_fv3_1h.sh ${cyc} 21 ${NEST} &" >> poe.ddd
echo "$USHhref/preprocess_fv3_1h.sh ${cyc} 22 ${NEST} &" >> poe.ddd
echo "$USHhref/preprocess_fv3_1h.sh ${cyc} 23 ${NEST} &" >> poe.ddd
echo "$USHhref/preprocess_fv3_1h.sh ${cyc} 24 ${NEST} &" >> poe.ddd
echo "wait" >> poe.ddd

echo "#!/bin/sh  "                             >  poe.eee
echo "$USHhref/preprocess_fv3_1h.sh ${cyc} 25 ${NEST} &" >> poe.eee
echo "$USHhref/preprocess_fv3_1h.sh ${cyc} 26 ${NEST} &" >> poe.eee
echo "$USHhref/preprocess_fv3_1h.sh ${cyc} 27 ${NEST} &" >> poe.eee
echo "$USHhref/preprocess_fv3_1h.sh ${cyc} 28 ${NEST} &" >> poe.eee
echo "$USHhref/preprocess_fv3_1h.sh ${cyc} 29 ${NEST} &" >> poe.eee
echo "$USHhref/preprocess_fv3_1h.sh ${cyc} 30 ${NEST} &" >> poe.eee
echo "wait" >> poe.eee

echo "#!/bin/sh  "                             >  poe.fff
echo "$USHhref/preprocess_fv3_1h.sh ${cyc} 31 ${NEST} &" >> poe.fff
echo "$USHhref/preprocess_fv3_1h.sh ${cyc} 32 ${NEST} &" >> poe.fff
echo "$USHhref/preprocess_fv3_1h.sh ${cyc} 33 ${NEST} &" >> poe.fff
echo "$USHhref/preprocess_fv3_1h.sh ${cyc} 34 ${NEST} &" >> poe.fff
echo "$USHhref/preprocess_fv3_1h.sh ${cyc} 35 ${NEST} &" >> poe.fff
echo "$USHhref/preprocess_fv3_1h.sh ${cyc} 36 ${NEST} &" >> poe.fff
echo "wait" >> poe.fff

echo "#!/bin/sh  "                             >  poe.ggg
echo "$USHhref/preprocess_fv3_1h.sh ${cyc} 37 ${NEST} &" >> poe.ggg
echo "$USHhref/preprocess_fv3_1h.sh ${cyc} 38 ${NEST} &" >> poe.ggg
echo "$USHhref/preprocess_fv3_1h.sh ${cyc} 39 ${NEST} &" >> poe.ggg
echo "$USHhref/preprocess_fv3_1h.sh ${cyc} 40 ${NEST} &" >> poe.ggg
echo "$USHhref/preprocess_fv3_1h.sh ${cyc} 41 ${NEST} &" >> poe.ggg
echo "$USHhref/preprocess_fv3_1h.sh ${cyc} 42 ${NEST} &" >> poe.ggg
echo "wait" >> poe.ggg

echo "#!/bin/sh  "                             >  poe.hhh
echo "$USHhref/preprocess_fv3_1h.sh ${cyc} 43 ${NEST} &" >> poe.hhh
echo "$USHhref/preprocess_fv3_1h.sh ${cyc} 44 ${NEST} &" >> poe.hhh
echo "$USHhref/preprocess_fv3_1h.sh ${cyc} 45 ${NEST} &" >> poe.hhh
echo "$USHhref/preprocess_fv3_1h.sh ${cyc} 46 ${NEST} &" >> poe.hhh
echo "$USHhref/preprocess_fv3_1h.sh ${cyc} 47 ${NEST} &" >> poe.hhh
echo "$USHhref/preprocess_fv3_1h.sh ${cyc} 48 ${NEST} &" >> poe.hhh
echo "wait" >> poe.hhh

echo "#!/bin/sh  "                             >  poe.iii
echo "$USHhref/preprocess_fv3_1h.sh ${cyc} 49 ${NEST} &" >> poe.iii
echo "$USHhref/preprocess_fv3_1h.sh ${cyc} 50 ${NEST} &" >> poe.iii
echo "$USHhref/preprocess_fv3_1h.sh ${cyc} 51 ${NEST} &" >> poe.iii
echo "$USHhref/preprocess_fv3_1h.sh ${cyc} 52 ${NEST} &" >> poe.iii
echo "$USHhref/preprocess_fv3_1h.sh ${cyc} 53 ${NEST} &" >> poe.iii
echo "$USHhref/preprocess_fv3_1h.sh ${cyc} 54 ${NEST} &" >> poe.iii
echo "wait" >> poe.iii

echo "#!/bin/sh  "                             >  poe.jjj
echo "$USHhref/preprocess_fv3_1h.sh ${cyc} 55 ${NEST} &" >> poe.jjj
echo "$USHhref/preprocess_fv3_1h.sh ${cyc} 56 ${NEST} &" >> poe.jjj
echo "$USHhref/preprocess_fv3_1h.sh ${cyc} 57 ${NEST} &" >> poe.jjj
echo "$USHhref/preprocess_fv3_1h.sh ${cyc} 58 ${NEST} &" >> poe.jjj
echo "$USHhref/preprocess_fv3_1h.sh ${cyc} 59 ${NEST} &" >> poe.jjj
echo "$USHhref/preprocess_fv3_1h.sh ${cyc} 60 ${NEST} &" >> poe.jjj
echo "wait" >> poe.jjj

chmod 775 ${DATA}/poe.aaa  ${DATA}/poe.bbb ${DATA}/poe.ccc
chmod 775 ${DATA}/poe.ddd  ${DATA}/poe.eee ${DATA}/poe.fff
chmod 775 ${DATA}/poe.ggg  ${DATA}/poe.hhh ${DATA}/poe.iii ${DATA}/poe.jjj

aprun -n 1 -N 1 -d 7 ${DATA}/poe.aaa &
aprun -n 1 -N 1 -d 6 ${DATA}/poe.bbb &
aprun -n 1 -N 1 -d 6 ${DATA}/poe.ccc &
aprun -n 1 -N 1 -d 6 ${DATA}/poe.ddd &
aprun -n 1 -N 1 -d 6 ${DATA}/poe.eee &
aprun -n 1 -N 1 -d 6 ${DATA}/poe.fff &
aprun -n 1 -N 1 -d 6 ${DATA}/poe.ggg &
aprun -n 1 -N 1 -d 6 ${DATA}/poe.hhh &
aprun -n 1 -N 1 -d 6 ${DATA}/poe.iii &
aprun -n 1 -N 1 -d 6 ${DATA}/poe.jjj &
wait


## deleting preprocessing outputs from 6 cycles prior to ${PDY}${cyc}

pdycycdel=`$NDATE -144 ${PDY}${cyc}`

PDYdel=`echo $pdycycdel | cut -c1-8`
cycdel=`echo $pdycycdel | cut -c9-10`

echo will delete from $COMOUTfv3.${PDYdel}/fv3s.t${cycdel}z

rm $COMOUTfv3.${PDYdel}/fv3s.t${cycdel}z.*grib2

cd $DATAROOT
if [ $KEEPDATA = NO ]; then rm -rf $DATA; fi

date
