#!/bin/sh 

########################################
# Preliminary data setup step
########################################
set -xa

export PS4='$SECONDS + ' 
date

###############################
# Specify NET and RUN name
###############################
export NET=${NET:-href}
export RUN=${RUN:-href}

export IOBUF_PARAMS='*:size=8M:count=8'


###############################################################
# This block can be modified for different Production test
# environment. This is used for operational testings
###############################################################

export COMINhiresw=/gpfs/hps/nco/ops/com/hiresw/prod
# export COMINnam=/gpfs/hps2/ptmp/Matthew.Pyle/com/nam/prod
export COMINpcpanl=${COMROOTp2}/pcpanl/prod
# export COMINhrrr=/gpfs/hps2/ptmp/Matthew.Pyle/com/hrrr/prod
# export COMINfv3=/gpfs/hps2/ptmp/Matthew.Pyle/com/fv3/prod
# export COMINclimo=${COMOUT}/../climo_bin

export HOMEhref=${HOMEhref:-/nw${envir}/href.${model_ver}}
export EXEChref=${EXEChref:-$HOMEhref/exec}
export FIXhref=${FIXhref:-$HOMEhref/fix}
export PARMhref=${PARMhref:-$HOMEhref/parm}
export USHhref=${USHhref:-$HOMEhref/ush}

########################################################### 
# obtain unique process id (pid) and make temp directories
###########################################################

export pid=$$
export DATA=${DATA:-${DATAROOT}/href_qpfclimo_${cyc}_${envir}}
mkdir -p $DATA
rm -rf $DATA/*
cd $DATA 

####################################
# File To Log Msgs
####################################
export jlogfile=${jlogfile:-$COMROOT/logs/jlogfile}


####################################
# Determine Job Output Name on System
####################################
export pgmout="OUTPUT.$$"

export cycle=${cycle:-t${cyc}z}


##################################################
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
##################################################
export SENDCOM=${SENDCOM:-YES}
export SENDECF=${SENDECF:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDDBN_NTC=${SENDDBN_NTC:-NO}

###################################
# Set up the UTILITIES
###################################

msg="JOB $job HAS BEGUN"
postmsg "$jlogfile" "$msg"

setpdy.sh
. PDY


 
##############################################
# Define running directory and COM directories
##############################################

if [ "$RUN_ENVIR" != nco ] ; then
  export COMOUT=${COMOUT:-${MYCOMROOT}/${NET}/${envir}/${RUN}.${PDY}_exp}
  export COMOUTPERM=${MYCOMROOTPERM}/${NET}/${envir}/${RUN}.${PDY}_exp
else
  export COMOUT=${COMOUT:-${COMROOT}/${NET}/${envir}/${RUN}.${PDY}}
fi

if [ ! -d $COMOUT ] ; then
 mkdir -p $COMOUT/ensprod
 mkdir -p $COMOUT/verf_g2g
fi

if [ ! -d $COMOUTPERM ] ; then
 mkdir -p $COMOUTPERM/ensprod
fi


########################################################
# Execute the script.

python ${HOMEhref}/scripts/build_qpf_climo.py 
########################################################

msg="JOB $job HREF_QPFCLIMO HAS COMPLETED NORMALLY."
postmsg "$jlogfile" "$msg"

cd $DATAROOT
if [ $KEEPDATA = NO ]; then rm -rf $DATA; fi

date
