#!/bin/sh

#############################################################
# HREF RUNALL 
# 02/02/2015 Binbin Zhou, create for run all scripts 
#############################################################

########################################
# Preliminary data setup step
########################################

set -xa
export PS4='$SECONDS + ' 
date

###################################
# Specify NET and RUN Name and model
####################################
export NET=${NET:-hiresw}
export RUN=${RUN:-href}

export IOBUF_PARAMS='*:size=8M:count=8'

###############################################################
# This block can be modified for different Production test
# environment. This is used for operational testings
###############################################################

## PDY not included here as pull data from PDYm1 as well

echo here with COMINhiresw $COMINhiresw
export COMINhiresw=${COMINhiresw:-$(compath.py hiresw/prod/hiresw)}

echo now here with COMINhiresw $COMINhiresw

export COMINnam=${COMINnam:-/gpfs/hps3/ptmp/Matthew.Pyle/com/nam/prod/nam}
export COMINhrrr=${COMINhrrr:-/gpfs/hps3/ptmp/Matthew.Pyle/com/hrrr/prod/hrrr}
export COMINfv3=${COMINfv3:-/gpfs/hps3/ptmp/Matthew.Pyle/com/fv3/prod/fv3}
export HOMEhref=${HOMEhref:-$NWROOT/href.${href_ver}} 
export EXEChref=${EXEChref:-$HOMEhref/exec}
export PARMhref=${PARMhref:-$HOMEhref/parm}
export USHhref=${USHhref:-$HOMEhref/ush}
export FIXhref=${FIXhref:-$HOMEhref/fix}
export SCRIPTShref=${SCRIPTShref:-$HOMEhref/scripts}

###########################################################
# obtain unique process id (pid) and make temp directories
###########################################################

export pid=$$
export DATA=${DATA:-${DATAROOT}/href_ensprodv3_${NEST}_${cyc}_${envir}.${pid}}
mkdir -p $DATA
rm -rf $DATA/*
cd $DATA

####################################
# File To Log Msgs
####################################
export jlogfile=${jlogfile:-$COMROOT/logs/jlogfile}

####################################
# Determine Job Output Name on System
####################################
export pgmout="OUTPUT.$$"

export cycle=${cycle:-t${cyc}z}

##################################################
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
##################################################

export SENDCOM=${SENDCOM:-YES}
export SENDECF=${SENDECF:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDDBN_NTC=${SENDDBN_NTC:-NO}

###################################
# Set up the UTILITIES
###################################

msg="JOB $job HAS BEGUN"
postmsg "$jlogfile" "$msg"

#
# Run setpdy and initialize PDY variables
#

setpdy.sh
. PDY

##############################################
# Define running directory and COM directories
##############################################

if [ "$RUN_ENVIR" != nco ] ; then
  export COMOUT=${MYCOMROOT}/${NET}/${envir}/${RUN}.${PDY}_expv3
  export COMINffg=${MYCOMROOT}/${NET}/${envir}/${RUN}.${PDY}_expv3
  export COMINffgm1=${MYCOMROOT}/${NET}/${envir}/${RUN}.${PDYm1}_expv3
else
  export COMOUT=${COMOUT:-${COMROOT}/${NET}/${envir}/${RUN}.${PDY}}
  export COMINffg=${COMINffg:-${COMROOT}/${NET}/${envir}/${RUN}.${PDY}}
  export COMINffgm1=${COMINffg:-${COMROOT}/${NET}/${envir}/${RUN}.${PDYm1}}
fi

if [ ! -d $COMOUT/ensprod ] ; then 
 mkdir -p $COMOUT/ensprod
 mkdir -p $COMOUT/verf_g2g
 mkdir -p $COMOUT/wmo
fi


#######################################################
# Pass information which is needed to run the Script
#######################################################

# export VERBOSE=YES

###################################################
# Execute the Script exhref_ensprod.sh.ecf

rm -rf poe.*


hrlist="01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 \
34 35 36 37 38 39 40 41 42 43 44 45 46 47 48"

for hr in $hrlist
do
echo "$SCRIPTShref/exhref_ensprod_link.sh.ecf $hr" >> poe.link.all
echo "$SCRIPTShref/exhref_ensprod.sh.ecf $hr" >> poe.ensprod.all
done


chmod 775  poe.link.all
chmod 775 poe.ensprod.all

if [ ${NEST}  =  "conus" ]
then
export NODES=16
aprun -j 1 -n 48 -N 3 -d 1 cfp poe.link.all
export err=$?; err_chk
aprun -j 1 -n 48 -N 3 -d 1 cfp poe.ensprod.all
export err=$?; err_chk

elif [ $NEST = "ak" ]
then
export NODES=6
aprun -j 1 -n 48 -N 8 -d 1 cfp poe.link.all
export err=$?; err_chk
aprun -j 1 -n 48 -N 8 -d 1 cfp poe.ensprod.all
export err=$?; err_chk

elif [ $NEST = "pr" -o $NEST = "hi" ]
then
export NODES=4
aprun -j 1 -n 48 -N 12 -d 1 cfp poe.link.all
export err=$?; err_chk
aprun -j 1 -n 48 -N 12 -d 1 cfp poe.ensprod.all
export err=$?; err_chk

fi




export err=$?; err_chk

msg"JOB $job HAS COMPLETED NORMALLY."
postmsg "$jlogfile" "$msg"
date



cd $DATAROOT
if [ $KEEPDATA = NO ]; then rm -rf $DATA; fi

date
