#!/bin/ksh 

########################################
# Preliminary data setup step
########################################
set -xa
export PS4='$SECONDS + ' 
date

###################################
# Specify NET and RUN Name and model
####################################
export NET=${NET:-hiresw}
export RUN=${RUN:-href}

export IOBUF_PARAMS='*:size=8M:count=8'

###############################################################
# This block can be modified for different Production test
# environment. This is used for operational testings
###############################################################

## PDY not included here as pull data from PDYm1 as well

export COMINhiresw=${COMINhiresw:-$(compath.py hiresw/prod/hiresw)}

# needed?
export COMINpcpanl=${COMINpcpanl:-$(compath.py pcpanl/prod)}

export HOMEhref=${HOMEhref:-$NWROOT/href.${href_ver}}
export EXEChref=${EXEChref:-$HOMEhref/exec}
export PARMhref=${PARMhref:-$HOMEhref/parm}
export USHhref=${USHhref:-$HOMEhref/ush}
export FIXhref=${FIXhref:-$HOMEhref/fix}
export SCRIPTShref=${SCRIPTShref:-$HOMEhref/scripts}


########################################################### 
# obtain unique process id (pid) and make temp directories
###########################################################
export pid=$$
export DATA=${DATA:-${DATAROOT}/href_qpfeasfrac_${cyc}_${envir}.${pid}}
mkdir -p $DATA
rm -rf $DATA/*
cd $DATA

####################################
# File To Log Msgs
####################################
export jlogfile=${jlogfile:-$COMROOT/logs/jlogfile}


####################################
# Determine Job Output Name on System
####################################
export pgmout="OUTPUT.$$"

export cycle=${cycle:-t${cyc}z}


##################################################
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
##################################################
export SENDCOM=${SENDCOM:-YES}
export SENDECF=${SENDECF:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDDBN_NTC=${SENDDBN_NTC:-NO}

###################################
# Set up the UTILITIES
###################################
msg="JOB $job HAS BEGUN"
postmsg "$jlogfile" "$msg"

setpdy.sh
. PDY


##############################################
# Define running directory and COM directories
##############################################

if [ "$RUN_ENVIR" != nco ] ; then
  export COMOUT=${COMOUT:-${MYCOMROOT}/${NET}/${envir}/${RUN}.${PDY}_expv3}
  export COMOUTPERM=${MYCOMROOTPERM}/${NET}/${envir}/${RUN}.${PDY}_expv3
else
  export COMOUT=${COMOUT:-${COMROOT}/${NET}/${envir}/${RUN}.${PDY}}
fi

if [ ! -d $COMOUT ] ; then
 mkdir -p $COMOUT/ensprod
 mkdir -p $COMOUT/verf_g2g
fi

if [ ! -d $COMOUTPERM ] ; then
 mkdir -p $COMOUTPERM/ensprod
fi


 
########################################################
# Execute the script.

if [ -e poe.qpf_6 ] 
then
rm poe.*
fi

hrs="24 27 30 33 36 39 42 45 48"
for fhr in $hrs
do
echo "cd ${DATA}; mkdir qpf_${fhr}_24; cd qpf_${fhr}_24 ; python ${HOMEhref}/scripts/make_easfracqpf_combo.py ${fhr} 24 >&  qpf_combo_${dom}_${cyc}_24h_${fhr}.log" >> poe.qpf_snow
done

hrs="06 09 12 15 18 21 24 27 30 33 36 39 42 45 48"
for fhr in $hrs
do
echo "cd ${DATA}; mkdir qpf_${fhr}_6; cd qpf_${fhr}_6 ; python ${HOMEhref}/scripts/make_easfracqpf_combo.py ${fhr} 6 >& qpf_combo_${dom}_${cyc}_6h_${fhr}.log" >> poe.qpf_snow
echo "cd ${DATA}; mkdir snow_${fhr}_6; cd snow_${fhr}_6; python ${HOMEhref}/scripts/make_easfracsnow_combo.py ${fhr} 6 >& snow_combo_${dom}_${cyc}_6h_${fhr}.log" >> poe.qpf_snow
done

hrs="12 15 18 21 24 27 30 33 36 39 42 45 48"
for fhr in $hrs
do
echo "cd ${DATA}; mkdir qpf_${fhr}_12; cd qpf_${fhr}_12 ; python ${HOMEhref}/scripts/make_easfracqpf_combo.py ${fhr} 12 >&  qpf_combo_${dom}_${cyc}_12h_${fhr}.log" >> poe.qpf_snow
done


hrs="03 06 09 12 15 18 21 24 27 30 33 36 39 42 45 48"
for fhr in $hrs
do
echo "cd ${DATA}; mkdir qpf_${fhr}_3; cd qpf_${fhr}_3 ; python ${HOMEhref}/scripts/make_easfracqpf_combo.py ${fhr} 3  >& qpf_combo_${dom}_${cyc}_3h_${fhr}.log" >> poe.qpf_snow
echo "cd ${DATA}; mkdir snow_${fhr}_3; cd snow_${fhr}_3; python ${HOMEhref}/scripts/make_easfracsnow_combo.py ${fhr} 3 >& snow_combo_${dom}_${cyc}_3h_${fhr}.log" >> poe.qpf_snow
done

hrs="01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48"
for fhr in $hrs
do
echo "cd ${DATA}; mkdir qpf_${fhr}_1; cd qpf_${fhr}_1 ; python ${HOMEhref}/scripts/make_easfracqpf_combo.py ${fhr} 1 >& qpf_combo_${dom}_${cyc}_1h_${fhr}.log" >> poe.qpf_snow
echo "cd ${DATA}; mkdir snow_${fhr}_1; cd snow_${fhr}_1; python ${HOMEhref}/scripts/make_easfracsnow_combo.py ${fhr} 1 >&  snow_combo_${dom}_${cyc}_1h_${fhr}.log" >> poe.qpf_snow
done


chmod 775 poe.qpf_snow

if [ ${dom}  =  "conus" ]
then
# export NODES=10
# aprun -j 1 -n 180 -N 18 -d 1 cfp poe.qpf_snow
export NODES=12
aprun -j 1 -n 180 -N 15 -d 1 cfp poe.qpf_snow

elif [ $dom = "ak" ]
then
export NODES=6
aprun -j 1 -n 90 -N 15 -d 1 cfp poe.qpf_snow

elif [ $dom = "pr" -o $dom = "hi" ]
then
export NODES=4
aprun -j 1 -n 64 -N 16 -d 1 cfp poe.qpf_snow

fi


export err=$?; err_chk


if [ $err -eq 0 ]
then

fhr=01

while [ $fhr -le 48 ]
do

if [ ! -e $DATA/href.t${cyc}z.${dom}.pqpf01_easfrac.f${fhr}.grib2 ]
then
msg="FATAL ERROR: missing $DATA/href.t${cyc}z.${dom}.pqpf01_easfrac.f${fhr}.grib2"
err_exit $msg
fi
if [ ! -e $DATA/href.t${cyc}z.${dom}.snow01_easfrac.f${fhr}.grib2 ]
then
msg="FATAL ERROR: missing $DATA/href.t${cyc}z.${dom}.snow01_easfrac.f${fhr}.grib2"
err_exit $msg
fi

cat $DATA/href.t${cyc}z.${dom}.pqpf01_easfrac.f${fhr}.grib2 > $DATA/href.t${cyc}z.${dom}.eas.f${fhr}.grib2
cat $DATA/href.t${cyc}z.${dom}.snow01_easfrac.f${fhr}.grib2 >> $DATA/href.t${cyc}z.${dom}.eas.f${fhr}.grib2

if [ $((fhr%3)) -eq 0 ]
then

if [ ! -e $DATA/href.t${cyc}z.${dom}.pqpf03_easfrac.f${fhr}.grib2 ]
then
msg="FATAL ERROR: missing $DATA/href.t${cyc}z.${dom}.pqpf03_easfrac.f${fhr}.grib2"
err_exit $msg
fi

if [ ! -e $DATA/href.t${cyc}z.${dom}.snow03_easfrac.f${fhr}.grib2 ]
then
msg="FATAL ERROR: missing $DATA/href.t${cyc}z.${dom}.snow03_easfrac.f${fhr}.grib2"
err_exit $msg
fi

cat $DATA/href.t${cyc}z.${dom}.pqpf03_easfrac.f${fhr}.grib2 >> $DATA/href.t${cyc}z.${dom}.eas.f${fhr}.grib2
cat $DATA/href.t${cyc}z.${dom}.snow03_easfrac.f${fhr}.grib2 >> $DATA/href.t${cyc}z.${dom}.eas.f${fhr}.grib2

fi

if [ $((fhr%3)) -eq 0 -a $fhr -ge 6 ]
then

if [ ! -e $DATA/href.t${cyc}z.${dom}.pqpf06_easfrac.f${fhr}.grib2 ]
then
msg="FATAL ERROR: missing $DATA/href.t${cyc}z.${dom}.pqpf06_easfrac.f${fhr}.grib2"
err_exit $msg
fi

if [ ! -e $DATA/href.t${cyc}z.${dom}.snow06_easfrac.f${fhr}.grib2 ]
then
msg="FATAL ERROR: missing $DATA/href.t${cyc}z.${dom}.snow06_easfrac.f${fhr}.grib2"
err_exit $msg
fi

cat $DATA/href.t${cyc}z.${dom}.pqpf06_easfrac.f${fhr}.grib2 >> $DATA/href.t${cyc}z.${dom}.eas.f${fhr}.grib2
cat $DATA/href.t${cyc}z.${dom}.snow06_easfrac.f${fhr}.grib2 >> $DATA/href.t${cyc}z.${dom}.eas.f${fhr}.grib2

fi

if [ $((fhr%3)) -eq 0 -a $fhr -ge 12 ]
then

if [ ! -e $DATA/href.t${cyc}z.${dom}.pqpf12_easfrac.f${fhr}.grib2 ]
then
msg="FATAL ERROR: missing $DATA/href.t${cyc}z.${dom}.pqpf12_easfrac.f${fhr}.grib2"
err_exit $msg
fi

cat $DATA/href.t${cyc}z.${dom}.pqpf12_easfrac.f${fhr}.grib2 >> $DATA/href.t${cyc}z.${dom}.eas.f${fhr}.grib2
fi

if [ $fhr -eq 24 -o $fhr -eq 27 -o $fhr -eq 30 -o $fhr -eq 33 -o $fhr -eq 36 -o $fhr -eq 39 \
                 -o $fhr -eq 42 -o $fhr -eq 45 -o $fhr -eq 48 ]
then

if [ ! -e $DATA/href.t${cyc}z.${dom}.pqpf24_easfrac.f${fhr}.grib2 ]
then
msg="FATAL ERROR: missing $DATA/href.t${cyc}z.${dom}.pqpf24_easfrac.f${fhr}.grib2"
err_exit $msg
fi

cat $DATA/href.t${cyc}z.${dom}.pqpf24_easfrac.f${fhr}.grib2 >> $DATA/href.t${cyc}z.${dom}.eas.f${fhr}.grib2
fi

if [ $SENDCOM == 'YES' ]
then
cp $DATA/href.t${cyc}z.${dom}.eas.f${fhr}.grib2 ${COMOUT}/ensprod/
## $WGRIB2 $DATA/href.t${cyc}z.${dom}.eas.f${fhr}.grib2 -match APCP -grib ${COMOUT}/ensprod/href.t${cyc}z.${dom}.easffair.f${fhr}.grib2
$WGRIB2 ${COMOUT}/ensprod/href.t${cyc}z.${dom}.eas.f${fhr}.grib2 -s > ${COMOUT}/ensprod/href.t${cyc}z.${dom}.eas.f${fhr}.grib2.idx
fi

let fhr=fhr+1

if [ $fhr -lt 10 ]
then
fhr=0${fhr}
fi

done

fi


########################################################

msg"JOB $job HAS COMPLETED NORMALLY."
postmsg "$jlogfile" "$msg"

cd $DATAROOT
if [ $KEEPDATA = NO ]; then rm -rf $DATA; fi

date
