#!/bin/sh

set -xa
# #### 08/25/1999 ###################
# SET SHELL PROCESSING VARIABLES
# ###################################
export PS4='$SECONDS + ' 
date

###########################################################
# obtain unique process id (pid) and make temp directories
###########################################################
export DATA=${DATA:-${DATAROOT}/${jobid}}
mkdir $DATA
cd $DATA 

# Run setpdy and initialize PDY variables
export cycle=${cycle:-t${cyc}z}
setpdy.sh
. ./PDY

##################################################
# SENDECF  - Flag Events on ecFLOW
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
##################################################
export SENDCOM=${SENDCOM:-YES}
export SENDECF=${SENDECF:-YES}
export SENDDBN=${SENDDBN:-YES}

export HOMEhref=${HOMEhref:-$NWROOT/href.${href_ver}}
export GEMPAKhref=${GEMPAKhref:-$HOMEhref/gempak}

export finc=1
export fend=48
export fstart=01

export DBN_ALERT_TYPE=${DBN_ALERT_TYPE:-HREF_GEMPAK}

###############################
# Specify NET and RUN name
###############################
export NET=${NET:-hiresw}
export RUN=${RUN:-href} 
  
export COMOUT=${COMOUT:-${COMROOT}/${RUN}/${href_ver}/${RUN}.${PDY}/gempak}
export COMIN=${COMIN:-${COMROOT}/${RUN}/${href_ver}/${RUN}.${PDY}/ensprod}

if [ ! -f $COMOUT ] ; then
  mkdir -p -m 775 $COMOUT
fi
 
export pgmout="OUTPUT.$$"

env

#################################################################
# Execute the script
rm -f poescript

echo "$HOMEhref/scripts/exhref_nawips.sh.ecf mean &> $DATA/${NEST}_mean.$$ " >>poescript
echo "$HOMEhref/scripts/exhref_nawips.sh.ecf pmmn &> $DATA/${NEST}_pmmn.$$ " >>poescript
echo "$HOMEhref/scripts/exhref_nawips.sh.ecf avrg &> $DATA/${NEST}_avrg.$$ " >>poescript
echo "$HOMEhref/scripts/exhref_nawips.sh.ecf prob &> $DATA/${NEST}_prob.$$ " >>poescript
echo "$HOMEhref/scripts/exhref_nawips.sh.ecf sprd &> $DATA/${NEST}_sprd.$$ " >>poescript
echo "$HOMEhref/scripts/exhref_nawips.sh.ecf eas  &> $DATA/${NEST}_eas.$$  " >>poescript
echo "$HOMEhref/scripts/exhref_nawips.sh.ecf lpmm  &> $DATA/${NEST}_lpmm.$$  " >>poescript

if [ ${NEST} =  'conus' ]
then
echo "$HOMEhref/scripts/exhref_nawips.sh.ecf ffri  &> $DATA/${NEST}_ffri.$$  " >>poescript
fi

mpiexec -n $NTASK -ppn $PTILE --configfile ./poescript
export err=$?; err_chk

cat $DATA/${NEST}_mean.$$
cat $DATA/${NEST}_pmmn.$$
cat $DATA/${NEST}_avrg.$$
cat $DATA/${NEST}_prob.$$
cat $DATA/${NEST}_sprd.$$
cat $DATA/${NEST}_eas.$$
cat $DATA/${NEST}_lpmm.$$
cat $DATA/${NEST}_ffri.$$
#################################################################

cd ${DATAROOT}
if [ $KEEPDATA = NO ]; then rm -rf $DATA; fi
date
