#!/bin/sh

set -xa
# #### 08/25/1999 ###################
# SET SHELL PROCESSING VARIABLES
# ###################################
export PS4='$SECONDS + ' 
date

###########################################################
# obtain unique process id (pid) and make temp directories
###########################################################
export DATA=${DATA:-${DATAROOT:?}/${jobid:?}}
mkdir $DATA
cd $DATA 

# Run setpdy and initialize PDY variables
export cycle=${cycle:-t${cyc}z}
setpdy.sh
. ./PDY

##################################################
# SENDECF  - Flag Events on ecFLOW
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
##################################################
export SENDCOM=${SENDCOM:-YES}
export SENDECF=${SENDECF:-YES}
export SENDDBN=${SENDDBN:-YES}

export HOMEhref=${HOMEhref:-$NWROOT/href.${href_ver}}
export USHhref=${USHhref:-$HOMEhref/ush}
export PARMwmo=${PARMwmo:-$HOMEhref/parm/wmo}

###############################
# Specify NET and RUN name
###############################
export NET=${NET:-hiresw}
export RUN=${RUN:-href} 
  
if [ "$RUN_ENVIR" != nco ] ; then
 export COMIN=${COMIN:-${MYCOMROOT}/${NET}/${envir}/href.${PDY}_expv3/ensprod}
 export COMOUT=${COMOUT:-${MYCOMROOT}/${NET}/${envir}/href.${PDY}_expv3/wmo}
else
 export COMIN=${COMIN:-${COMROOT}/${NET}/${envir}/${RUN}.${PDY}/ensprod}
 export COMOUT=${COMOUT:-${COMROOT}/${NET}/${envir}/${RUN}.${PDY}/wmo}
fi

if [ ! -f $COMOUT ] ; then
  mkdir -p -m 775 $COMOUT
fi

export pgmout=OUTPUT.$$

#################################################################
# Execute the script
$HOMEhref/scripts/exhref_awips.sh.ecf
#################################################################

cd ${DATAROOT}
echo in AWIPS jobs down here with KEEPDATA $KEEPDATA
echo in AWIPS jobs down here with DATA $DATA
if [ $KEEPDATA = NO ]; then rm -rf $DATA; fi
date
