#!/bin/sh

#############################################################
# HREF RUNALL 
# 02/02/2015 Binbin Zhou, create for run all scripts 
#############################################################

########################################
# Preliminary data setup step
########################################

set -xa
export PS4='$SECONDS + ' 
date

###################################
# Specify NET and RUN Name and model
####################################
export NET=${NET:-hiresw}
export RUN=${RUN:-href}

export IOBUF_PARAMS='*:size=8M:count=8'

###############################################################
# This block can be modified for different Production test
# environment. This is used for operational testings
###############################################################

## PDY not included here as pull data from PDYm1 as well

export COMINhiresw=${COMINhiresw:-${COMROOT}/${NET}/${envir}/hiresw}
export COMINnam=${COMINnam:-${COMROOTp2}/nam/prod/nam}
export HOMEhref=${HOMEhref:-$NWROOT/href.${href_ver}} 
export EXEChref=${EXEChref:-$HOMEhref/exec}
export PARMhref=${PARMhref:-$HOMEhref/parm}
export USHhref=${USHhref:-$HOMEhref/ush}
export FIXhref=${FIXhref:-$HOMEhref/fix}
export SCRIPTShref=${SCRIPTShref:-$HOMEhref/scripts}

###########################################################
# obtain unique process id (pid) and make temp directories
###########################################################

export pid=$$
export DATA=${DATA:-${DATAROOT}/href_ensprodpreproc_${NEST}_${cyc}_${envir}.${pid}}
mkdir -p $DATA
rm -rf $DATA/*
cd $DATA

####################################
# File To Log Msgs
####################################
export jlogfile=${jlogfile:-$COMROOT/logs/jlogfile}

####################################
# Determine Job Output Name on System
####################################
export pgmout="OUTPUT.$$"

export cycle=${cycle:-t${cyc}z}

##################################################
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
##################################################

export SENDCOM=${SENDCOM:-YES}
export SENDECF=${SENDECF:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDDBN_NTC=${SENDDBN_NTC:-NO}

###################################
# Set up the UTILITIES
###################################

msg="JOB $job HAS BEGUN"
postmsg "$jlogfile" "$msg"

#
# Run setpdy and initialize PDY variables
#

# setpdy.sh
# . PDY

export PDY=${DATE}
export PDYm1=`$NDATE -24 ${DATE}00 | cut -c1-8`

echo PDY PDYm1 in job $PDY $PDYm1


##############################################
# Define running directory and COM directories
##############################################

if [ "$RUN_ENVIR" != nco ] ; then
  export COMOUT=${MYCOMROOT}/${NET}/${envir}/${RUN}.${PDY}_exp
else
  export COMOUT=${COMOUT:-${COMROOT}/${NET}/${envir}/${RUN}.${PDY}}
fi

if [ ! -d $COMOUT ] ; then 
 mkdir -p $COMOUT/ensprod
 mkdir -p $COMOUT/verf_g2g
fi

#######################################################
# Pass information which is needed to run the Script
#######################################################

# export VERBOSE=YES

###################################################
# Execute the Script exhref_ensprod.sh.ecf

rm -rf poe.*


if [ $NEST = "conus" ]
then

echo "#!/bin/sh  "                             >  poe.a
echo "$USHhref/preprocess_hrrr.sh.ecf_1h_retro ${cyc} 00 ${PDY}  &" >> poe.a
echo "$USHhref/preprocess_hrrr.sh.ecf_1h_retro ${cyc} 01 ${PDY}  &" >> poe.a
echo "$USHhref/preprocess_hrrr.sh.ecf_1h_retro ${cyc} 02 ${PDY}  &" >> poe.a
echo "$USHhref/preprocess_hrrr.sh.ecf_1h_retro ${cyc} 03 ${PDY}  &" >> poe.a
echo "$USHhref/preprocess_hrrr.sh.ecf_1h_retro ${cyc} 04 ${PDY}  &" >> poe.a
echo "$USHhref/preprocess_hrrr.sh.ecf_1h_retro ${cyc} 05 ${PDY}  &" >> poe.a
echo "$USHhref/preprocess_hrrr.sh.ecf_1h_retro ${cyc} 06 ${PDY}  &" >> poe.a
echo "$USHhref/preprocess_hrrr.sh.ecf_1h_retro ${cyc} 07 ${PDY}  &" >> poe.a
echo "$USHhref/preprocess_hrrr.sh.ecf_1h_retro ${cyc} 08 ${PDY}  &" >> poe.a
echo "$USHhref/preprocess_hrrr.sh.ecf_1h_retro ${cyc} 09 ${PDY}  &" >> poe.a
echo "$USHhref/preprocess_hrrr.sh.ecf_1h_retro ${cyc} 10 ${PDY}  &" >> poe.a
echo "$USHhref/preprocess_hrrr.sh.ecf_1h_retro ${cyc} 11 ${PDY}  &" >> poe.a
echo "$USHhref/preprocess_hrrr.sh.ecf_1h_retro ${cyc} 12 ${PDY}  &" >> poe.a
echo "wait" >> poe.a

echo "#!/bin/sh  "                             >  poe.b
echo "$USHhref/preprocess_hrrr.sh.ecf_1h_retro ${cyc} 13 ${PDY}  &" >> poe.b
echo "$USHhref/preprocess_hrrr.sh.ecf_1h_retro ${cyc} 14 ${PDY}  &" >> poe.b
echo "$USHhref/preprocess_hrrr.sh.ecf_1h_retro ${cyc} 15 ${PDY}  &" >> poe.b
echo "$USHhref/preprocess_hrrr.sh.ecf_1h_retro ${cyc} 16 ${PDY}  &" >> poe.b
echo "$USHhref/preprocess_hrrr.sh.ecf_1h_retro ${cyc} 17 ${PDY}  &" >> poe.b
echo "$USHhref/preprocess_hrrr.sh.ecf_1h_retro ${cyc} 18 ${PDY}  &" >> poe.b
echo "$USHhref/preprocess_hrrr.sh.ecf_1h_retro ${cyc} 19 ${PDY}  &" >> poe.b
echo "$USHhref/preprocess_hrrr.sh.ecf_1h_retro ${cyc} 20 ${PDY}  &" >> poe.b
echo "$USHhref/preprocess_hrrr.sh.ecf_1h_retro ${cyc} 21 ${PDY}  &" >> poe.b
echo "$USHhref/preprocess_hrrr.sh.ecf_1h_retro ${cyc} 22 ${PDY}  &" >> poe.b
echo "$USHhref/preprocess_hrrr.sh.ecf_1h_retro ${cyc} 23 ${PDY}  &" >> poe.b
echo "$USHhref/preprocess_hrrr.sh.ecf_1h_retro ${cyc} 24 ${PDY}  &" >> poe.b
echo "wait" >> poe.b

echo "#!/bin/sh  "                             >  poe.c
echo "$USHhref/preprocess_hrrr.sh.ecf_1h_retro ${cyc} 25 ${PDY}  &" >> poe.c
echo "$USHhref/preprocess_hrrr.sh.ecf_1h_retro ${cyc} 26 ${PDY}  &" >> poe.c
echo "$USHhref/preprocess_hrrr.sh.ecf_1h_retro ${cyc} 27 ${PDY}  &" >> poe.c
echo "$USHhref/preprocess_hrrr.sh.ecf_1h_retro ${cyc} 28 ${PDY}  &" >> poe.c
echo "$USHhref/preprocess_hrrr.sh.ecf_1h_retro ${cyc} 29 ${PDY}  &" >> poe.c
echo "$USHhref/preprocess_hrrr.sh.ecf_1h_retro ${cyc} 30 ${PDY}  &" >> poe.c
echo "$USHhref/preprocess_hrrr.sh.ecf_1h_retro ${cyc} 31 ${PDY}  &" >> poe.c
echo "$USHhref/preprocess_hrrr.sh.ecf_1h_retro ${cyc} 32 ${PDY}  &" >> poe.c
echo "$USHhref/preprocess_hrrr.sh.ecf_1h_retro ${cyc} 33 ${PDY}  &" >> poe.c
echo "$USHhref/preprocess_hrrr.sh.ecf_1h_retro ${cyc} 34 ${PDY}  &" >> poe.c
echo "$USHhref/preprocess_hrrr.sh.ecf_1h_retro ${cyc} 35 ${PDY}  &" >> poe.c
echo "$USHhref/preprocess_hrrr.sh.ecf_1h_retro ${cyc} 36 ${PDY}  &" >> poe.c
echo "wait" >> poe.c


echo "#!/bin/sh  "                             >  poe.d
echo "$USHhref/preprocess_nam.sh.ecf_1h_retro ${cyc} 00 ${PDY}  &" >> poe.d
echo "$USHhref/preprocess_nam.sh.ecf_1h_retro ${cyc} 01 ${PDY}  &" >> poe.d
echo "$USHhref/preprocess_nam.sh.ecf_1h_retro ${cyc} 02 ${PDY}  &" >> poe.d
echo "$USHhref/preprocess_nam.sh.ecf_1h_retro ${cyc} 03 ${PDY}  &" >> poe.d
echo "$USHhref/preprocess_nam.sh.ecf_1h_retro ${cyc} 04 ${PDY}  &" >> poe.d
echo "$USHhref/preprocess_nam.sh.ecf_1h_retro ${cyc} 05 ${PDY}  &" >> poe.d
echo "$USHhref/preprocess_nam.sh.ecf_1h_retro ${cyc} 06 ${PDY}  &" >> poe.d
echo "$USHhref/preprocess_nam.sh.ecf_1h_retro ${cyc} 07 ${PDY}  &" >> poe.d
echo "$USHhref/preprocess_nam.sh.ecf_1h_retro ${cyc} 08 ${PDY}  &" >> poe.d
echo "$USHhref/preprocess_nam.sh.ecf_1h_retro ${cyc} 09 ${PDY}  &" >> poe.d
echo "$USHhref/preprocess_nam.sh.ecf_1h_retro ${cyc} 10 ${PDY}  &" >> poe.d
echo "$USHhref/preprocess_nam.sh.ecf_1h_retro ${cyc} 11 ${PDY}  &" >> poe.d
echo "wait" >> poe.d

echo "#!/bin/sh  "                             >  poe.e
echo "$USHhref/preprocess_nam.sh.ecf_1h_retro ${cyc} 12 ${PDY}  &" >> poe.e
echo "$USHhref/preprocess_nam.sh.ecf_1h_retro ${cyc} 13 ${PDY}  &" >> poe.e
echo "$USHhref/preprocess_nam.sh.ecf_1h_retro ${cyc} 14 ${PDY}  &" >> poe.e
echo "$USHhref/preprocess_nam.sh.ecf_1h_retro ${cyc} 15 ${PDY}  &" >> poe.e
echo "$USHhref/preprocess_nam.sh.ecf_1h_retro ${cyc} 16 ${PDY}  &" >> poe.e
echo "$USHhref/preprocess_nam.sh.ecf_1h_retro ${cyc} 17 ${PDY}  &" >> poe.e
echo "$USHhref/preprocess_nam.sh.ecf_1h_retro ${cyc} 18 ${PDY}  &" >> poe.e
echo "$USHhref/preprocess_nam.sh.ecf_1h_retro ${cyc} 19 ${PDY}  &" >> poe.e
echo "$USHhref/preprocess_nam.sh.ecf_1h_retro ${cyc} 20 ${PDY}  &" >> poe.e
echo "$USHhref/preprocess_nam.sh.ecf_1h_retro ${cyc} 21 ${PDY}  &" >> poe.e
echo "$USHhref/preprocess_nam.sh.ecf_1h_retro ${cyc} 22 ${PDY}  &" >> poe.e
echo "$USHhref/preprocess_nam.sh.ecf_1h_retro ${cyc} 23 ${PDY}  &" >> poe.e
echo "wait" >> poe.e

echo "#!/bin/sh  "                             >  poe.f
echo "$USHhref/preprocess_nam.sh.ecf_1h_retro ${cyc} 24 ${PDY}  &" >> poe.f
echo "$USHhref/preprocess_nam.sh.ecf_1h_retro ${cyc} 25 ${PDY}  &" >> poe.f
echo "$USHhref/preprocess_nam.sh.ecf_1h_retro ${cyc} 26 ${PDY}  &" >> poe.f
echo "$USHhref/preprocess_nam.sh.ecf_1h_retro ${cyc} 27 ${PDY}  &" >> poe.f
echo "$USHhref/preprocess_nam.sh.ecf_1h_retro ${cyc} 28 ${PDY}  &" >> poe.f
echo "$USHhref/preprocess_nam.sh.ecf_1h_retro ${cyc} 29 ${PDY}  &" >> poe.f
echo "$USHhref/preprocess_nam.sh.ecf_1h_retro ${cyc} 30 ${PDY}  &" >> poe.f
echo "$USHhref/preprocess_nam.sh.ecf_1h_retro ${cyc} 31 ${PDY}  &" >> poe.f
echo "$USHhref/preprocess_nam.sh.ecf_1h_retro ${cyc} 32 ${PDY}  &" >> poe.f
echo "$USHhref/preprocess_nam.sh.ecf_1h_retro ${cyc} 33 ${PDY}  &" >> poe.f
echo "$USHhref/preprocess_nam.sh.ecf_1h_retro ${cyc} 34 ${PDY}  &" >> poe.f
echo "$USHhref/preprocess_nam.sh.ecf_1h_retro ${cyc} 35 ${PDY}  &" >> poe.f
echo "wait" >> poe.f

echo "#!/bin/sh  "                             >  poe.g
echo "$USHhref/preprocess_nam.sh.ecf_1h_retro ${cyc} 36 ${PDY}  &" >> poe.g
echo "$USHhref/preprocess_nam.sh.ecf_1h_retro ${cyc} 37 ${PDY}  &" >> poe.g
echo "$USHhref/preprocess_nam.sh.ecf_1h_retro ${cyc} 38 ${PDY}  &" >> poe.g
echo "$USHhref/preprocess_nam.sh.ecf_1h_retro ${cyc} 39 ${PDY}  &" >> poe.g
echo "$USHhref/preprocess_nam.sh.ecf_1h_retro ${cyc} 40 ${PDY}  &" >> poe.g
echo "$USHhref/preprocess_nam.sh.ecf_1h_retro ${cyc} 41 ${PDY}  &" >> poe.g
echo "$USHhref/preprocess_nam.sh.ecf_1h_retro ${cyc} 42 ${PDY}  &" >> poe.g
echo "$USHhref/preprocess_nam.sh.ecf_1h_retro ${cyc} 43 ${PDY}  &" >> poe.g
echo "$USHhref/preprocess_nam.sh.ecf_1h_retro ${cyc} 44 ${PDY}  &" >> poe.g
echo "$USHhref/preprocess_nam.sh.ecf_1h_retro ${cyc} 45 ${PDY}  &" >> poe.g
echo "$USHhref/preprocess_nam.sh.ecf_1h_retro ${cyc} 46 ${PDY}  &" >> poe.g
echo "$USHhref/preprocess_nam.sh.ecf_1h_retro ${cyc} 47 ${PDY}  &" >> poe.g
echo "$USHhref/preprocess_nam.sh.ecf_1h_retro ${cyc} 48 ${PDY}  &" >> poe.g
echo "wait" >> poe.g


chmod 775 ${DATA}/poe.a  ${DATA}/poe.b ${DATA}/poe.c
chmod 775 ${DATA}/poe.d  ${DATA}/poe.e ${DATA}/poe.f  ${DATA}/poe.g


aprun -n 1 -N 1 -d 13 ${DATA}/poe.a   &
aprun -n 1 -N 1 -d 12 ${DATA}/poe.b   &
aprun -n 1 -N 1 -d 12 ${DATA}/poe.c   &
aprun -n 1 -N 1 -d 12 ${DATA}/poe.d   &
aprun -n 1 -N 1 -d 12 ${DATA}/poe.e   &
aprun -n 1 -N 1 -d 12 ${DATA}/poe.f   &
aprun -n 1 -N 1 -d 13 ${DATA}/poe.g   &
wait
export err=$?; err_chk

$USHhref/preprocess_hrrrak.sh.ecf_3hapcp_retro ${cyc} ${PDY}

msg"JOB $job HAS COMPLETED NORMALLY."
postmsg "$jlogfile" "$msg"
date

fi

cd $DATAROOT
if [ $KEEPDATA = NO ]; then rm -rf $DATA; fi

date
