#!/bin/ksh 

########################################
# Preliminary data setup step
########################################
set -xa

export PS4='$SECONDS + ' 
date

######################################################
# Default to NCO production run environment
#######################################################
export RUN_ENVIR=${RUN_ENVIR:-prod}

###############################
# Specify NET and RUN name
###############################
export NET=${NET:-href}
export RUN=${RUN:-href}

###############################################################
# This block can be modified for different Production test
# environment. This is used for operational testings
###############################################################
if [ "$RUN_ENVIR" = prod -a $envir != prod ]; then
  export jlogfile=/com/logs/${envir}/jlogfile
  export SENDDBN=NO
fi

########################################################### 
# obtain unique process id (pid) and make temp directories
###########################################################
export pid=$$
export DATA=${DATA:-/tmpnwprd2/href_qpfeasfrac_${cyc}_${envir}}
mkdir -p $DATA
cd $DATA 

rm ${DATA}/*

####################################
# File To Log Msgs
####################################
export jlogfile=${jlogfile:-/com/logs/jlogfiles/jlogfile.$job.$pid}

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"

export cycle=${cycle:-t${cyc}z}

##################################################
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
##################################################
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-NO}

export HOMEhref=${HOMEhref:-/nw${envir}/href.${model_ver}}
export EXEChref=${EXEChref:-$HOMEhref/exec}
export FIXhref=${FIXhref:-$HOMEhref/fix}
export PARMhref=${PARMhref:-$HOMEhref/parm}
export USHhref=${USHhref:-$HOMEhref/ush}

###################################
# Set up the UTILITIES
###################################
export utilscript=/nwprod/util/ush
export utilexec=/nwprod/util/exec

# Run setup to initialize working directory and utility scripts
sh $utilscript/setup.sh

# Run setpdy and initialize PDY variables
sh $utilscript/setpdy.sh
. PDY

export COMIN=${COMIN:-/com/${NET}/${envir}/href.${PDY}}
export COMOUT=${COMOUT:-/com/${NET}/${envir}/href.${PDY}}

mkdir -p -m 775 $COMOUT/ensprod
 
########################################################
# Execute the script.

export COMINhrrr=/gpfs/hps2/ptmp/Matthew.Pyle/com/hrrr/prod
export COMINhiresw=/gpfs/hps/nco/ops/com/hiresw/prod
export COMINnam=/com2/nam/prod
export COMINnam=/gpfs/hps2/ptmp/Matthew.Pyle/com/nam/prod
export COMINpcpanl=/com2/pcpanl/prod

if [ -e poe.all ] 
then
rm poe.all
fi

hrs="06 09 12 15 18 21 24 27 30 33 36"
for fhr in $hrs
do
echo "mkdir qpf_${fhr}_6; cd qpf_${fhr}_6 ; python ${HOMEhref}/scripts/make_easfracqpf_combo_bin.py ${fhr} 6 >& qpf_combo_${dom}_${cyc}_6h_${fhr}.log" >> poe.all
echo "mkdir snow_${fhr}_6; cd snow_${fhr}_6; python ${HOMEhref}/scripts/make_easfracsnow_combo_bin.py ${fhr} 6 >& snow_combo_${dom}_${cyc}_6h_${fhr}.log" >> poe.all
done

hrs="03 06 09 12 15 18 21 24 27 30 33 36"
for fhr in $hrs
do
echo "mkdir qpf_${fhr}_3; cd qpf_${fhr}_3 ; python ${HOMEhref}/scripts/make_easfracqpf_combo_bin.py ${fhr} 3  >& qpf_combo_${dom}_${cyc}_3h_${fhr}.log" >> poe.all
echo "mkdir snow_${fhr}_3; cd snow_${fhr}_3; python ${HOMEhref}/scripts/make_easfracsnow_combo_bin.py ${fhr} 3 >& snow_combo_${dom}_${cyc}_3h_${fhr}.log" >> poe.all
done

hrs="01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36"
for fhr in $hrs
do
echo "mkdir qpf_${fhr}_1; cd qpf_${fhr}_1 ; python ${HOMEhref}/scripts/make_easfracqpf_combo_bin.py ${fhr} 1 >& qpf_combo_${dom}_${cyc}_1h_${fhr}.log" >> poe.all
echo "mkdir snow_${fhr}_1; cd snow_${fhr}_1; python ${HOMEhref}/scripts/make_easfracsnow_combo_bin.py ${fhr} 1 >&  snow_combo_${dom}_${cyc}_1h_${fhr}.log" >> poe.all
done

hrs="12 15 18 21 24 27 30 33 36"
for fhr in $hrs
do
echo "mkdir qpf_${fhr}_12; cd qpf_${fhr}_12 ; python ${HOMEhref}/scripts/make_easfracqpf_combo_bin.py ${fhr} 12 >&  qpf_combo_${dom}_${cyc}_12h_${fhr}.log" >> poe.all
done

hrs="24 30 36"
for fhr in $hrs
do
echo "mkdir qpf_${fhr}_24; cd qpf_${fhr}_24 ; python ${HOMEhref}/scripts/make_easfracqpf_combo_bin.py ${fhr} 24 >&  qpf_combo_${dom}_${cyc}_24h_${fhr}.log" >> poe.all
done



export MP_CMDFILE=poe.all
export MP_PGMMODEL=mpmd
export MP_EUILIB=us
export MP_LABELIO=YES
export MP_INFOLEVEL=3

echo to running of mpirun.lsf
mpirun.lsf cfp poe.all

export err=$?; err_chk


if [ $err -eq 0 ]
then

fhr=01

while [ $fhr -le 36 ]
do

if [ ! -e $DATA/href.t${cyc}z.${dom}.pqpf01_easfrac.f${fhr}.grib2 ]
then
print missing $DATA/href.t${cyc}z.${dom}.pqpf01_easfrac.f${fhr}.grib2
fi

cat $DATA/href.t${cyc}z.${dom}.pqpf01_easfrac.f${fhr}.grib2 > $DATA/href.t${cyc}z.${dom}.eas.f${fhr}.grib2
cat $DATA/href.t${cyc}z.${dom}.snow01_easfrac.f${fhr}.grib2 >> $DATA/href.t${cyc}z.${dom}.eas.f${fhr}.grib2

if [ $((fhr%3)) -eq 0 ]
then
cat $DATA/href.t${cyc}z.${dom}.pqpf03_easfrac.f${fhr}.grib2 >> $DATA/href.t${cyc}z.${dom}.eas.f${fhr}.grib2
cat $DATA/href.t${cyc}z.${dom}.snow03_easfrac.f${fhr}.grib2 >> $DATA/href.t${cyc}z.${dom}.eas.f${fhr}.grib2
fi

if [ $((fhr%3)) -eq 0 -a $fhr -ge 6 ]
then
cat $DATA/href.t${cyc}z.${dom}.pqpf06_easfrac.f${fhr}.grib2 >> $DATA/href.t${cyc}z.${dom}.eas.f${fhr}.grib2
cat $DATA/href.t${cyc}z.${dom}.snow06_easfrac.f${fhr}.grib2 >> $DATA/href.t${cyc}z.${dom}.eas.f${fhr}.grib2
fi

if [ $((fhr%3)) -eq 0 -a $fhr -ge 12 ]
then
cat $DATA/href.t${cyc}z.${dom}.pqpf12_easfrac.f${fhr}.grib2 >> $DATA/href.t${cyc}z.${dom}.eas.f${fhr}.grib2
fi

if [ $fhr -eq 24 -o $fhr -eq 30 -o $fhr -eq 36 ]
then
cat $DATA/href.t${cyc}z.${dom}.pqpf24_easfrac.f${fhr}.grib2 >> $DATA/href.t${cyc}z.${dom}.eas.f${fhr}.grib2
fi

if [ $SENDCOM == 'YES' ]
then
cp $DATA/href.t${cyc}z.${dom}.eas.f${fhr}.grib2 ${COMOUT}/ensprod/
fi

let fhr=fhr+1

if [ $fhr -lt 10 ]
then
fhr=0${fhr}
fi

done

fi


echo past running of mpirun.lsf

########################################################

# msg="JOB $job HREF_QPFCLIMO HAS COMPLETED NORMALLY."
# postmsg "$jlogfile" "$msg"
