#!/bin/sh

#############################################################
# HREF RUNALL 
# 02/02/2015 Binbin Zhou, create for run all scripts 
#############################################################

########################################
# Preliminary data setup step
########################################

set -xa
export PS4='$SECONDS + ' 
date

###################################
# Specify NET and RUN Name and model
####################################
export NET=${NET:-hiresw}
export RUN=${RUN:-href}

export IOBUF_PARAMS='*:size=8M:count=8'

###############################################################
# This block can be modified for different Production test
# environment. This is used for operational testings
###############################################################

## PDY not included here as pull data from PDYm1 as well

export COMINhiresw=${COMINhiresw:-${COMROOT}/${NET}/${envir}/hiresw}
export COMINnam=${COMINnam:-${COMROOTp2}/nam/prod/nam}
export HOMEhref=${HOMEhref:-$NWROOT/href.${href_ver}} 
export EXEChref=${EXEChref:-$HOMEhref/exec}
export PARMhref=${PARMhref:-$HOMEhref/parm}
export USHhref=${USHhref:-$HOMEhref/ush}
export FIXhref=${FIXhref:-$HOMEhref/fix}
export SCRIPTShref=${SCRIPTShref:-$HOMEhref/scripts}

###########################################################
# obtain unique process id (pid) and make temp directories
###########################################################

export pid=$$
export DATA=${DATA:-${DATAROOT}/href_ensprodpreproc_${NEST}_${cyc}_${envir}.${pid}}
mkdir -p $DATA
rm -rf $DATA/*
cd $DATA

####################################
# File To Log Msgs
####################################
export jlogfile=${jlogfile:-$COMROOT/logs/jlogfile}

####################################
# Determine Job Output Name on System
####################################
export pgmout="OUTPUT.$$"

export cycle=${cycle:-t${cyc}z}

##################################################
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
##################################################

export SENDCOM=${SENDCOM:-YES}
export SENDECF=${SENDECF:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDDBN_NTC=${SENDDBN_NTC:-NO}

###################################
# Set up the UTILITIES
###################################

msg="JOB $job HAS BEGUN"
postmsg "$jlogfile" "$msg"

#
# Run setpdy and initialize PDY variables
#

setpdy.sh
. PDY

##############################################
# Define running directory and COM directories
##############################################

if [ "$RUN_ENVIR" != nco ] ; then
  export COMOUT=${MYCOMROOT}/${NET}/${envir}/${RUN}.${PDY}_expv3
else
  export COMOUT=${COMOUT:-${COMROOT}/${NET}/${envir}/${RUN}.${PDY}}
fi

if [ ! -d $COMOUT ] ; then 
 mkdir -p $COMOUT/ensprod
 mkdir -p $COMOUT/verf_g2g
fi

#######################################################
# Pass information which is needed to run the Script
#######################################################

# export VERBOSE=YES

###################################################
# Execute the Script exhref_ensprod.sh.ecf

rm -rf poe.*


if [ $NEST = "conus" ]
then

if [ $cyc = "00" ]
then

echo "#!/bin/sh  "                             >  poe.aaa
echo "$USHhref/preprocess_fv3.sh.ecf_1h ${cyc} 00 &" >> poe.aaa
echo "$USHhref/preprocess_fv3.sh.ecf_1h ${cyc} 01 &" >> poe.aaa
echo "$USHhref/preprocess_fv3.sh.ecf_1h ${cyc} 02 &" >> poe.aaa
echo "$USHhref/preprocess_fv3.sh.ecf_1h ${cyc} 03 &" >> poe.aaa
echo "$USHhref/preprocess_fv3.sh.ecf_1h ${cyc} 04 &" >> poe.aaa
echo "$USHhref/preprocess_fv3.sh.ecf_1h ${cyc} 05 &" >> poe.aaa
echo "$USHhref/preprocess_fv3.sh.ecf_1h ${cyc} 06 &" >> poe.aaa
echo "wait" >> poe.aaa

echo "#!/bin/sh  "                             >  poe.bbb
echo "$USHhref/preprocess_fv3.sh.ecf_1h ${cyc} 07 &" >> poe.bbb
echo "$USHhref/preprocess_fv3.sh.ecf_1h ${cyc} 08 &" >> poe.bbb
echo "$USHhref/preprocess_fv3.sh.ecf_1h ${cyc} 09 &" >> poe.bbb
echo "$USHhref/preprocess_fv3.sh.ecf_1h ${cyc} 10 &" >> poe.bbb
echo "$USHhref/preprocess_fv3.sh.ecf_1h ${cyc} 11 &" >> poe.bbb
echo "$USHhref/preprocess_fv3.sh.ecf_1h ${cyc} 12 &" >> poe.bbb
echo "wait" >> poe.bbb

echo "#!/bin/sh  "                             >  poe.ccc
echo "$USHhref/preprocess_fv3.sh.ecf_1h ${cyc} 13 &" >> poe.ccc
echo "$USHhref/preprocess_fv3.sh.ecf_1h ${cyc} 14 &" >> poe.ccc
echo "$USHhref/preprocess_fv3.sh.ecf_1h ${cyc} 15 &" >> poe.ccc
echo "$USHhref/preprocess_fv3.sh.ecf_1h ${cyc} 16 &" >> poe.ccc
echo "$USHhref/preprocess_fv3.sh.ecf_1h ${cyc} 17 &" >> poe.ccc
echo "$USHhref/preprocess_fv3.sh.ecf_1h ${cyc} 18 &" >> poe.ccc
echo "wait" >> poe.ccc

echo "#!/bin/sh  "                             >  poe.ddd
echo "$USHhref/preprocess_fv3.sh.ecf_1h ${cyc} 19 &" >> poe.ddd
echo "$USHhref/preprocess_fv3.sh.ecf_1h ${cyc} 20 &" >> poe.ddd
echo "$USHhref/preprocess_fv3.sh.ecf_1h ${cyc} 21 &" >> poe.ddd
echo "$USHhref/preprocess_fv3.sh.ecf_1h ${cyc} 22 &" >> poe.ddd
echo "$USHhref/preprocess_fv3.sh.ecf_1h ${cyc} 23 &" >> poe.ddd
echo "$USHhref/preprocess_fv3.sh.ecf_1h ${cyc} 24 &" >> poe.ddd
echo "wait" >> poe.ddd

echo "#!/bin/sh  "                             >  poe.eee
echo "$USHhref/preprocess_fv3.sh.ecf_1h ${cyc} 25 &" >> poe.eee
echo "$USHhref/preprocess_fv3.sh.ecf_1h ${cyc} 26 &" >> poe.eee
echo "$USHhref/preprocess_fv3.sh.ecf_1h ${cyc} 27 &" >> poe.eee
echo "$USHhref/preprocess_fv3.sh.ecf_1h ${cyc} 28 &" >> poe.eee
echo "$USHhref/preprocess_fv3.sh.ecf_1h ${cyc} 29 &" >> poe.eee
echo "$USHhref/preprocess_fv3.sh.ecf_1h ${cyc} 30 &" >> poe.eee
echo "wait" >> poe.eee

echo "#!/bin/sh  "                             >  poe.fff
echo "$USHhref/preprocess_fv3.sh.ecf_1h ${cyc} 31 &" >> poe.fff
echo "$USHhref/preprocess_fv3.sh.ecf_1h ${cyc} 32 &" >> poe.fff
echo "$USHhref/preprocess_fv3.sh.ecf_1h ${cyc} 33 &" >> poe.fff
echo "$USHhref/preprocess_fv3.sh.ecf_1h ${cyc} 34 &" >> poe.fff
echo "$USHhref/preprocess_fv3.sh.ecf_1h ${cyc} 35 &" >> poe.fff
echo "$USHhref/preprocess_fv3.sh.ecf_1h ${cyc} 36 &" >> poe.fff
echo "wait" >> poe.fff

chmod 775 ${DATA}/poe.aaa  ${DATA}/poe.bbb ${DATA}/poe.ccc
chmod 775 ${DATA}/poe.ddd  ${DATA}/poe.eee ${DATA}/poe.fff

aprun -n 1 -N 1 -d 7 ${DATA}/poe.aaa &
aprun -n 1 -N 1 -d 6 ${DATA}/poe.bbb &
aprun -n 1 -N 1 -d 6 ${DATA}/poe.ccc &
aprun -n 1 -N 1 -d 6 ${DATA}/poe.ddd &
aprun -n 1 -N 1 -d 6 ${DATA}/poe.eee &
aprun -n 1 -N 1 -d 6 ${DATA}/poe.fff &
wait

$USHhref/preprocess_fv3_3hapcp.sh.ecf ${cyc}

fi

echo "#!/bin/sh  "                             >  poe.a
echo "$USHhref/preprocess_hrrr.sh.ecf_1h ${cyc} 00 &" >> poe.a
echo "$USHhref/preprocess_hrrr.sh.ecf_1h ${cyc} 01 &" >> poe.a
echo "$USHhref/preprocess_hrrr.sh.ecf_1h ${cyc} 02 &" >> poe.a
echo "$USHhref/preprocess_hrrr.sh.ecf_1h ${cyc} 03 &" >> poe.a
echo "$USHhref/preprocess_hrrr.sh.ecf_1h ${cyc} 04 &" >> poe.a
echo "$USHhref/preprocess_hrrr.sh.ecf_1h ${cyc} 05 &" >> poe.a
echo "$USHhref/preprocess_hrrr.sh.ecf_1h ${cyc} 06 &" >> poe.a
echo "wait" >> poe.a

echo "#!/bin/sh  "                             >  poe.b
echo "$USHhref/preprocess_hrrr.sh.ecf_1h ${cyc} 07 &" >> poe.b
echo "$USHhref/preprocess_hrrr.sh.ecf_1h ${cyc} 08 &" >> poe.b
echo "$USHhref/preprocess_hrrr.sh.ecf_1h ${cyc} 09 &" >> poe.b
echo "$USHhref/preprocess_hrrr.sh.ecf_1h ${cyc} 10 &" >> poe.b
echo "$USHhref/preprocess_hrrr.sh.ecf_1h ${cyc} 11 &" >> poe.b
echo "$USHhref/preprocess_hrrr.sh.ecf_1h ${cyc} 12 &" >> poe.b
echo "wait" >> poe.b

echo "#!/bin/sh  "                             >  poe.c
echo "$USHhref/preprocess_hrrr.sh.ecf_1h ${cyc} 13 &" >> poe.c
echo "$USHhref/preprocess_hrrr.sh.ecf_1h ${cyc} 14 &" >> poe.c
echo "$USHhref/preprocess_hrrr.sh.ecf_1h ${cyc} 15 &" >> poe.c
echo "$USHhref/preprocess_hrrr.sh.ecf_1h ${cyc} 16 &" >> poe.c
echo "$USHhref/preprocess_hrrr.sh.ecf_1h ${cyc} 17 &" >> poe.c
echo "$USHhref/preprocess_hrrr.sh.ecf_1h ${cyc} 18 &" >> poe.c
echo "wait" >> poe.c

echo "#!/bin/sh  "                             >  poe.d
echo "$USHhref/preprocess_hrrr.sh.ecf_1h ${cyc} 19 &" >> poe.d
echo "$USHhref/preprocess_hrrr.sh.ecf_1h ${cyc} 20 &" >> poe.d
echo "$USHhref/preprocess_hrrr.sh.ecf_1h ${cyc} 21 &" >> poe.d
echo "$USHhref/preprocess_hrrr.sh.ecf_1h ${cyc} 22 &" >> poe.d
echo "$USHhref/preprocess_hrrr.sh.ecf_1h ${cyc} 23 &" >> poe.d
echo "$USHhref/preprocess_hrrr.sh.ecf_1h ${cyc} 24 &" >> poe.d
echo "wait" >> poe.d

echo "#!/bin/sh  "                             >  poe.e
echo "$USHhref/preprocess_hrrr.sh.ecf_1h ${cyc} 25 &" >> poe.e
echo "$USHhref/preprocess_hrrr.sh.ecf_1h ${cyc} 26 &" >> poe.e
echo "$USHhref/preprocess_hrrr.sh.ecf_1h ${cyc} 27 &" >> poe.e
echo "$USHhref/preprocess_hrrr.sh.ecf_1h ${cyc} 28 &" >> poe.e
echo "$USHhref/preprocess_hrrr.sh.ecf_1h ${cyc} 29 &" >> poe.e
echo "$USHhref/preprocess_hrrr.sh.ecf_1h ${cyc} 30 &" >> poe.e
echo "wait" >> poe.e

echo "#!/bin/sh  "                             >  poe.f
echo "$USHhref/preprocess_hrrr.sh.ecf_1h ${cyc} 31 &" >> poe.f
echo "$USHhref/preprocess_hrrr.sh.ecf_1h ${cyc} 32 &" >> poe.f
echo "$USHhref/preprocess_hrrr.sh.ecf_1h ${cyc} 33 &" >> poe.f
echo "$USHhref/preprocess_hrrr.sh.ecf_1h ${cyc} 34 &" >> poe.f
echo "$USHhref/preprocess_hrrr.sh.ecf_1h ${cyc} 35 &" >> poe.f
echo "$USHhref/preprocess_hrrr.sh.ecf_1h ${cyc} 36 &" >> poe.f
echo "wait" >> poe.f

chmod 775 ${DATA}/poe.a  ${DATA}/poe.b ${DATA}/poe.c
chmod 775 ${DATA}/poe.d  ${DATA}/poe.e ${DATA}/poe.f

aprun -n 1 -N 1 -d 7 ${DATA}/poe.a &
aprun -n 1 -N 1 -d 6 ${DATA}/poe.b &
aprun -n 1 -N 1 -d 6 ${DATA}/poe.c &
aprun -n 1 -N 1 -d 6 ${DATA}/poe.d &
aprun -n 1 -N 1 -d 6 ${DATA}/poe.e &
aprun -n 1 -N 1 -d 6 ${DATA}/poe.f &
wait

$USHhref/preprocess_hrrr_3hapcp.sh.ecf ${cyc}


echo "#!/bin/sh  "                             >  poe.aa
echo "$USHhref/preprocess_nam.sh.ecf_1h ${cyc} 00 &" >> poe.aa
echo "$USHhref/preprocess_nam.sh.ecf_1h ${cyc} 01 &" >> poe.aa
echo "$USHhref/preprocess_nam.sh.ecf_1h ${cyc} 02 &" >> poe.aa
echo "$USHhref/preprocess_nam.sh.ecf_1h ${cyc} 03 &" >> poe.aa
echo "$USHhref/preprocess_nam.sh.ecf_1h ${cyc} 04 &" >> poe.aa
echo "$USHhref/preprocess_nam.sh.ecf_1h ${cyc} 05 &" >> poe.aa
echo "$USHhref/preprocess_nam.sh.ecf_1h ${cyc} 06 &" >> poe.aa
echo "wait" >> poe.aa

echo "#!/bin/sh  "                             >  poe.bb
echo "$USHhref/preprocess_nam.sh.ecf_1h ${cyc} 07 &" >> poe.bb
echo "$USHhref/preprocess_nam.sh.ecf_1h ${cyc} 08 &" >> poe.bb
echo "$USHhref/preprocess_nam.sh.ecf_1h ${cyc} 09 &" >> poe.bb
echo "$USHhref/preprocess_nam.sh.ecf_1h ${cyc} 10 &" >> poe.bb
echo "$USHhref/preprocess_nam.sh.ecf_1h ${cyc} 11 &" >> poe.bb
echo "$USHhref/preprocess_nam.sh.ecf_1h ${cyc} 12 &" >> poe.bb
echo "$USHhref/preprocess_nam.sh.ecf_1h ${cyc} 13 &" >> poe.bb
echo "wait" >> poe.bb

echo "#!/bin/sh  "                             >  poe.cc
echo "$USHhref/preprocess_nam.sh.ecf_1h ${cyc} 14 &" >> poe.cc
echo "$USHhref/preprocess_nam.sh.ecf_1h ${cyc} 15 &" >> poe.cc
echo "$USHhref/preprocess_nam.sh.ecf_1h ${cyc} 16 &" >> poe.cc
echo "$USHhref/preprocess_nam.sh.ecf_1h ${cyc} 17 &" >> poe.cc
echo "$USHhref/preprocess_nam.sh.ecf_1h ${cyc} 18 &" >> poe.cc
echo "$USHhref/preprocess_nam.sh.ecf_1h ${cyc} 19 &" >> poe.cc
echo "$USHhref/preprocess_nam.sh.ecf_1h ${cyc} 20 &" >> poe.cc
echo "wait" >> poe.cc

echo "#!/bin/sh  "                             >  poe.dd
echo "$USHhref/preprocess_nam.sh.ecf_1h ${cyc} 21 &" >> poe.dd
echo "$USHhref/preprocess_nam.sh.ecf_1h ${cyc} 22 &" >> poe.dd
echo "$USHhref/preprocess_nam.sh.ecf_1h ${cyc} 23 &" >> poe.dd
echo "$USHhref/preprocess_nam.sh.ecf_1h ${cyc} 24 &" >> poe.dd
echo "$USHhref/preprocess_nam.sh.ecf_1h ${cyc} 25 &" >> poe.dd
echo "$USHhref/preprocess_nam.sh.ecf_1h ${cyc} 26 &" >> poe.dd
echo "$USHhref/preprocess_nam.sh.ecf_1h ${cyc} 27 &" >> poe.dd
echo "wait" >> poe.dd

echo "#!/bin/sh  "                             >  poe.ee
echo "$USHhref/preprocess_nam.sh.ecf_1h ${cyc} 28 &" >> poe.ee
echo "$USHhref/preprocess_nam.sh.ecf_1h ${cyc} 29 &" >> poe.ee
echo "$USHhref/preprocess_nam.sh.ecf_1h ${cyc} 30 &" >> poe.ee
echo "$USHhref/preprocess_nam.sh.ecf_1h ${cyc} 31 &" >> poe.ee
echo "$USHhref/preprocess_nam.sh.ecf_1h ${cyc} 32 &" >> poe.ee
echo "$USHhref/preprocess_nam.sh.ecf_1h ${cyc} 33 &" >> poe.ee
echo "$USHhref/preprocess_nam.sh.ecf_1h ${cyc} 34 &" >> poe.ee
echo "wait" >> poe.ee

echo "#!/bin/sh  "                             >  poe.ff
echo "$USHhref/preprocess_nam.sh.ecf_1h ${cyc} 35 &" >> poe.ff
echo "$USHhref/preprocess_nam.sh.ecf_1h ${cyc} 36 &" >> poe.ff
echo "$USHhref/preprocess_nam.sh.ecf_1h ${cyc} 37 &" >> poe.ff
echo "$USHhref/preprocess_nam.sh.ecf_1h ${cyc} 38 &" >> poe.ff
echo "$USHhref/preprocess_nam.sh.ecf_1h ${cyc} 39 &" >> poe.ff
echo "$USHhref/preprocess_nam.sh.ecf_1h ${cyc} 40 &" >> poe.ff
echo "$USHhref/preprocess_nam.sh.ecf_1h ${cyc} 41 &" >> poe.ff
echo "wait" >> poe.ff

echo "#!/bin/sh  "                             >  poe.gg
echo "$USHhref/preprocess_nam.sh.ecf_1h ${cyc} 42 &" >> poe.gg
echo "$USHhref/preprocess_nam.sh.ecf_1h ${cyc} 43 &" >> poe.gg
echo "$USHhref/preprocess_nam.sh.ecf_1h ${cyc} 44 &" >> poe.gg
echo "$USHhref/preprocess_nam.sh.ecf_1h ${cyc} 45 &" >> poe.gg
echo "$USHhref/preprocess_nam.sh.ecf_1h ${cyc} 46 &" >> poe.gg
echo "$USHhref/preprocess_nam.sh.ecf_1h ${cyc} 47 &" >> poe.gg
echo "$USHhref/preprocess_nam.sh.ecf_1h ${cyc} 48 &" >> poe.gg
echo "wait" >> poe.gg


chmod 775 ${DATA}/poe.aa  ${DATA}/poe.bb ${DATA}/poe.cc
chmod 775 ${DATA}/poe.dd  ${DATA}/poe.ee ${DATA}/poe.ff ${DATA}/poe.gg


aprun -n 1 -N 1 -d 7 ${DATA}/poe.aa &
aprun -n 1 -N 1 -d 7 ${DATA}/poe.bb &
aprun -n 1 -N 1 -d 7 ${DATA}/poe.cc &
aprun -n 1 -N 1 -d 7 ${DATA}/poe.dd &
aprun -n 1 -N 1 -d 7 ${DATA}/poe.ee &
aprun -n 1 -N 1 -d 7 ${DATA}/poe.ff &
aprun -n 1 -N 1 -d 7 ${DATA}/poe.gg &
wait


msg"JOB $job HAS COMPLETED NORMALLY."
postmsg "$jlogfile" "$msg"
date

fi

if [ $NEST = "ak" ]
then

echo "IN ak NEST part"

echo "#!/bin/sh  "                             >  poe.a
echo "$USHhref/preprocess_hrrrak.sh.ecf_1h ${cyc} 00 &" >> poe.a
echo "$USHhref/preprocess_hrrrak.sh.ecf_1h ${cyc} 01 &" >> poe.a
echo "$USHhref/preprocess_hrrrak.sh.ecf_1h ${cyc} 02 &" >> poe.a
echo "$USHhref/preprocess_hrrrak.sh.ecf_1h ${cyc} 03 &" >> poe.a
echo "$USHhref/preprocess_hrrrak.sh.ecf_1h ${cyc} 04 &" >> poe.a
echo "$USHhref/preprocess_hrrrak.sh.ecf_1h ${cyc} 05 &" >> poe.a
echo "$USHhref/preprocess_hrrrak.sh.ecf_1h ${cyc} 06 &" >> poe.a
echo "wait" >> poe.a

echo "#!/bin/sh  "                             >  poe.b
echo "$USHhref/preprocess_hrrrak.sh.ecf_1h ${cyc} 07 &" >> poe.b
echo "$USHhref/preprocess_hrrrak.sh.ecf_1h ${cyc} 08 &" >> poe.b
echo "$USHhref/preprocess_hrrrak.sh.ecf_1h ${cyc} 09 &" >> poe.b
echo "$USHhref/preprocess_hrrrak.sh.ecf_1h ${cyc} 10 &" >> poe.b
echo "$USHhref/preprocess_hrrrak.sh.ecf_1h ${cyc} 11 &" >> poe.b
echo "$USHhref/preprocess_hrrrak.sh.ecf_1h ${cyc} 12 &" >> poe.b
echo "wait" >> poe.b

echo "#!/bin/sh  "                             >  poe.c
echo "$USHhref/preprocess_hrrrak.sh.ecf_1h ${cyc} 13 &" >> poe.c
echo "$USHhref/preprocess_hrrrak.sh.ecf_1h ${cyc} 14 &" >> poe.c
echo "$USHhref/preprocess_hrrrak.sh.ecf_1h ${cyc} 15 &" >> poe.c
echo "$USHhref/preprocess_hrrrak.sh.ecf_1h ${cyc} 16 &" >> poe.c
echo "$USHhref/preprocess_hrrrak.sh.ecf_1h ${cyc} 17 &" >> poe.c
echo "$USHhref/preprocess_hrrrak.sh.ecf_1h ${cyc} 18 &" >> poe.c
echo "wait" >> poe.c

echo "#!/bin/sh  "                             >  poe.d
echo "$USHhref/preprocess_hrrrak.sh.ecf_1h ${cyc} 19 &" >> poe.d
echo "$USHhref/preprocess_hrrrak.sh.ecf_1h ${cyc} 20 &" >> poe.d
echo "$USHhref/preprocess_hrrrak.sh.ecf_1h ${cyc} 21 &" >> poe.d
echo "$USHhref/preprocess_hrrrak.sh.ecf_1h ${cyc} 22 &" >> poe.d
echo "$USHhref/preprocess_hrrrak.sh.ecf_1h ${cyc} 23 &" >> poe.d
echo "$USHhref/preprocess_hrrrak.sh.ecf_1h ${cyc} 24 &" >> poe.d
echo "wait" >> poe.d

echo "#!/bin/sh  "                             >  poe.e
echo "$USHhref/preprocess_hrrrak.sh.ecf_1h ${cyc} 25 &" >> poe.e
echo "$USHhref/preprocess_hrrrak.sh.ecf_1h ${cyc} 26 &" >> poe.e
echo "$USHhref/preprocess_hrrrak.sh.ecf_1h ${cyc} 27 &" >> poe.e
echo "$USHhref/preprocess_hrrrak.sh.ecf_1h ${cyc} 28 &" >> poe.e
echo "$USHhref/preprocess_hrrrak.sh.ecf_1h ${cyc} 29 &" >> poe.e
echo "$USHhref/preprocess_hrrrak.sh.ecf_1h ${cyc} 30 &" >> poe.e
echo "wait" >> poe.e

echo "#!/bin/sh  "                             >  poe.f
echo "$USHhref/preprocess_hrrrak.sh.ecf_1h ${cyc} 31 &" >> poe.f
echo "$USHhref/preprocess_hrrrak.sh.ecf_1h ${cyc} 32 &" >> poe.f
echo "$USHhref/preprocess_hrrrak.sh.ecf_1h ${cyc} 33 &" >> poe.f
echo "$USHhref/preprocess_hrrrak.sh.ecf_1h ${cyc} 34 &" >> poe.f
echo "$USHhref/preprocess_hrrrak.sh.ecf_1h ${cyc} 35 &" >> poe.f
echo "$USHhref/preprocess_hrrrak.sh.ecf_1h ${cyc} 36 &" >> poe.f
echo "wait" >> poe.f


chmod 775 ${DATA}/poe.a  ${DATA}/poe.b ${DATA}/poe.c
chmod 775 ${DATA}/poe.d  ${DATA}/poe.e ${DATA}/poe.f

aprun -n 1 -N 1 -d 7 ${DATA}/poe.a &
aprun -n 1 -N 1 -d 6 ${DATA}/poe.b &
aprun -n 1 -N 1 -d 6 ${DATA}/poe.c &
aprun -n 1 -N 1 -d 6 ${DATA}/poe.d &
aprun -n 1 -N 1 -d 6 ${DATA}/poe.e &
aprun -n 1 -N 1 -d 6 ${DATA}/poe.f &
wait

$USHhref/preprocess_hrrrak_3hapcp.sh.ecf ${cyc}
export err=$?; err_chk


fi


cd $DATAROOT
if [ $KEEPDATA = NO ]; then rm -rf $DATA; fi

date
