#!/bin/sh

#############################################################
# HREF RUNALL 
# 02/02/2015 Binbin Zhou, create for run all scripts 
#############################################################

########################################
# Preliminary data setup step
########################################

set -xa
export PS4='$SECONDS + ' 
date

###########################################################
# obtain unique process id (pid) and make temp directories
###########################################################
export DATA=${DATA:-${DATAROOT:?}/${jobid:?}}
mkdir -p $DATA
rm -rf $DATA/*
cd $DATA

msg="JOB $job HAS BEGUN"
postmsg "$jlogfile" "$msg"

#
# Run setpdy and initialize PDY variables
#

export cycle=${cycle:-t${cyc}z}
setpdy.sh
. PDY

##################################################
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
##################################################

export SENDCOM=${SENDCOM:-YES}
export SENDECF=${SENDECF:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDDBN_NTC=${SENDDBN_NTC:-NO}

export HOMEhref=${HOMEhref:-$NWROOT/href.${href_ver}} 
export EXEChref=${EXEChref:-$HOMEhref/exec}
export PARMhref=${PARMhref:-$HOMEhref/parm}
export USHhref=${USHhref:-$HOMEhref/ush}
export FIXhref=${FIXhref:-$HOMEhref/fix}
export SCRIPTShref=${SCRIPTShref:-$HOMEhref/scripts}

###################################
# Specify NET and RUN Name and model
####################################
export NET=${NET:-hiresw}
export RUN=${RUN:-href}

export IOBUF_PARAMS='*:size=8M:count=8'

##############################################
# Define running directory and COM directories
##############################################

## PDY not included here as pull data from PDYm1 as well

export COMINhiresw=${COMINhiresw:-$(compath.py hiresw/prod/hiresw)}
#export COMINnam=${COMINnam:-$(compath.py nam/prod/nam)}
#export COMINhrrr=${COMINhrrr:-$(compath.py hrrr/prod/hrrr)}
#export COMINfv3=${COMINfv3:-/gpfs/hps3/ptmp/Matthew.Pyle/com/fv3/prod/fv3}

export GESIN=${GESIN:-${GESROOT}/${envir}}
export COMINnam=${COMINnam:-$GESIN/href}
export COMINhrrr=${COMINhrrr:-$GESIN/href}
export COMINfv3=${COMINfv3:-$GESIN/href}

if [ "$RUN_ENVIR" != nco ] ; then
  export COMOUT=${MYCOMROOT}/${NET}/${envir}/${RUN}.${PDY}_expv3
  export COMINffg=${MYCOMROOT}/${NET}/${envir}/${RUN}.${PDY}_expv3
  export COMINffgm1=${MYCOMROOT}/${NET}/${envir}/${RUN}.${PDYm1}_expv3
else
  export COMOUT=${COMOUT:-${COMROOT}/${NET}/${envir}/${RUN}.${PDY}}
  export COMINffg=${COMINffg:-${COMROOT}/${NET}/${envir}/${RUN}.${PDY}}
  export COMINffgm1=${COMINffg:-${COMROOT}/${NET}/${envir}/${RUN}.${PDYm1}}
fi

if [ ! -d $COMOUT/ensprod ] ; then 
 mkdir -p $COMOUT/ensprod
 mkdir -p $COMOUT/verf_g2g
 mkdir -p $COMOUT/wmo
fi

export pgmout="OUTPUT.$$"

#######################################################
# Pass information which is needed to run the Script
#######################################################

# export VERBOSE=YES

###################################################
# Execute the Script exhref_ensprod.sh.ecf

rm -rf poe.*


hrlist="01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 \
34 35 36"

for hr in $hrlist
do
echo "$SCRIPTShref/exhref_ensprod_link.sh.ecf $hr" >> poe.link.all
echo "$SCRIPTShref/exhref_ensprod.sh.ecf $hr" >> poe.ensprod.all
done


chmod 775  poe.link.all
chmod 775 poe.ensprod.all

# NTASK 36 for both here
aprun -j 1 -n $NTASK -N $PTILE -d 1 cfp poe.link.all
export err=$?; err_chk
aprun -j 1 -n $NTASK -N $PTILE -d 1 cfp poe.ensprod.all
export err=$?; err_chk

msg"JOB $job HAS COMPLETED NORMALLY."
postmsg "$jlogfile" "$msg"
date

cd $DATAROOT
if [ $KEEPDATA = NO ]; then rm -rf $DATA; fi

date
