#!/bin/sh

set -xa
# #### 08/25/1999 ###################
# SET SHELL PROCESSING VARIABLES
# ###################################
export PS4='$SECONDS + ' 
date

###############################
# Specify NET and RUN name
###############################
export NET=${NET:-hiresw}
export RUN=${RUN:-href} 
  
###########################################################
# obtain unique process id (pid) and make temp directories
###########################################################
export pid=$$
export DATA=${DATA:-${DATAROOT}/href_awips_${cyc}_${envir}.${pid}}
mkdir $DATA
cd $DATA 

####################################
# File To Log Msgs
####################################
export jlogfile=${jlogfile:-/com/logs/jlogfiles/jlogfile.${jobid}}

####################################
# Determine Job Output Name on System
####################################
export pgmout=OUTPUT.$$

export cycle=${cycle:-t${cyc}z}

##################################################
# SENDECF  - Flag Events on ecFLOW
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
##################################################
export SENDCOM=${SENDCOM:-YES}
export SENDECF=${SENDECF:-YES}
export SENDDBN=${SENDDBN:-YES}

export HOMEhref=${HOMEhref:-$NWROOT/href.${href_ver}}
export USHhref=${USHhref:-$HOMEhref/ush}
export PARMutil=${PARMutil:-$HOMEhref/util/parm}

# Run setpdy and initialize PDY variables
setpdy.sh
. PDY

if [ "$RUN_ENVIR" != nco ] ; then
 export PCOM=${PCOM:-${MYCOMROOT}/${NET}/${envir}/awip}
 export COMIN=${COMIN:-${MYCOMROOT}/${NET}/${envir}/href.${PDY}/ensprod}
else
 export PCOM=${PCOM:-${PCOMROOT:?}/${RUN}}
 export COMIN=${COMIN:-${COMROOT}/${NET}/${envir}/${RUN}.${PDY}/ensprod}
fi

if [ ! -f $PCOM ] ; then
  mkdir -p -m 775 $PCOM
fi

#################################################################
# Execute the script
$HOMEhref/scripts/exhref_awips.sh.ecf
#################################################################

cd ${DATAROOT}
if [ $KEEPDATA = NO ]; then rm -rf $DATA; fi
date
