#!/bin/sh

#############################################################
# HREF RUNALL 
# 02/02/2015 Binbin Zhou, create for run all scripts 
#############################################################

########################################
# Preliminary data setup step
########################################

set -xa
export PS4='$SECONDS + ' 
date

###################################
# Specify NET and RUN Name and model
####################################
export NET=${NET:-hiresw}
export RUN=${RUN:-href}

export IOBUF_PARAMS='*:size=8M:count=8:verbose'

###############################################################
# This block can be modified for different Production test
# environment. This is used for operational testings
###############################################################

## PDY not included here as pull data from PDYm1 as well

export COMINhiresw=${COMINhiresw:-${COMROOT}/${NET}/prod/hiresw}
export COMINnam=${COMINnam:-${COMROOTp1}/nam/prod/nam}

export HOMEhref=${HOMEhref:-$NWROOT/href.${href_ver}} 
export EXEChref=${EXEChref:-$HOMEhref/exec}
export PARMhref=${PARMhref:-$HOMEhref/parm}
export USHhref=${USHhref:-$HOMEhref/ush}
export FIXhref=${FIXhref:-$HOMEhref/fix}
export SCRIPTShref=${SCRIPTShref:-$HOMEhref/scripts}

###########################################################
# obtain unique process id (pid) and make temp directories
###########################################################

export pid=$$
export DATA=${DATA:-${DATAROOT}/href_ensprod_${cyc}_${envir}.${pid}}
mkdir -p $DATA
rm -rf $DATA/*
cd $DATA

####################################
# File To Log Msgs
####################################
export jlogfile=${jlogfile:-$COMROOT/logs/jlogfile}

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"

export cycle=${cycle:-t${cyc}z}

##################################################
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
##################################################

export SENDCOM=${SENDCOM:-YES}
export SENDECF=${SENDECF:-YES}
export SENDDBN=${SENDDBN:-YES}

###################################
# Set up the UTILITIES
###################################
module load grib_util

msg="JOB $job HAS BEGUN"
postmsg "$jlogfile" "$msg"

#
# Run setpdy and initialize PDY variables
#

setpdy.sh
. PDY

##############################################
# Define running directory and COM directories
##############################################

if [ "$RUN_ENVIR" != nco ] ; then
  export COMOUT=${MYCOMROOT}/${NET}/${envir}/${RUN}.${PDY}
else
  export COMOUT=${COMOUT:-${COMROOT}/${NET}/${envir}/${RUN}.${PDY}}
fi

if [ ! -d $COMOUT ] ; then 
 mkdir -p $COMOUT
fi

env

#######################################################
# Pass information which is needed to run the Script
#######################################################

# export VERBOSE=YES

###################################################
# Execute the Script exhref_ensprod.sh.ecf

rm -rf poescript

echo "#!/bin/sh  "                             >  poe.a
echo "$SCRIPTShref/exhref_ensprod.sh.ecf 03 &" >> poe.a
echo "$SCRIPTShref/exhref_ensprod.sh.ecf 06 &" >> poe.a
echo "wait"                                    >> poe.a

echo "#!/bin/sh  "                             >  poe.b
echo "$SCRIPTShref/exhref_ensprod.sh.ecf 09 &" >> poe.b
echo "$SCRIPTShref/exhref_ensprod.sh.ecf 12 &" >> poe.b
echo "wait"                                    >> poe.b

echo "#!/bin/sh  "                             >  poe.c
echo "$SCRIPTShref/exhref_ensprod.sh.ecf 15 &" >> poe.c
echo "$SCRIPTShref/exhref_ensprod.sh.ecf 18 &" >> poe.c
echo "wait"                                    >> poe.c

echo "#!/bin/sh  "                             >  poe.d
echo "$SCRIPTShref/exhref_ensprod.sh.ecf 21 &" >> poe.d
echo "$SCRIPTShref/exhref_ensprod.sh.ecf 24 &" >> poe.d
echo "wait"                                    >> poe.d

echo "#!/bin/sh  "                             >  poe.e
echo "$SCRIPTShref/exhref_ensprod.sh.ecf 27 &" >> poe.e
echo "$SCRIPTShref/exhref_ensprod.sh.ecf 30 &" >> poe.e
echo "wait"                                    >> poe.e

echo "#!/bin/sh  "                             >  poe.f
echo "$SCRIPTShref/exhref_ensprod.sh.ecf 33 &" >> poe.f
echo "$SCRIPTShref/exhref_ensprod.sh.ecf 36 &" >> poe.f
echo "wait"                                    >> poe.f

chmod 775 ${DATA}/poe.a ${DATA}/poe.b ${DATA}/poe.c
chmod 775 ${DATA}/poe.d ${DATA}/poe.e ${DATA}/poe.f

# aprun -n 1 -N 1 -d 4 ${DATA}/poe.a : -n 1 -N 1 -d 4 ${DATA}/poe.b : -n 1 -N 1 -d 4 ${DATA}/poe.c

aprun -n 1 -N 1 -d 2 ${DATA}/poe.a & 
aprun -n 1 -N 1 -d 2 ${DATA}/poe.b &
aprun -n 1 -N 1 -d 2 ${DATA}/poe.c &
aprun -n 1 -N 1 -d 2 ${DATA}/poe.d &
aprun -n 1 -N 1 -d 2 ${DATA}/poe.e &
aprun -n 1 -N 1 -d 2 ${DATA}/poe.f &

wait
export err=$?; err_chk

msg"JOB $job HAS COMPLETED NORMALLY."
postmsg "$jlogfile" "$msg"
date

cd $DATAROOT
#if [ $KEEPDATA = NO ]; then rm -rf $DATA; fi
date
