#!/bin/sh

########################################
# RUNS HIRESW POST JOB
########################################
set -xa
export PS4='$SECONDS + ' 
date

######################################################
# Default to NCO production run environment
#######################################################
export RUN_ENVIR=${RUN_ENVIR:-prod}

###############################
# Specify NET and RUN name
###############################
export NET=${NET:-hiresw}
export RUN=${RUN:-${NEST}${MODEL}}

###############################################################
# This block can be modified for different Production test
# environment. This is used for operational testings
###############################################################
if [ "$RUN_ENVIR" = prod -a $envir != prod ]; then
  export jlogfile=/com/logs/${envir}/jlogfile
  export SENDDBN=NO
  export SENDDBN_GB2=NO
fi

############################################################# 
# obtain unique process id (pid) and make temp directories
############################################################# 
export pid=$$
export DATA=${DATA:-$DATAROOT/hiresw.post_${NEST}_${MODEL}_${cyc}_${envir}}
export INPUT_DATA=${INPUT_DATA:-$DATAROOT/hiresw.forecast_${NEST}_${MODEL}_${cyc}_${envir}}
mkdir -p $DATA
cd $DATA
# rm $DATA/*

##################################################
# SAVEGES  - Copy Files From TMPDIR to $GESdir
# SENDECF  - Flag Events on ecFlow
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
##################################################
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDDBN_GB2=${SENDDBN_GB2:-NO}
export SENDECF=${SENDECF:-YES}

####################################
# File To Log Msgs
####################################
export jlogfile=${jlogfile:-/com/logs/jlogfiles/jlogfile.${job}.${pid}}

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"

export cycle=${cycle:-t${cyc}z}

#nestMODEL=`echo ${NEST}${MODEL} | tr '[a-z]' '[A-Z]'`
#export nestMODEL
#export DBN_NEST=${nestMODEL}
export DBN_NEST=`echo ${NEST}_${MODEL} | tr '[a-z]' '[A-Z]'`
                                                                                                             
export HOMEhiresw=${HOMEhiresw:-/nw${envir}/hiresw.${model_ver}}
export EXEChiresw=${EXEChiresw:-$HOMEhiresw/exec}
export FIXhiresw=${FIXhiresw:-$HOMEhiresw/fix}
export PARMhiresw=${PARMhiresw:-$HOMEhiresw/parm}
export USHhiresw=${USHhiresw:-$HOMEhiresw/ush}
export PARMhrrr=${PARMhrrr:-/nwtest/hrrr.v1.0.0/parm}

###################################
# Set up the UTILITIES
###################################
export USHutil=${USHutil:-/nwprod/util/ush}
export EXECutil=${EXECutil:-/nwprod/util/exec}

module load prod_util

sh $USHutil/setup.sh


export NDATE=${NDATE:-$EXECutil/ndate}

# Run setpdy and initialize PDY variables
# sh $USHutil/setpdy.sh
# . PDY

export PDY=${DATE}

export COMIN=${COMIN:-/com/${NET}/${envir}/hiresw.${PDY}}

################################################
# Copy Forecast files from com
################################################
. $COMIN/hiresw.t${cyc}z.${NEST}${MODEL}.envir.sh
export tmmark=tm00

########################################################
# Run the ex-script
#
# ${HOMEhiresw}/scripts/exhiresw_post.sh.ecf
${HOMEhiresw}/scripts/exhiresw_postg2.sh.ecf_retro
#
########################################################

postmsg "$jlogfile" "$job FOR NEST=${NEST}${MODEL} IS COMPLETE"

cd $DATAROOT
date
