#!/bin/sh

set -xa
# #### 07/30/1999 ###################
# SET SHELL PROCESSING VARIABLES
# ###################################
export PS4='$SECONDS + ' 
date

######################################################
# Default to NCO production run environment
#######################################################
export RUN_ENVIR=${RUN_ENVIR:-prod}

###############################
# Specify NET and RUN name
###############################
export NET=${NET:-hiresw}
export RUN=${RUN:-${NEST}${MODEL}}

###############################################################
# This block can be modified for different Production test
# environment. This is used for operational testings
###############################################################
if [ "$RUN_ENVIR" = prod -a $envir != prod ]; then
  export jlogfile=/com/logs/${envir}/jlogfile
  export SENDDBN=NO
  export pcom=/pcom/${envir}/${NET}
fi

############################################################# 
# obtain unique process id (pid) and make temp directories
############################################################# 
export pid=$$
export DATA=${DATA:-${DATAROOT}/${job}.${pid}}
mkdir $DATA
cd $DATA 

##################################################
# SENDECF  - Flag Events on SMS
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
##################################################
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDECF=${SENDECF:-YES}

export DBN_ALERT_TYPE=${DBN_ALERT_TYPE:-HIRESW_AWIPS}

####################################
# File To Log Msgs
####################################
export jlogfile=${jlogfile:-/com/logs/jlogfiles/jlogfile.${job}.${pid}}

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"

export cycle=${cycle:-t${cyc}z}

#echo ${NEST}${MODEL} > lower
#nestMODEL=`cat lower | tr '[a-z]' '[A-Z]'`
#export nestMODEL
#export DBN_NEST=${nestMODEL}
export DBN_NEST=`echo ${NEST}_${MODEL} | tr '[a-z]' '[A-Z]'`

# these will be used for ensemble mean

export HOMEhiresw=${HOMEhiresw:-/nw${envir}/hiresw.${model_ver}}
export EXEChiresw=${EXEChiresw:-$HOMEhiresw/exec}
export FIXhiresw=${FIXhiresw:-$HOMEhiresw/fix}
export PARMhiresw=${PARMhiresw:-$HOMEhiresw/parm}
export USHhiresw=${USHhiresw:-$HOMEhiresw/ush}
export PARMutil=${PARMutil:-$HOMEhiresw/util/parm}
###################################
# Set up the UTILITIES
###################################
export USHutil=${USHutil:-/nwprod/util/ush}
export EXECutil=${EXECutil:-/nwprod/util/exec}

module load prod_util

# Run setpdy and initialize PDY variables
sh $USHutil/setpdy.sh
. PDY

export COMIN=${COMIN:-/com/${NET}/${envir}/hiresw.${PDY}}
export pcom=${pcom:-/pcom/${NET}}

mkdir -p $COMOUT $pcom
 
env

########################################################
# Run the ex-script
#
$HOMEhiresw/scripts/exhiresw_awips.sh.ecf
#
########################################################

postmsg "$jlogfile" "$job FOR NEST=${NEST}${MODEL} IS COMPLETE"

cd $DATAROOT
rm -rf $DATA

date
