      SUBROUTINE MPI_LAST
C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C                .      .    .
C SUBPROGRAM:    MPI_LAST    SHUTS DOWN THE IO SERVER
C   PRGRMMR: TUCCILLO        ORG: IBM
C
C ABSTRACT:
C     SHUTS DOWN IO SERVER
C   .
C
C PROGRAM HISTORY LOG:
C   00-01-06  TUCCILLO - ORIGINAL
C
C USAGE:    CALL COLLECT(A)
C   INPUT ARGUMENT LIST:
C
C   OUTPUT ARGUMENT LIST:
C
C   OUTPUT FILES:
C     STDOUT  - RUN TIME STANDARD OUT.
C
C   SUBPROGRAMS CALLED:
C       MPI_FINALIZE
C     UTILITIES:
C       NONE
C     LIBRARY:
C       NONE
C
C   ATTRIBUTES:
C     LANGUAGE: FORTRAN
C     MACHINE : IBM RS/6000 SP
C$$$
      include "mpif.h"
!      include "parmeta"
      include "CTLBLK.comm"
      LOGICAL DONE
      DATA DONE / .TRUE. /
      IF ( ME .EQ. 0 ) THEN
         IF ( NUM_SERVERS .GT. 0 ) THEN
            CALL MPI_SEND(DONE,1,MPI_LOGICAL,0,1,MPI_COMM_INTER,IERR)
         END IF
      END IF
      END
