#! /bin/ksh 

# @ job_name=wrf_single
# @ notification=never
# @ output=copygb.out
# @ error=copygb.err
# @ job_type = serial
# @ class=dev
# @ node_usage=shared
# @ wall_clock_limit=00:30:00
# @ queue


cd /gpfstmp/wx20py/wrfpost_nmmtest/

cp /emc2/wx20py/fslwork/tb_1006/test/nmm_real/grid_246_info.txt .

hrs="00 03 06 09 12 15 18 21 24 27 30 33 36 39 42 45 48"
# hrs="36 39 42 45 48"
grid=`cat grid_246_info.txt`

for hr in $hrs
do
/emc2/wx20py/copygb/copygb.x -s"3,-3" -g"$grid" -x WRFPRS${hr}.tm00 WRFWST.f${hr}
echo "DONE $hr"
done
