#!/bin/ksh
#
# @ job_name = run_l150
# @ job_type = parallel
# @ account_no = GFS-T2O
# @ output = out2_l150
# @ error =  err2_l150
# @ node_usage = not_shared
# @ tasks_per_node = 32
# @ node = 1
# @ node_resources = ConsumableMemory(110GB)
# @ task_affinity = core(2)
# @ parallel_threads = 1
# @ bulkxfer = yes
# @ network.MPI=sn_all,not_shared,us
# @ class = 1
# @ group = class1onprod
### @ class = dev
### @ group = dev
# @ wall_clock_limit = 04:00:00
# @ queue
#
set -x
#
#jw  export CDATE=2006033100
#jw export CDATE=2006093000
 export CDATE=2011092300

 export fcst_begin=YES
#export EXPLICIT=.true.
 export ADIAB=.false.
 export IDEA=.true.
 export IAER=0
 export GOCART=0
# reduced_grid default is true
 export REDUCED_GRID=.true.

#
 NST_FCST=0         # valid values are 0 (AM), 1(am,nst) and 2(cpld nstnst)
 if [[ $ADIAB = .true. ]] ; then
     export NUM_FILE=1 ;
    export FILENAME_BASE="'SIG.F'"
    export FILE_IO_FORM="'bin4'"
 else
    export FILENAME_BASE="'SIG.F' 'SFC.F' 'FLX.F'"
    export FILE_IO_FORM="'bin4' 'bin4' 'grib'"
    export NUM_FILE=3
    if [ $NST_FCST -gt 0 ] ; then
      export FILENAME_BASE=${FILENAME_BASE}" 'NST.F'"
      export FILE_IO_FORM=${FILE_IO_FORM}" 'bin4'"
      NUM_FILE=`expr $NUM_FILE + 1`
      export NUM_FILE
    fi
    echo "NUM_FILE=$NUM_FILE,NST_FCST=$NST_FCST,FILENAME_BASE=$FILENAME_BASE"
 fi

#
#export NEMSIO_IN=.true.
#export NEMSIO_OUT=.true.
 export NEMSIO_IN=.false.
 export NEMSIO_OUT=.false.
 export SIGIO_OUT=.true.
 export SFCIO_OUT=.true.
 export ldiag3d=.false.

#
 export MACHINE_ID=${MACHINE_ID:-ccs}
 export SCHEDULER=${SCHEDULER:-loadleveler}
#
 export hybrid=NO
 export GEN_COORD_HYBRID=YES
# -------------------------------------------------------------
# SFCPRESS_ID=0 or 1 for ln(psfc), 2 for psfc
# THERMODYN_ID=3 for enthalphy, 0 or 1 for virtual T, 2 for T
# -------------------------------------------------------------
if [[ $hybrid = YES ]] ; then
 export IDVC=2
 export SFCPRESS_ID=1
 export THERMODYN_ID=1
fi
if [[ $GEN_COORD_HYBRID = YES ]] ; then
 export IDVC=3
 export SFCPRESS_ID=2
 export THERMODYN_ID=3
 export IDVM=32
 export NDSLFV=.false.
#export NDSLFV=.true.
#export DELTIM=900
#export DELTIM=1200
#export DELTIM=1800
#export DELTIM=400
#export DELTIM=600
fi
#
# SPECTRAL_LOOP       2 for old option, 1 is for one loop.default is 2
 export SPECTRAL_LOOP=2
#***************************************************************
#                    N2 ,    H2O,     O3,        CLW,    O,      O2
#export CPIlist=" 1039.645, 1846.0, 820.2391,    0.0, 1299.185, 918.0969"
#export RIlist="  296.8034, 461.50, 173.2247,    0.0,  519.674, 259.837 "
#***************************************************************
#                   Dry ,    H2O,     O3,        CLW,    O,      O2
#jw export CPIlist=" 1004.6,   1846.0, 820.2391,    0.0"
#jw export RIlist="  286.05,   461.50, 173.2247,    0.0"
 export RIlist="  296.8034, 461.50, 173.2247,    0.0, 519.674, 259.837"
 export CPIlist=" 1039.645, 1846.0, 820.2391,    0.0, 1299.185, 918.0969"
#***************************************************************
#
#    Set up horizontal and vertical resolution ; default will be T6264
#
# ----- quadratic grid ----
#wave=62   ; im=192  ; jm=94   ; lm=64  ; iop=144 ; jop=73  ; dt=900
#wave=62   ; im=192  ; jm=94   ; lm=150  ; iop=144 ; jop=73  ; dt=900
 wave=62   ; im=192  ; jm=94   ; lm=150 ; iop=144 ; jop=73  ; dt=180
#wave=126  ; im=384  ; jm=190  ; lm=64  ; iop=360 ; jop=181 ; dt=600
#wave=170  ; im=512  ; jm=256  ; lm=64  ; iop=360 ; jop=181 ; dt=450
#wave=190  ; im=576  ; jm=288  ; lm=64  ; iop=360 ; jop=181 ; dt=300
#wave=254  ; im=768  ; jm=384  ; lm=64  ; iop=360 ; jop=181 ; dt=300
#wave=382  ; im=1152 ; jm=576  ; lm=64  ; iop=360 ; jop=181 ; dt=180
#wave=574  ; im=1760 ; jm=880  ; lm=64  ; iop=360 ; jop=181 ; dt=120
#wave=764  ; im=2304 ; jm=1152 ; lm=64  ; iop=360 ; jop=181 ; dt=90
#
# ----- linear grid -------
#wave=92   ; im=192  ; jm=94   ; lm=64  ; iop=144 ; jop=73  ; dt=1200
#wave=188  ; im=384  ; jm=190  ; lm=64  ; iop=360 ; jop=181 ; dt=900
#wave=254  ; im=512  ; jm=256  ; lm=64  ; iop=360 ; jop=181 ; dt=600
#wave=382  ; im=768  ; jm=384  ; lm=64  ; iop=360 ; jop=181 ; dt=600
#wave=574  ; im=1152 ; jm=576  ; lm=64  ; iop=360 ; jop=181 ; dt=400
#wave=878  ; im=1760 ; jm=880  ; lm=64  ; iop=360 ; jop=181 ; dt=300
#wave=1148 ; im=2304 ; jm=1152 ; lm=64  ; iop=360 ; jop=181 ; dt=300
#
#
export NCP=cp
export FTSFS=0.0
export FAISS=0.0
#
#  This script is NOT complete for running multiple ensemble members
#
 export ENS_NUM=1
#
 tasks=32  ; export PE1=32 
#jw export tasks=1   ; export PE1=1
export QUILTING=.false.   
export WRT_GROUP=1
  export WRITE_DOPOST=.false.
  export POST_GRIBVERSION="grib1"
  export GOCART_AER2POST=.false.
  export liope=.false.

#
export MP_STDOUTMODE=ordered
export MP_LABELIO=yes
export MP_SHARED_MEMORY=yes
export MEMORY_AFFINITY=MCM
##export BIND_TASKS=yes
export NTHREADS=1
export XLSMPOPTS="parthds=$NTHREADS:spins=0:yields=0:stack=512000000"
export SPINLOOPTIME=500
export YIELDLOOPTIME=500
export AIXTHREAD_SCOPE=S
export MALLOCMULTIHEAP=true
#
 export FHROT=0
#
#    Set up experiment and directory names
#
 export expt=testwam_clm

#
 export NSCDIR=/global/noscrub
 export TOPDIR=/gpfs/t3/global/save
 export DUMPDIR=/global/shared/dump
#export MP_COREFILE_FORMAT=lite 
 export RUNDIR=${RUNDIR:-/ptmp/$LOGNAME/$expt}
 export SCRIPTS=${SCRIPTS:-$TOPDIR/wx23sm/gsm/scripts}

 export fcst_begin=${fcst_begin:-YES}
 export cold_sfc=${cold_sfc:-NO}
 export hybrid=${hybrid:-NO}
 export ldiag3d=${ldiag3d:-.false.}
#
 export NCP=${NCP:-/u/wx20mi/bin/ncp}
#export nemsioget=${nemsioget:-/climate/save/wx20wa/gfsio/nems/nemsio_get}
 if [ $NEMSIO_IN = .true. ]; then
   if [ $SCHEDULER = 'loadleveler' ]; then
     export nemsioget=${nemsioget:-/climate/save/wx20wa/gfsio/nems/nemsio_get}
   elif [ $SCHEDULER = 'moab' ]; then
     export nemsioget=${nemsioget}
   elif [ $SCHEDULER = 'pbs' ]; then
     export nemsioget=${nemsioget:-/scratch1/portfolios/NCEPDEV/nems/save/Jun.Wang/nems/util/n emsio_get}
   fi
 else
   export nemsioget=${nemsioget:-${EXECGLOBAL}/global_sighdr$XC}
 fi
#
#
#
#    nhourb is the beginig hour.  If nhourb=0, then initial condition
#    needs to be specified. ndays is the Length of #orecast in days
#    begining from nhourb
#
 export ndays=3
#
 export nhours=`expr $ndays \* 24`

#
# For two tracers
  export ntrc=5  ; export varid=21  ; export numcld=1
# export ntrc=5  ; export varid=200  ; export numcld=1
#
#
 export fmax=$nhours
 export fout=1  
 export fzer=6  
 export fcyc=24 
 export fdfi=3 
 export FHRES=24
#
#    Forecast model : horizontal truncation  and vertical levels
#                     ---------------------
#
export wave=${wave:-62}
export lm=${lm:-64}
#
export LSOIL=${lsoil:-4}
export NTRAC=${NTRAC:-$ntrc}
export NTOZ=${NTOZ:-2}
export NTCW=${NTCW:-3}
export NCLD=${NCLD:-1}
export NMTVR=${NMTVR:-14}
#
export nsout=${nsout:-0}
export lsm=${lsm:-1}
#
#   Control for post and time averaging  If "YES" then run
#   -- Defaults to "NO" 
#
 export gfsio_in=.false.
 export gfsio_out=.false.
 export FHOUT_HF=1
#
 export FCSTVARS="adiab=$ADIAB,liope=.F.,"
 export TRACERVARS="RI=$RIlist,CPI=$CPIlist,"
#
 export DYNVARS="nemsio_in=$NEMSIO_IN,nemsio_out=$NEMSIO_OUT,\
                 sigio_out=$SIGIO_OUT,liope=.F."
 export PHYVARS="nemsio_in=$NEMSIO_IN,nemsio_out=$NEMSIO_OUT,\
                 sfcio_out=$SFCIO_OUT,ldiag3d=$ldiag3d,liope=.F."

#
export NGPTC=12
export LEVR=${levr:-0}
#
#     Forecaset script and executable name
#
 export CRTDIR=`pwd`
 export NEMSDIR=$CRTDIR/..
 export FCSTSCRIPT=${NEMSDIR}/job/exglobal_fcst.sh.sms_nems
 export FCSTEXEC=${NEMSDIR}/exe/NEMS.x
#
#
# ***************************************************************
#    Below here no change needed most of the time
#    ____________________________________________
#
mkdir -p $RUNDIR/restart
cd $RUNDIR
#ic
#jw  cp /climate/save/wx20wa/wam/henry/data/ic/nems/*anl* $RUNDIR
#jw  cp /climate/save/wx20wa/wam/Fei_Wu/data/*anl*${CDATE} $RUNDIR
 if [[ ${fcst_begin} = YES ]] ; then
   if [[ $NEMSIO ]] ; then
     cp /climate/noscrub/wx20wa/wam/ic/nemsio/withdp/*anl.${CDATE} $RUNDIR
   else
     cp /global/save/wx23rm/WAM/chgres_test/replay/*anl.${CDATE} $RUNDIR
   fi
 fi
 export COMOUT=$RUNDIR
#
 cp -p ${NEMSDIR}/job/regression_tests/Chem_Registry.rc $RUNDIR
 cp -p ${NEMSDIR}/job/regression_tests/MAPL.rc $RUNDIR

#
 export FIXGLOBAL=/nwprod/fix
 export FIX_RAD=/global/save/wx23hh/00wkgfs/fix/fix_rad
#
 export POSTGPDIR=$TOPDIR/wx23hh/00wkgfs/src/global_postgp.fd
 export POSTGPEXEC=$POSTGPDIR/global_postgp
 export POSTGPSH=/nwprod/ush/global_postgp.sh
#
 export LANDICE_OPT=1
#export CLIMO_FIELDS_OPT=3
 export CLIMO_FIELDS_OPT=2
#
# ------------------------ initial condition ----------------
#
  export JCAP=$wave
  export LEVS=$lm
  export LONB=$im
  export LATB=$jm
  export LONR=$im
  export LATR=$jm
  export LONF=$im
  export LATG=$jm
  export DELTIM=$dt
  export VERBOSE=YES
#
#
  export FHROT=00
  if [[ ${fcst_begin} = YES ]] ; then
    export GRDI=$RUNDIR/gfsanl.$CDATE
    export SIGI=$RUNDIR/siganl.$CDATE
    export SFCI=$RUNDIR/sfcanl.$CDATE
    export nhourb=0
    export FHINI=00

  else
    if [ -f $RUNDIR/grdr1 -a -f $RUNDIR/grdr2 -a -f $RUNDIR/sigr1 -a -f $RUNDIR/sigr2 -a -f $RUNDIR/sfcr ];
    then
      cp $RUNDIR/grdr1 $RUNDIR/restart/grdr1
      cp $RUNDIR/grdr2 $RUNDIR/restart/grdr2
      cp $RUNDIR/sigr1 $RUNDIR/restart/sigr1
      cp $RUNDIR/sigr2 $RUNDIR/restart/sigr2
      cp $RUNDIR/sfcr $RUNDIR/restart/sfcr
      export GRDI=$RUNDIR/grdr1
      export GRDI2=$RUNDIR/grdr2
      export SIGI=$RUNDIR/sigr1
      export SIGI2=$RUNDIR/sigr2
      export SFCI=$RUNDIR/sfcr
      export FHINI=`$nemsioget $GRDI nfhour |grep -i "nfhour"|awk -F"= " '{print $2}'`
      export nhourb=$FHINI
      export FHROT=${FHROT:-$nhourb}

    elif [ -f $RUNDIR/restart/grdr1 -a -f $RUNDIR/restart/grdr2 -a -f $RUNDIR/restart/sigr1 -a -f $RUNDIR/restart/sigr2 -a -f $RUNDIR/restart/sfcr ];
    then
      export GRDI=$RUNDIR/restart/grdr1
      export GRDI2=$RUNDIR/restart/grdr2
      export SIGI=$RUNDIR/restart/sigr1
      export SIGI2=$RUNDIR/restart/sigr2
      export SFCI=$RUNDIR/restart/sfcr
      export FHINI=`$nemsioget $GRDI nfhour |grep -i "nfhour"|awk -F"= " '{print $2}'`
      export nhourb=$FHINI
      export FHROT=${FHROT:-$nhourb}
    else
      export GRDI=$RUNDIR/gfsanl.$CDATE
      export SIGI=$RUNDIR/siganl.$CDATE
      export SFCI=$RUNDIR/sfcanl.$CDATE
      export FHINI=00
      nhourb=$((ndays*24))
    fi
  fi
#
  export SIGO='sigf$(/nwprod/util/exec/ndate $FH $CDATE)'
  export SFCO='sfcf$(/nwprod/util/exec/ndate $FH $CDATE)'
  export FLXO='flxf$(/nwprod/util/exec/ndate $FH $CDATE)'
  export LOGO='logf$(/nwprod/util/exec/ndate $FH $CDATE)'
  export D3DO='d3df$(/nwprod/util/exec/ndate $FH $CDATE)'
#
# ---------------------------------------- fcst ----------------------
#
if [[ $nhourb -lt $nhours ]] ; then

  export FNTSFA=
  export FNACNA=
#
  export FHOUT=$fout
  export FHZER=$fzer
  export FHCYC=$fcyc
  export FHDFI=$fdfi
  export FHLWR=${FHLWR:-3}
  export FHSWR=${FHSWR:-1}
  export FHMAX=$nhours
  export FHRES=${FHRES:-$FHMAX}
  export FHROT=${FHROT:-0}
#
  $FCSTSCRIPT || exit
fi
#
