#! /bin/sh

cyc=$1

cd /u/$USER    # cron does this for us - this is here just to be safe
. /etc/profile

if [ -a .profile ]; then
   . ./.profile
fi

if [ -a .bashrc ]; then
   . ./.bashrc
fi

echo cyc $cyc

module load prod_util
module load grib_util
module load prod_envir

export COMINhiresw=${COMROOT}/hiresw/prod/hiresw
export COMINnam=${COMROOTp1}/nam/prod/nam

vers=`cat ~/href_version`

cd /gpfs/hps/emc/meso/noscrub/Matthew.Pyle/href.${vers}/launch_info/

cat runpoe.sh_in_cray | sed s:_CYC_:${cyc}:g > launch_hrefrunpoe_${cyc}

bsub < launch_hrefrunpoe_${cyc}

# rm launch_hrefrunpoe_${cyc}
