#! /bin/ksh


cyc=${1}
hr_start=${2}
hr_end=${3}
core=${4}
ETADATE=${5}
area=${6}

mproj=lcc
lat1=38
cenlon=-90
lat2=38

echo $cyc 
echo $hr_start
echo $hr_end
echo $core

if [ $area = "N" ]
then
LLAT=#42
LLON=-90
ULAT=7
ULON=12
elif [ $area = "C" ]
then
LLAT=#39
LLON=-90
ULAT=7
ULON=12
elif [ $area = "S" ]
then
LLAT=#36
LLON=-90
ULAT=7
ULON=12
elif [ $area = "E" ]
then
LLAT=#38
LLON=-80
ULAT=7
ULON=12
fi

size1=1000
size2=800

export GEMTBL=/meso/save/Matthew.Pyle/gem_tables_5.11_hiresw

rm  /ptmpd1/Matthew.Pyle/process_4km_east_${ETADATE}_comp_${cyc}/*.grd
mkdir -p /ptmpd1/Matthew.Pyle/process_4km_east_${ETADATE}_comp_${cyc}/${hr_end}

cd /ptmpd1/Matthew.Pyle/process_4km_east_${ETADATE}_comp_${cyc}/${hr_end}

if [ $hr_end -eq 00 ]
then
rm  /ptmpd1/Matthew.Pyle/process_4km_east_${ETADATE}_comp_${cyc}/*.gif
fi

rm /ptmpd1/Matthew.Pyle/process_4km_east_${ETADATE}_comp_${cyc}/${hr_end}/*.grd
rm /ptmpd1/Matthew.Pyle/process_4km_east_${ETADATE}_comp_${cyc}/${hr_end}/*.grb
rm /ptmpd1/Matthew.Pyle/process_4km_east_${ETADATE}_comp_${cyc}/${hr_end}/*.gif

rm /ptmpd1/Matthew.Pyle/process_4km_east_${ETADATE}_comp_${cyc}/${hr_end}/*

ETADATE=${5}
DATE=$ETADATE${cyc}
echo $DATE

cores="arw nmmb"
types="para prod"

for core in $cores
do
for type in $types
do
echo type $type
hr=${hr_start}

if [ $type = "prod" -a ${hr}%3 -ne 0 ]
then
echo NOT A PRODUCTION TIME SO EXIT
let hr=hr+1
echo hr now $hr
fi

while [ $hr -le $hr_end ]
do


if [ $type = "para" ]
then

GRIB_PARA=/meso/noscrub/Matthew.Pyle/com/hiresw/prod/hiresw.${ETADATE}/conus${core}.t${cyc}z.awpregeastf${hr}
GRIBTEST=$GRIB_PARA
GRIBFILE=$GRIB_PARA

coreloc=${core}

else

coreloc=${core}

if [ $core = "nmmb" ]
then
coreloc=nmm
fi



GRIB_PROD=/meso/noscrub/Matthew.Pyle/opshiresw/hiresw.${ETADATE}/east${coreloc}.t${cyc}z.awpreg${hr}.tm00.grib2_sub.grb

GRIBTEST=$GRIB_PROD
GRIBFILE=$GRIB_PROD
fi

rm /ptmpd1/Matthew.Pyle/process_4km_east_${ETADATE}_comp_${cyc}/${hr_end}/*.grd
rm /ptmpd1/Matthew.Pyle/process_4km_east_${ETADATE}_comp_${cyc}/${hr_end}/*.grb
rm /ptmpd1/Matthew.Pyle/process_4km_east_${ETADATE}_comp_${cyc}/${hr_end}/*SPC*

threehrold=`expr $hr - 3`
onehrold=`expr $hr - 1`

typeset Z2 threehrold
typeset Z2 onehrold


wgrib $GRIBTEST | grep APCP |  grep P1=$threehrold | wgrib -i -grib $GRIBTEST -o WRFPCP${hr}.tm00
wgrib $GRIBTEST | grep APCP |  grep P1=$onehrold | wgrib -i -grib $GRIBTEST -o SPCPCP${hr}.tm00

WGRIB=/nwprod/util/exec/wgrib

datestr=`date`
echo START wgribbing $hr at $datestr

echo GRIBFILE $GRIBFILE

wgrib $GRIBFILE  |  \
      grep "REFD" | wgrib -i -grib $GRIBFILE -o wrfcent4km_radar1_${hr}.grb

wgrib $GRIBFILE  |  \
      grep "REFC" | wgrib -i -grib $GRIBFILE -o wrfcent4km_radar2_${hr}.grb

# /usrx/local/grads/bin/wgrib $GRIBFILE  |  \
#       grep "REFZR" | wgrib -i -grib $GRIBFILE -o wrfcent4km_radar3_${hr}.grb

# /usrx/local/grads/bin/wgrib $GRIBFILE  |  \
#       grep "REFZI" | wgrib -i -grib $GRIBFILE -o wrfcent4km_radar4_${hr}.grb

wgrib $GRIBFILE  |  \
      grep "MSLET" | wgrib -i -grib $GRIBFILE -o wrfcent4km_emsl_${hr}.grb

wgrib $GRIBFILE  |  \
      grep "TMP" | grep "2 m above" | wgrib -i -grib $GRIBFILE -o wrfcent4km_t2ms_${hr}.grb

wgrib $GRIBFILE  |  \
      grep "DPT" | grep "2 m above" | wgrib -i -grib $GRIBFILE -o wrfcent4km_dwpc_${hr}.grb

wgrib $GRIBFILE  |  \
      grep "RH" | grep "2 m above" | wgrib -i -grib $GRIBFILE -o wrfcent4km_2mrh_${hr}.grb

wgrib $GRIBFILE  |  \
      grep "UGRD" | grep "10 m above" | wgrib -i -grib $GRIBFILE -o wrfcent4km_ugrd_${hr}.grb

wgrib $GRIBFILE  |  \
      grep "VGRD" | grep "10 m above" | wgrib -i -grib $GRIBFILE -o wrfcent4km_vgrd_${hr}.grb

wgrib $GRIBFILE  |  \
      grep "UPHL" | wgrib -i -grib $GRIBFILE -o wrfcent4km_updhel_${hr}.grb

wgrib $GRIBFILE  |  \
      grep "MAXREF" | wgrib -i -grib $GRIBFILE -o wrfcent4km_235_${hr}.grb
wgrib $GRIBFILE  |  \
      grep "MXUPHL" | wgrib -i -grib $GRIBFILE -o wrfcent4km_236_${hr}.grb
wgrib $GRIBFILE  |  \
      grep "MAXUVV" | wgrib -i -grib $GRIBFILE -o wrfcent4km_237_${hr}.grb
wgrib $GRIBFILE  |  \
      grep "MAXDVV" | wgrib -i -grib $GRIBFILE -o wrfcent4km_238_${hr}.grb
wgrib $GRIBFILE  |  \
      grep "MAXVIG" | wgrib -i -grib $GRIBFILE -o wrfcent4km_239_${hr}.grb
wgrib $GRIBFILE  |  \

wgrib $GRIBFILE | grep MAXUW | wgrib -i -grib $GRIBFILE -o 253.grb
wgrib $GRIBFILE | grep MAXVW | wgrib -i -grib $GRIBFILE -o 254.grb

wgrib $GRIBFILE | grep CAPE | grep 46080 | wgrib -i -grib $GRIBFILE -o cape.grb



cat SPCPCP${hr}.tm00 wrfcent4km_radar1_${hr}.grb wrfcent4km_radar2_${hr}.grb wrfcent4km_radar3_${hr}.grb \
wrfcent4km_radar4_${hr}.grb wrfcent4km_condensate_${hr}.grb wrfcent4km_emsl_${hr}.grb \
 wrfcent4km_t2ms_${hr}.grb wrfcent4km_dwpc_${hr}.grb wrfcent4km_2mrh_${hr}.grb wrfcent4km_ugrd_${hr}.grb wrfcent4km_vgrd_${hr}.grb wrfcent4km_updhel_${hr}.grb > SPCPCP_radar.grb

mv SPCPCP_radar.grb intermed.grb


cat intermed.grb wrfcent4km_23*_${hr}.grb wrfcent4km_240_${hr}.grb wrfcent4km_250_${hr}.grb wrfcent4km_251_${hr}.grb  wrfcent4km_245_${hr}.grb wrfcent4km_gust_${hr}.grb 253.grb 254.grb cape.grb wrfcent4km_206_${hr}.grb wrfcent4km_213_${hr}.grb tcolr_${hr}.grb tcols_${hr}.grb > SPCPCP_radar.grb

rm wrf*.grb 2*.grb cape.grb


datestr=`date`
echo DONE wgribbing $hr at $datestr

nagrib << endgrib
 GBFILE   = SPCPCP_radar.grb
 INDXFL   =
 GDOUTF   = today_1hprecip.grd
 PROJ     =
 GRDAREA  =
 KXKY     =
 MAXGRD   = 4999
 CPYFIL   = GDS
 GAREA    = dset
 OUTPUT   = T
 GBTBLS   =
 GBDIAG   =
 PDSEXT   = NO

r

ex

endgrib

rm wrfcent4km_radar1_${hr}.grb wrfcent4km_radar2_${hr}.grb

datestr=`date`
echo DONE nagribbing $hr at $datestr

gdplot << endplot

 GDFILE = today_1hprecip.grd
 GDATTIM  = f${hr}
 GLEVEL   = 0
 GVCORD   = none
 PANEL    = 0/4//1
 SKIP     = /12
 SCALE    = 0
 GFUNC    = p01i
 CTYPE    = f
 CONTUR   = 3
 CINT     = 2
 LINE     = 2/-12/1/1
 FINT     = 0.01;5;10;15;20;25;30;35;50;75;100;125;150;175
 FINT     = 0.01;.05;.1;.15;.2;.3;.5;.75;1;1.5;2
 FLINE    = 0;23;22;21;20;19;10;17;16;15;14;29;28;24;25
 HILO     =
 HLSYM    =
 CLRBAR   = 32/V/LL/.005;.02/.9;.013|.82/2/.82/111/SW
 CLRBAR   = 32/H/LL/.005;.02/.8;.01|.82/2/.82/111/SW
 CLRBAR   = 32/H/LL/.07;.02/.85;.006|.82/2/.82/111/SW
 CLRBAR   = 32/H/LL/.07;.035/.85;.007|.82/2/.82/111/SW
 GVECT    =
 REFVEC   =
 TITLE    = 32/0/ ${type} ${coreloc} ^
 TEXT     = 1.9/23/2.0/HW
 CLEAR    = y
 GAREA    = dset
 garea    = $LLAT;$LLON;$ULAT;$ULON 
 IJSKIP   = 0
 PROJ     = $mproj/$lat1;$cenlon;$lat2
 MAP      = 32/12/1
 LATLON   = 0
 DEVICE   = gif|${type}_${coreloc}_1h_f${hr}.gif|$size1;$size2|C
 STNPLT   =

r

cle=n
ctype=c
gfun=emsl
cint=2
line=4/-12/1/0
gvect=obs@10%hght
WIND     = hi32/.25/.25/122/.35
REFVEC   = 20.;.01;.01;1.0

r


GFUN    = REFD
ctype=f
gvcord=hght
glev=1000
fint=5;10;15;20;25;30;35;40;45;50;55;60;65
gvect=
fline=0;25;24;4;21;22;23;5;18;17;15;14;28;29
gfun=REFD
DEVICE = gif|${type}_${coreloc}_refd_1000m_f${hr}.gif|$size1;$size2|C
r


gfun=UPHL
scale=0
gvcord=hght
glev=5000:2000
fint=2;4;8;12;20;30;40;50;75;100;125;150
fline=0;21-27;2;14-18
DEVICE = gif|${type}_${coreloc}_uphl_f${hr}.gif|$size1;$size2|C
r

glev=2
gvcord=hght
gfun=tmpc
fint=-3;0;3;6;9;12;15;18;21;24;27;30;33;36;39
fint=-16;-12;-8;-4;0;4;8;12;16;20;24;28;32;36;40
fint=-3;0;3;6;9;12;15;18;21;24;27;30;33;36;39
fint=        -9;-6;-3;0;3;6;9;12;15;18;21;24;27;30;33
fint=-16;-12;-9;-6;-3;0;3;6;9;12;15;18;21;24;28
fint=-12;-9;-6;-3;0;3;6;9;12;16;20;24;28;32;36
fint=-3;0;3;6;9;12;15;18;21;24;27;30;33;36;39
fint=-9;-6;-3;0;3;6;9;12;15;18;21;24;27;30;33
fint=-20;-16;-12;-9;-6;-3;0;3;6;9;12;16;20;24;28
fint=-3;0;3;6;9;12;15;18;21;24;27;30;33;36;39
fint=-9;-6;-3;0;3;6;9;12;15;18;21;24;27;30;33
fint=-20;-16;-12;-9;-6;-3;0;3;6;9;12;16;20;24;28
fint=-18;-15;-12;-9;-6;-3;0;3;6;9;12;15;18;21;24;27;30
fint=-15;-12;-9;-6;-3;0;3;6;9;12;15;18;21;24;27;30;33
fint=-6;-3;0;3;6;9;12;15;18;21;24;27;30;33;36;39;42
fint=-12;-9;-6;-3;0;3;6;9;12;15;18;21;24;27;30;33;36
fint=-18;-15;-12;-9;-6;-3;0;3;6;9;12;15;18;21;24;27;30
fint=-18;-15;-12;-9;-6;-3;0;3;6;9;12;15;18;21;24;28;32
fint=-6;-3;0;3;6;9;12;15;18;21;24;27;30;33;36;39;42
fline=30;29;28;27;26;25;0;21;22;23;12;13;14;15;16;17
fline=30;29;28;27;26;25;0;21;22;23;17;16;15;14;12;13
fline=30;29;28;27;26;25;0;21;22;23;19;18;17;16;15;14;13;32
DEVICE=gif|${type}_${coreloc}_t2ms_f${hr}.gif|$size1;$size2|C
r

GFUN    = MXUPDR01
glev=400:1000
gvcord=pres
cle=y
ctype=f
gvect=
fint=0.5;1;1.5;2;3;4;5;6;7;8;9;10;12
fint=2;4;6;8;10;12;14;16;18;20;24;28
fline=0;25;24;4;21;22;23;5;18;17;15;14;28;29
DEVICE = gif|${type}_${coreloc}_mxupdr_f${hr}.gif|$size1;$size2|C
r

GFUN    = abs(MXDNDR01)
fline=0;25;24;4;21;22;23;5;18;17;15;14;28;29
fint=2;4;6;8;10;12;14;16;18;20;22;24
fint=0.5;1;1.5;2;3;4;5;6;7;8;9;10;12
DEVICE = gif|${type}_${coreloc}_mxdndr_f${hr}.gif|$size1;$size2|C
r

gfun=CAPE
glev=180:0
gvcord=PDLY
fint=500;750;1000;1250;1500;1750;2000;2500;3000;3500;4000;4500;5000
fline=0;25;24;4;21;22;23;5;18;17;15;14;28;29
DEVICE = gif|${type}_${coreloc}_mucape_f${hr}.gif|$size1;$size2|C
r

gvcord=hght
glev=10
fint=1;2;3;4;5;6;7;8;10;12;14;16;18;20;25
fint=15;17.5;20.0;22.5;25;27.5;30;32.5;35;40
fline=0;25;24;4;21;22;23;5;18;17;15;14;28;29
fline=0;4;23;3;5;17;14;15;16;29;2
gfun=mag(vecr(mx10u01,mx10v01))
DEVICE = gif|${type}_${coreloc}_mx10w_f${hr}.gif|$size1;$size2|C
r

gvcord=hght
glev=5000:2000
fint=2;4;8;12;20;30;40;50;75;100;125;150
fline=0;21-27;2;14-18
gfun=MXUPHL01
DEVICE = gif|${type}_${coreloc}_mxuphl_f${hr}.gif|$size1;$size2|C
r

gfun=MXDBZ01
glev=1000
gvcord=hght
fint=5;10;15;20;25;30;35;40;45;50;55;60;65
fline=0;25;24;4;21;22;23;5;18;17;15;14;28;29
DEVICE = gif|${type}_${coreloc}_mx1000refd_f${hr}.gif|$size1;$size2|C
r

ex

endplot

gpend

datestr=`date`
echo DONE plotting $hr at $datestr

rm wrfcent4km*${hr}.grb


############################################


if [ ${hr}%3 -eq 0 ]
then

# ls /com/nam/prod/nam.${ETADATE}/nam.t${cyc}z.awip3d${hr}.tm00

nagrib << endgrib
 GBFILE   = WRFPCP${hr}.tm00
 INDXFL   =
 GDOUTF   = today_3hprecip.grd
 PROJ     =
 GRDAREA  =
 KXKY     =
 MAXGRD   = 4999
 CPYFIL   = GDS
 GAREA    = dset
 OUTPUT   = T
 GBTBLS   =
 GBDIAG   =
 PDSEXT   = NO
r

ex

endgrib

gdplot << endplot

 GDFILE = today_3hprecip.grd
 GDATTIM  = f${hr}
 GLEVEL   = 0
 GVCORD   = none
 SKIP     = /8
 SCALE    = 0
 GFUNC    = p03i
 CTYPE    = f
 CONTUR   = 3
 CINT     = 2
 LINE     = 2/-12/1/1
 FINT     = 0.01;5;10;15;20;25;30;35;50;75;100;125;150;175
 FINT     = 0.01;.05;.1;.2;.3;.5;.75;1;1.5;2;2.5;3
 FLINE    = 0;23;22;21;20;19;10;17;16;15;14;29;28;24;25
 CLRBAR   = 32/H/LL/.07;.035/.85;.007|.82/2/.82/111/SW
 HILO     =
 HLSYM    =
 GVECT    =
 WIND     = bm2/.45/.45/122/.5
 REFVEC   =
 CLEAR    = y
 GAREA    = dset
 TITLE    = 32/0/ ${type} ${coreloc} ^
 TEXT     = 1.9/23/2.0/HW
 garea    = $LLAT;$LLON;$ULAT;$ULON
 PROJ     = $mproj/$lat1;$cenlon;$lat2
 LATLON   = 0
 DEVICE   = gif|${type}_${coreloc}_3hprec_f${hr}.gif|$size1;$size2|C
 STNPLT   =

r

ex

endplot

gpend

cp WRFPCP${hr}.tm00  ../

fi

cp *f${hr}.gif  ../

let "hr = hr + 1"

typeset -Z2 hr

echo hr now $hr

done

echo past this loop

done

done

### montage block - move to transfer job

types="3hprec mucape mx1000refd mx10w mxdndr mxupdr mxuphl refd_1000m t2ms uphl"
m1=700
m2=560

exit

let "hr = hr - 1"



for typ in $types
do

if [ ${hr}%3 -eq 0 ]
then

echo where am I
pwd

# time montage prod_arw_${typ}_f${hr}.gif para_arw_${typ}_f${hr}.gif prod_nmm_${typ}_f${hr}.gif para_nmmb_${typ}_f${hr}.gif -geometry ${m1}x${m2}+1+1 combo3h_${typ}_f${hr}.gif
# time montage para_arw_${typ}_f${hr}.gif  para_nmmb_${typ}_f${hr}.gif -geometry ${m1}x${m2}+1+1 combo1h_${typ}_f${hr}.gif
# mv combo1h_${typ}_f${hr}.gif combo3h_${typ}_f${hr}.gif ../

else

echo not here

# time montage para_arw_${typ}_f${hr}.gif  para_nmmb_${typ}_f${hr}.gif -geometry ${m1}x${m2}+1+1 combo1h_${typ}_f${hr}.gif
# mv  combo1h_${typ}_f${hr}.gif ../

fi

done


# /meso/save/Matthew.Pyle/html/4km_stuff/gen_info_ijk.scr_conus ${cyc}

# DIR=/home/www/emc/htdocs/mmb/mpyle/east_${core}_compare/${cyc}_tide

# mkdir -p /meso/noscrub/Matthew.Pyle/com/hiresw/prod/hiresw.${ETADATE}/eastgifs_${cyc}/
# cp *.gif /meso/noscrub/Matthew.Pyle/com/hiresw/prod/hiresw.${ETADATE}/eastgifs_${cyc}/

# fi
