#! /bin/ksh

REGION=${1}
CYC=${2}
DATE=${3}

echo REGION $REGION
echo CYC $CYC
echo DATE $DATE

cat sub_graphics_ncoparaweb.lsf_in | sed s:_REGION_:${REGION}:g | sed s:_CYC_:${CYC}:g  | sed s:_DATE_:${DATE}:g   > \
sub_graphics.lsf

bsub < sub_graphics.lsf

# cat  transfer_graphics_ncoparaweb.lsf_in | sed s:_REGLOC_:${REGION}:g  | sed s:_CYCLOC_:${CYC}:g | sed s:_DATELOC_:${DATE}:g > \
# transfer_graphics.lsf
