#! /bin/ksh

DOM=${1}
CORE=${2}
CYC=${3}


if [ $DOM$CORE == "hinmmb"  ]
then
MODPROCS=72
MODSPAN=24
POSTPROCS=2
POSTSPAN=2
PRDGENPROCS=2
PRDGENSPAN=2
BUFRSPAN=1
NPROCBUFR=1
elif [ $DOM$CORE == "hiarw" ]
then
MODPROCS=67
MODSPAN=23
POSTPROCS=2
POSTSPAN=2
PRDGENPROCS=2
PRDGENSPAN=2
BUFRSPAN=1
NPROCBUFR=1
elif [ $DOM$CORE == "prnmmb"  ]
then
MODPROCS=120
MODSPAN=24
POSTPROCS=2
POSTSPAN=2
PRDGENPROCS=2
PRDGENSPAN=2
BUFRSPAN=1
NPROCBUFR=1
elif [ $DOM$CORE == "prarw" ]
then
MODPROCS=105
MODSPAN=21
POSTPROCS=2
POSTSPAN=2
PRDGENPROCS=2
PRDGENSPAN=2
BUFRSPAN=1
NPROCBUFR=1
elif [ $DOM$CORE == "guamnmmb"  ]
then
MODPROCS=72
MODSPAN=24
POSTPROCS=2
POSTSPAN=2
PRDGENPROCS=2
PRDGENSPAN=2
BUFRSPAN=1
NPROCBUFR=1
elif [ $DOM$CORE == "guamarw" ]
then
MODPROCS=72
MODSPAN=24
POSTPROCS=2
POSTSPAN=2
PRDGENPROCS=2
PRDGENSPAN=2
BUFRSPAN=1
NPROCBUFR=1
elif [ $DOM$CORE == "conusnmmb" ]
then
MODPROCS=696
MODSPAN=24
POSTPROCS=24
POSTSPAN=8
PRDGENPROCS=13
PRDGENSPAN=5
NPROCBUFR=56
BUFRSPAN=14
elif [ $DOM$CORE == "conusarw" ]
then
MODPROCS=888
MODSPAN=24
POSTPROCS=24
POSTSPAN=12
PRDGENPROCS=13
PRDGENSPAN=5
NPROCBUFR=1
BUFRSPAN=1
elif [ $DOM$CORE == "aknmmb" ]
then
MODPROCS=672
MODSPAN=24
POSTPROCS=32
POSTSPAN=8
PRDGENPROCS=5
PRDGENSPAN=5
NPROCBUFR=48
BUFRSPAN=8
elif [ $DOM$CORE == "akarw" ]
then
MODPROCS=864
MODSPAN=24
POSTPROCS=16
POSTSPAN=8
PRDGENPROCS=5
PRDGENSPAN=5
NPROCBUFR=1
BUFRSPAN=1
fi



cat ungrib.lsf_in_phase2 | sed s:_DOM_:${DOM}:g | sed s:_CORE_:${CORE}:g | sed s:_CYC_:${CYC}:g > \
sub_ungrib.lsf_${DOM}_${CORE}_${CYC}

cat metgrid.lsf_in_phase2 | sed s:_DOM_:${DOM}:g | sed s:_CORE_:${CORE}:g | sed s:_CYC_:${CYC}:g > \
sub_metgrid.lsf_${DOM}_${CORE}_${CYC}


if [ $CORE == "nmmb" ]
then

cat sub_nemsinterp_1.lsf_in_phase2 |  sed s:_DOM_:${DOM}:g | sed s:_CORE_:${CORE}:g | \
sed s:_CYC_:${CYC}:g > sub_nemsinterp_1.lsf_${DOM}_${CORE}_${CYC}

cat sub_nemsinterp_2.lsf_in_phase2 |  sed s:_DOM_:${DOM}:g | sed s:_CORE_:${CORE}:g | \
 sed s:_CYC_:${CYC}:g > sub_nemsinterp_2.lsf_${DOM}_${CORE}_${CYC}

cat sub_nemsinterp_3.lsf_in_phase2 |  sed s:_DOM_:${DOM}:g | sed s:_CORE_:${CORE}:g | \
sed s:_CYC_:${CYC}:g > sub_nemsinterp_3.lsf_${DOM}_${CORE}_${CYC}

cat sub_nemsinterp_4.lsf_in_phase2 |  sed s:_DOM_:${DOM}:g | sed s:_CORE_:${CORE}:g | \
sed s:_CYC_:${CYC}:g > sub_nemsinterp_4.lsf_${DOM}_${CORE}_${CYC}

cat prelim.lsf_bigrap_in_phase2 | sed s:_DOM_:${DOM}:g | sed s:_CORE_:${CORE}:g | \
sed s:_CYC_:${CYC}:g > sub_preprap.lsf_${DOM}_${CORE}_${CYC}

else

cat prelimfinal.lsf_in_phase2 | sed s:_DOM_:${DOM}:g | sed s:_CORE_:${CORE}:g | \
sed s:_CYC_:${CYC}:g > sub_prelimfinal.lsf_${DOM}_${CORE}_${CYC}

cat prelim.lsf_bigrap_in_phase2 | sed s:_DOM_:${DOM}:g | sed s:_CORE_:${CORE}:g | \
sed s:_CYC_:${CYC}:g > sub_preprap.lsf_${DOM}_${CORE}_${CYC}

fi

cat sub_model.lsf_in_phase2 | sed s:_DOM_:${DOM}:g | sed s:_CORE_:${CORE}:g | sed s:_CYC_:${CYC}:g | \
  sed s:_SPAN_:${MODSPAN}:g |  sed s:_NPROC_:${MODPROCS}:g  > sub_model.lsf_${DOM}_${CORE}_${CYC}

cat sub_post.lsf_in_phase2 | sed s:_DOM_:${DOM}:g | sed s:_CORE_:${CORE}:g | sed s:_CYC_:${CYC}:g | \
  sed s:_POSTSPAN_:${POSTSPAN}:g |  sed s:_NPROC_:${POSTPROCS}:g  > sub_post.lsf_${DOM}_${CORE}_${CYC}

cat sub_prdgen.lsf_in_phase2 | sed s:_DOM_:${DOM}:g | sed s:_CORE_:${CORE}:g | sed s:_CYC_:${CYC}:g | \
  sed s:_SPAN_:${PRDGENSPAN}:g |  sed s:_NPROC_:${PRDGENPROCS}:g  > sub_prdgen.lsf_${DOM}_${CORE}_${CYC}

cat sub_wrfbufrsnd.lsf_in_phase2 | sed s:_DOM_:${DOM}:g | sed s:_CORE_:${CORE}:g | sed s:_CYC_:${CYC}:g | \
  sed s:_PTILEBUFR_:${BUFRSPAN}:g |  sed s:_NPROCBUFR_:${NPROCBUFR}:g  > sub_wrfbufrsnd.lsf_${DOM}_${CORE}_${CYC}

cat sub_smartinit.lsf_in_phase2 | sed s:_DOM_:${DOM}:g | sed s:_CORE_:${CORE}:g | sed s:_CYC_:${CYC}:g > \
sub_smartinit.lsf_${DOM}_${CORE}_${CYC}

cat sub_smartinitb.lsf_in_phase2 | sed s:_DOM_:${DOM}:g | sed s:_CORE_:${CORE}:g | sed s:_CYC_:${CYC}:g > \
sub_smartinitb.lsf_${DOM}_${CORE}_${CYC}

bsub < sub_ungrib.lsf_${DOM}_${CORE}_${CYC}

if [ $DOM == "conus" ]
then
bsub < sub_preprap.lsf_${DOM}_${CORE}_${CYC}
fi
