#!/bin/sh

########################################
# Runs HIRESW WRFBUFR and SNDP programs
########################################
set -xa
export PS4='$SECONDS + ' 
date

######################################################
# Default to NCO production run environment
#######################################################
export RUN_ENVIR=${RUN_ENVIR:-prod}

###############################
# Specify NET and RUN name
###############################
export NET=${NET:-hiresw}
export RUN=${RUN:-${NEST}${MODEL}}

###############################################################
# This block can be modified for different Production test
# environment. This is used for operational testings
###############################################################
if [ "$RUN_ENVIR" = prod -a $envir != prod ]; then
  export jlogfile=/com/logs/${envir}/jlogfile
  export SENDDBN=NO
fi

# 
# obtain unique process id (pid) and make temp directories
#
export pid=$$
export DATA=${DATA:-/tmpnwprd1/hiresw_${NEST}_${MODEL}_${MEMBER}_${cyc}_${envir}}
#if [ -d $DATA/smartinit ]; then
   #rm -rf $DATA/smartinit/
#fi
mkdir -p $DATA/smartinit
cd $DATA/smartinit

####################################
# File To Log Msgs
####################################
export jlogfile=${jlogfile:-/com/logs/jlogfiles/jlogfile.${job}.${pid}}

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"

export cycle=${cycle:-t${cyc}z}

export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDECF=${SENDECF:-YES}

export HOMEhiresw=${HOMEhiresw:-/nw${envir}/hiresw.${model_ver}}
export EXEChiresw=${EXEChiresw:-$HOMEhiresw/exec}
export FIXhiresw=${FIXhiresw:-$HOMEhiresw/fix}
export PARMhiresw=${PARMhiresw:-$HOMEhiresw/parm}
export USHhiresw=${USHhiresw:-$HOMEhiresw/ush}

###################################
# Set up the UTILITIES
###################################
export utilscript=/nwprod/util/ush
export utilexec=/nwprod/util/exec

hrs="00 03 06 09 12 15 18 21 24 27 30 33 36 39 42 45 48"
for hr in $hrs
do
  if [ -d $DATA/smartinit_${hr} ]; then
    rm -rf $DATA/smartinit_${hr}/
  fi
  mkdir -p $DATA/smartinit_${hr}
  cd $DATA/smartinit_${hr}

  # Run setup to initialize working directory and utility scripts
  sh $utilscript/setup.sh

  # Run setpdy and initialize PDY variables
  sh $utilscript/setpdy.sh
  . PDY
done

export COMROOT=${COMROOT:-/com}
export COMIN=${COMIN:-/com/${NET}/${envir}/hiresw.${PDY}}
export COMOUT=${COMOUT:-/com/${NET}/${envir}/hiresw.${PDY}}
export COM_SREF=${COM_SREF:-/com/sref/prod}

mkdir -p $COMOUT

let srefcyc=$cyc-3
if [ $srefcyc -lt 0 ] ; then
  let srefcyc=$srefcyc+24
  export SREF_PDY=$PDYm1
else
  export SREF_PDY=$PDY
fi

let gefscyc=$cyc-6
if [ $gefscyc -lt 0 ] ; then
  let gefscyc=$gefscyc+24
  export GEFS_PDY=$PDYm1
else
  export GEFS_PDY=$PDY
fi

export srefcyc
let srefcyc2=$srefcyc

export gefscyc
let gefscyc2=$gefscyc

if [ $srefcyc2 -lt 10 ];then srefcyc2="0"${srefcyc2};fi
if [ $gefscyc2 -lt 10 ];then gefscyc2="0"${gefscyc2};fi

export COMIN_SREF=${COMIN_SREF:-$COM_SREF/sref.${SREF_PDY}/${srefcyc2}/ensprod}
export COMIN_GEFS=${COMIN_GEFS:-$COM_SREF/sref.${GEFS_PDY}/ensprod_gefs}

########################################################
# Execute the script.
$HOMEhiresw/scripts/exhiresw_smartinit.sh.ecf
########################################################

cd /tmpnwprd1
date
