#!/bin/sh

set -xa
# #### 07/30/1999 ###################
# SET SHELL PROCESSING VARIABLES
# ###################################
export PS4='$SECONDS + ' 
date

###############################
# Specify NET and RUN name
###############################
export NET=${NET:-hiresw}
export RUN=${RUN:-hiresw}

############################################################# 
# obtain unique process id (pid) and make temp directories
############################################################# 
export pid=$$
export DATA=${DATA:-${DATAROOT:?}/${jobid:?}}
mkdir $DATA
cd $DATA 

export DBN_ALERT_TYPE=${DBN_ALERT_TYPE:-HIRESW_AWIPS}

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export pgmout="OUTPUT.${pid}"

export cycle=${cycle:-t${cyc:?}z}

export DBN_NEST=`echo ${NEST}_${MODEL} | tr '[a-z]' '[A-Z]'`

# these will be used for ensemble mean

export HOMEhiresw=${HOMEhiresw:-${NWROOT:?}/hiresw.${hiresw_ver:?}}
export EXEChiresw=${EXEChiresw:-$HOMEhiresw/exec}
export FIXhiresw=${FIXhiresw:-$HOMEhiresw/fix}
export PARMhiresw=${PARMhiresw:-$HOMEhiresw/parm}
export USHhiresw=${USHhiresw:-$HOMEhiresw/ush}
export PARMutil=${PARMutil:-$HOMEhiresw/util/parm}
###################################
# Set up the UTILITIES
###################################
setpdy.sh
. PDY

export COMIN=${COMIN:-${COMROOT:?}/${NET}/${envir}/${RUN}.${PDY}}
export PCOM=${PCOM:-${PCOMROOT:?}/${NET}}

mkdir -p $PCOM
 
########################################################
# Run the ex-script
#
$HOMEhiresw/scripts/exhiresw_awips.sh.ecf_singleconus
#
########################################################

postmsg "$jlogfile" "$job FOR NEST=${NEST}${MODEL} IS COMPLETE"

cd $DATAROOT
if [ $KEEPDATA = NO ]; then rm -rf $DATA; fi
date
