#!/bin/sh 

########################################
# Preliminary data setup step
########################################
set -xa
export PS4='$SECONDS + ' 
date

###############################
# Specify NET and RUN name
###############################
export NET=${NET:-hiresw}
export RUN=${RUN:-hiresw}

########################################################### 
# obtain unique process id (pid) and make temp directories
###########################################################
export pid=$$
export DATA=${DATA:-${DATAROOT:?}/hiresw.ungrib_${NEST:?}_${MODEL:?}_${cyc:?}_${envir:?}}

# Remove old forecast data directory if it exists
if [ -d $DATA ]; then
   rm -rf $DATA
fi
mkdir -p $DATA
cd $DATA 

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export pgmout="OUTPUT.${pid}"

export cycle=${cycle:-t${cyc}z}

export SENDDBN=NO

export HOMEhiresw=${HOMEhiresw:-${NWROOT:?}/hiresw.${hiresw_ver:?}}
export EXEChiresw=${EXEChiresw:-$HOMEhiresw/exec}
export FIXhiresw=${FIXhiresw:-$HOMEhiresw/fix}
export PARMhiresw=${PARMhiresw:-$HOMEhiresw/parm}
export USHhiresw=${USHhiresw:-$HOMEhiresw/ush}

###################################
# Set up the UTILITIES
###################################

#module load prod_util


# Run setpdy and initialize PDY variables
setpdy.sh
. PDY

export COMOUT=${COMOUT:-/${COMROOT:?}/${NET}/${envir}/${RUN}.${PDY}}
export COMINgfs=${COMINgfs:-$(compath.py gfs/prod/gfs.$PDY)}
export COMINnam=${COMINnam:-$(compath.py nam/prod/nam.$PDY)}
export COMINhur=${COMINhur:-$(compath.py hur/prod/inpdata)}

mkdir -p -m 775 $COMOUT
 
########################################################
# Execute the script.
${HOMEhiresw}/scripts/exhiresw_ungrib.sh.ecf
########################################################

cd $DATAROOT
export KEEPDATA=YES
if [ $KEEPDATA = NO ]; then rm -rf $DATA; fi
date
