#!/bin/sh

set -x 

echo `date` $0 `date -u` begin
export PS4='$SECONDS + '

###########################################################
# obtain unique process id (pid) and make temp directories
###########################################################
export pid=$$
export DATA_IN=${DATA_IN:-${DATAROOT:?}}

export DATA=$DATA_IN/${jobid:?}
rm -rf $DATA
mkdir -p $DATA

cd $DATA

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export pgmout="OUTPUT.${pid}"

export cycle=t${cyc}z

###############################
# Specify NET and RUN name
##############################
export NET=hiresw
export RUN=hiresw

# Run setpdy and initialize PDY variables
setpdy.sh
. PDY

env

########################################################
# Start remove the directories
########################################################
cd $DATAROOT
for nest in nmmb arw
do
  if [ $cyc -eq 00 -o $cyc -eq 12 ]; then
    for mod in hi guam conus
    do
      for step in ungrib metgrid forecast post prdgen smartinit smartinitb bufrpost
      do
        rm -rf hiresw.${step}_${mod}_${nest}_${cyc}_${envir}
      done
    done
  else
    for mod in pr ak
    do
      for step in ungrib metgrid forecast post prdgen smartinit smartinitb bufrpost
      do
        rm -rf hiresw.${step}_${mod}_${nest}_${cyc}_${envir}
      done
    done
  fi
done

date
