#!/bin/sh

########################################
# Set up environment for HIRESW FCST
########################################
set -xa
export PS4='$SECONDS + ' 
date

export MP_PULSE=0
unset MP_DEBUG_NOTIMEOUT #recommended by Farid to avoid time out message
###############################
# Specify NET and RUN name
###############################
export NET=${NET:-hiresw}
export RUN=${RUN:-hiresw}


########################################################### 
# obtain unique process id (pid) and make temp directories
###########################################################
export pid=$$
export DATA=${DATA:-${DATAROOT:?}/hiresw.forecast_${NEST:?}_${MODEL:?}_${cyc:?}_${envir:?}}

mkdir $DATA
cd $DATA 

ecflow_client --event release_downstream

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export pgmout="OUTPUT.${pid}"

export cycle=${cycle:-t${cyc}z} 
export MP_LABELIO=YES
export MP_USE_BULK_XFER=yes

export HOMEhiresw=${HOMEhiresw:-${NWROOT:?}/hiresw.${hiresw_ver:?}}
export EXEChiresw=${EXEChiresw:-$HOMEhiresw/exec}
export FIXhiresw=${FIXhiresw:-$HOMEhiresw/fix}
export PARMhiresw=${PARMhiresw:-$HOMEhiresw/parm}
export USHhiresw=${USHhiresw:-$HOMEhiresw/ush}

export HOMEgsm=${HOMEgsm:-${NWROOTp2:?}/gsm.${gsm_ver:?}}
export FIXgsm=${FIXgsm:-${HOMEgsm}/fix/fix_am}

# Run setpdy and initialize PDY variables
# setpdy.sh
# . PDY


export PDY=${DATE}

export COMIN=${COMIN:-${COMROOT:?}/${NET}/${envir}/${RUN}.${PDY}}
export COMOUT=${COMOUT:-${COMROOT:?}/${NET}/${envir}/${RUN}.${PDY}}

if [ ${MODEL} = "arw" ]
then
  export MP_SHARED_MEMORY=yes
  export MP_USE_TOKEN_FLOW_CONTROL=yes
  export MP_INSTANCES=2
fi

# bsub post scripts  - clean these out before commit
bsub < ${HOMEhiresw}/launch_info/sub_postodd.lsf_${NEST}_${MODEL}_${cyc}
bsub < ${HOMEhiresw}/launch_info/sub_posteven.lsf_${NEST}_${MODEL}_${cyc}
bsub < ${HOMEhiresw}/launch_info/sub_prdgen.lsf_${NEST}_${MODEL}_${cyc}
## bsub < ${HOMEhiresw}/launch_info/sub_wrfbufrsnd.lsf_${NEST}_${MODEL}_${cyc}
# bsub < ${HOMEhiresw}/launch_info/sub_smartinit.lsf_${NEST}_${MODEL}_${cyc}
# bsub < ${HOMEhiresw}/launch_info/sub_smartinitb.lsf_${NEST}_${MODEL}_${cyc}
### end bsub post scripts
 
###################################################
# Execute the Script
#
${HOMEhiresw}/scripts/exhiresw_fcst.sh.ecf
#
###################################################

cat $pgmout

msg="JOB $job FOR NEST=${NEST}${MODEL} HAS COMPLETED NORMALLY."
postmsg "$jlogfile" "$msg"
date
