#!/bin/sh

########################################
# Runs HIRESW WRFBUFR and SNDP programs
########################################
set -xa
export PS4='$SECONDS + ' 
date

###############################
# Specify NET and RUN name
###############################
export NET=${NET:-hiresw}
export RUN=${RUN:-hiresw}

# 
# obtain unique process id (pid) and make temp directories
#
export pid=$$
export DATA=${DATA:-${DATAROOT:?}/hiresw.smartinit_${NEST:?}_${MODEL:?}_${cyc:?}_${envir:?}}
export INPUT_DATA=${INPUT_DATA:-${DATAROOT:?}/hiresw.prdgen_${NEST}_${MODEL}_${cyc}_${envir}}
mkdir -p $DATA
cd $DATA

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export pgmout="OUTPUT.${pid}"

export cycle=${cycle:-t${cyc}z}

export HOMEhiresw=${HOMEhiresw:-${NWROOT:?}/hiresw.${hiresw_ver:?}}
export EXEChiresw=${EXEChiresw:-$HOMEhiresw/exec}
export FIXhiresw=${FIXhiresw:-$HOMEhiresw/fix}
export PARMhiresw=${PARMhiresw:-$HOMEhiresw/parm}
export USHhiresw=${USHhiresw:-$HOMEhiresw/ush}

###################################
# Set up the UTILITIES
###################################
#module load grib_util

# no keep using local version of wgrib2
# export WGRIB2=$HOMEhiresw/exec/hiresw_wgrib2

hrs="00 03 06 09 12 15 18 21 24 27 30 33 36 39 42 45 48"
for hr in $hrs
do

  mkdir -p $DATA/smartinit_${hr}
  cd $DATA/smartinit_${hr}

  # Run setpdy and initialize PDY variables
  setpdy.sh
  . PDY
done

export COMIN=${COMIN:-${COMROOT:?}/${NET}/${envir}/hiresw.${PDY}}
export COMOUT=${COMOUT:-${COMROOT:?}/${NET}/${envir}/hiresw.${PDY}}
export COMsref=${COMsref:-${COMROOTp2:?}/sref/prod}

mkdir -p $COMOUT

let srefcyc=$cyc-3
if [ $srefcyc -lt 0 ] ; then
  let srefcyc=$srefcyc+24
  export SREF_PDY=$PDYm1
else
  export SREF_PDY=$PDY
fi

let gefscyc=$cyc-6
if [ $gefscyc -lt 0 ] ; then
  let gefscyc=$gefscyc+24
  export GEFS_PDY=$PDYm1
else
  export GEFS_PDY=$PDY
fi

export srefcyc
let srefcyc2=$srefcyc

export gefscyc
let gefscyc2=$gefscyc

if [ $srefcyc2 -lt 10 ];then srefcyc2="0"${srefcyc2};fi
if [ $gefscyc2 -lt 10 ];then gefscyc2="0"${gefscyc2};fi

export COMINsref=${COMINsref:-$COMsref/sref.${SREF_PDY}/${srefcyc2}/ensprod}
export COMINgefs=${COMINgefs:-$COMsref/sref.${GEFS_PDY}/ensprod_gefs}

########################################################
# Execute the script.
$HOMEhiresw/scripts/exhiresw_smartinit.sh.ecf
########################################################

date
