#! /bin/sh


if [ "$#" -ne 2 ]
then
echo wrong number of arguments
echo need cyc and NEST
exit
fi

cyc=$1
export NEST=${2}

cd /u/$USER    # cron does this for us - this is here just to be safe
. /etc/profile

if [ -a .profile ]; then
   . ./.profile
fi

if [ -a .bashrc ]; then
   . ./.bashrc
fi

echo cyc $cyc

module load prod_util
module load grib_util/1.0.3
module load prod_envir

export COMINhiresw=${COMROOT}/hiresw/prod/hiresw
export COMINnam=${COMROOTp1}/nam/prod/nam

vers=`cat ~/href_para`

echo vers is $vers

DATE=`cat $COMROOT/date/t${cyc}z | cut -c7-14`

# echo call ffg_input with ${DATE}${cyc}

cd /gpfs/hps/emc/meso/noscrub/Matthew.Pyle/href.${vers}/launch_info/

# ../scripts/interp_conv.scr ${DATE}${cyc}

if [ $NEST = "conus" ]
then
cat runpoe.sh_in_cray | sed s:_CYC_:${cyc}:g | sed s:_NEST_:${NEST}:g > launch_hrefrunpoe_${cyc}
elif [ $NEST = "hi" ]
then
cat runpoe.sh_in_cray_smaller | sed s:_CYC_:${cyc}:g | sed s:_NEST_:${NEST}:g > launch_hrefrunpoe_${cyc}
else
cat runpoe.sh_in_cray_small | sed s:_CYC_:${cyc}:g | sed s:_NEST_:${NEST}:g > launch_hrefrunpoe_${cyc}
fi

cat run_nawips.sh_in_cray  | sed s:_CYC_:${cyc}:g | sed s:_NEST_:${NEST}:g > launch_nawips_${cyc}

bsub < launch_hrefrunpoe_${cyc}
bsub < launch_nawips_${cyc}

#  bsub < /gpfs/hps/emc/meso/noscrub/Matthew.Pyle/href.${vers}/launch_info/send_href_ftp_${cyc} ;  bsub < /gpfs/hps/emc/meso/noscrub/Matthew.Pyle/python_tools/send_python_graphics_awip.sh_${cyc} &

# rm launch_hrefrunpoe_${cyc}
