#! /bin/sh

cd /u/$USER    # cron does this for us - this is here just to be safe
. /etc/profile

if [ -a .profile ]; then
   . ./.profile
fi

if [ -a .bashrc ]; then
   . ./.bashrc
fi


module load -a /gpfs/hps/nco/ops/nwprod/modulefiles
module load prod_envir/1.0.0
module load prod_util

base=/gpfs/hps3/emc/meso/noscrub/Matthew.Pyle/python_tools

cd $base

bsub < ${base}/all_hrefv2_06_ak.sh_prod
