#!/bin/sh

########################################
# Runs HIRESW WRFBUFR and SNDP programs
########################################
set -xa
export PS4='$SECONDS + ' 
date

###############################
# Specify NET and RUN name
###############################
export NET=${NET:-hiresw}
export RUN=${RUN:-hiresw}

export DBN_NEST=`echo ${NEST}_${MODEL} | tr '[a-z]' '[A-Z]'`


# 
# obtain unique process id (pid) and make temp directories
#
export pid=$$
export DATA=${DATA:-$DATAROOT/hiresw.smartinitb_${NEST}_${MODEL}_${cyc}_${envir}}
export INPUT_DATA=${INPUT_DATA:-$DATAROOT/hiresw.smartinit_${NEST}_${MODEL}_${cyc}_${envir}}
export PRDGEN_DATA=${PRDGEN_DATA:-$DATAROOT/hiresw.prdgen_${NEST}_${MODEL}_${cyc}_${envir}}

mkdir -p $DATA
cd $DATA

####################################
# File To Log Msgs
####################################
export jlogfile=${jlogfile:-$COMROOT/logs/jlogfiles/jlogfile.$job.$pid}

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"

export cycle=${cycle:-t${cyc}z}

###############################

export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDECF=${SENDECF:-YES}

export DBN_ALERT_TYPE_SMART=${DBN_ALERT_TYPE_SMART:-HIRESW_${DBN_NEST}_NDFD_GB2}
export DBN_ALERT_TYPE_SMART_WIDX=${DBN_ALERT_TYPE_SMART_WIDX:-HIRESW_${DBN_NEST}_NDFD_GB2_WIDX}

export HOMEhiresw=${HOMEhiresw:-$NWROOT/hiresw.${hiresw_ver}}
export EXEChiresw=${EXEChiresw:-$HOMEhiresw/exec}
export FIXhiresw=${FIXhiresw:-$HOMEhiresw/fix}
export PARMhiresw=${PARMhiresw:-$HOMEhiresw/parm}
export USHhiresw=${USHhiresw:-$HOMEhiresw/ush}

###################################
# Set up the UTILITIES
###################################
module load grib_util

# keep using local version
export WGRIB2=$HOMEhiresw/exec/hiresw_wgrib2

# Run setpdy and initialize PDY variables
setpdy.sh
. PDY

export COMROOT=${COMROOT:-/com2}
export COMIN=${COMIN:-${COMROOT}/${NET}/${envir}/${RUN}.${PDY}}
export COMOUT=${COMOUT:-${COMROOT}/${NET}/${envir}/${RUN}.${PDY}}
export COMsref=${COMsref:-${COMROOT}/sref/prod}

mkdir -p $COMOUT

let srefcyc=$cyc-3
if [ $srefcyc -lt 0 ] ; then
  let srefcyc=$srefcyc+24
  export SREF_PDY=$PDYm1
else
  export SREF_PDY=$PDY
fi

let gefscyc=$cyc-6
if [ $gefscyc -lt 0 ] ; then
  let gefscyc=$gefscyc+24
  export GEFS_PDY=$PDYm1
else
  export GEFS_PDY=$PDY
fi

export srefcyc
let srefcyc2=$srefcyc

export gefscyc
let gefscyc2=$gefscyc

if [ $srefcyc2 -lt 10 ];then srefcyc2="0"${srefcyc2};fi
if [ $gefscyc2 -lt 10 ];then gefscyc2="0"${gefscyc2};fi

export COMINsref=${COMINsref:-$COM_SREF/sref.${SREF_PDY}/${srefcyc2}/ensprod}
export COMINgefs=${COMINgefs:-$COM_SREF/sref.${GEFS_PDY}/ensprod_gefs}

########################################################
# Execute the script.
$HOMEhiresw/scripts/exhiresw_smartinitb.sh.ecf
########################################################

date
