#!/bin/sh

set -xa
# #### 08/25/1999 ###################
# SET SHELL PROCESSING VARIABLES
# ###################################
export PS4='$SECONDS + ' 
date

###############################
# Specify NET and RUN name
###############################
export NET=${NET:-hiresw}
export RUN=${RUN:-href} 
  
###########################################################
# obtain unique process id (pid) and make temp directories
###########################################################
export pid=$$
export DATA=${DATA:-${DATAROOT}/${job}.${pid}}
mkdir $DATA
cd $DATA 

####################################
# File To Log Msgs
####################################
export jlogfile=${jlogfile:-/com/logs/jlogfiles/jlogfile.${job}.${pid}}

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"

export cycle=${cycle:-t${cyc}z}

##################################################
# SENDECF  - Flag Events on ecFLOW
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
##################################################
export SENDCOM=${SENDCOM:-YES}
export SENDECF=${SENDECF:-YES}
export SENDDBN=${SENDDBN:-YES}

export HOMEhref=${HOMEhref:-$NWROOT/href.${href_ver}}
export GEMPAKhref=${GEMPAKhref:-$HOMEhref/gempak}

export finc=1
export fend=48

export fstart=00
export model=${NEST}${MODEL}

export GRIB=5km
export EXT=
export DBN_ALERT_TYPE=${DBN_ALERT_TYPE:-HIRESW_GEMPAK}

#
# Copy model specific GEMPAK tables into working directory
#
cp $GEMPAKhref/fix/*.tbl .

#
# Now set up GEMPAK/NTRANS environment
#
. /nwprod/gempak/.gempak

# Run setpdy and initialize PDY variables
setpdy.sh
. PDY

export COMROOT=${COMROOT:-/com2}
export COMIN=${COMIN:-${COMROOT}/${NET}/${envir}/href.${PDY}}
export COMOUT=${COMOUT:-${COMROOT}/nawips/${envir}/href.${PDY}}

if [ ! -f $COMOUT ] ; then
  mkdir -p -m 775 $COMOUT
fi
 
env

#################################################################
# Execute the script
$HOMEhref/scripts/exnawips_href.sh.ecf
#################################################################

cd ${DATAROOT}
if [ $KEEPDATA = NO ]; then rm -rf $DATA; fi
date
