#!/bin/bash

#############################################################
# 02/02/2015 Binbin Zhou, create for run all scripts 
# 08/11/2022 Jun Du, added a variable "region"
# 03/20/2023 Jun Du, the package name changed to rrfs_enspost
# 04/10/2023 Jun Du, added variable "name" to rearrange member's order
#                    by naming ctl run as mem01 rather than mem00
# 04/25/2023 Jun Du, added a version of time-lag ensemble (type=single or timelag)
# 02/06/2024 M. Pyle Switch to REFS
# 04/11/2025 M. Pyle Making a "by the hour" version

#############################################################

########################################
# Preliminary data setup step
########################################

set -xa
export PS4='$SECONDS + ' 
date

###################################
# Specify NET and RUN Name and model
####################################
export NET=${NET:-refs}
export RUN=${RUN:-refs}

###############################################################
# This block can be modified for different Production test
# environment. This is used for operational testings
###############################################################

## PDY not included here as pull data from PDYm1 as well
# without timelagging maybe should include PDY here?


export HOMErefs=${HOMErefs:-$NWROOT/refs.${refs_ver}} 
export EXECrefs=${EXECrefs:-$HOMErefs/exec}
export PARMrefs=${PARMrefs:-$HOMErefs/parm}
export USHrefs=${USHrefs:-$HOMErefs/ush}
export FIXrefs=${FIXrefs:-$HOMErefs/fix}
export SCRIPTSrefs=${SCRIPTSrefs:-$HOMErefs/scripts}

###########################################################
# obtain unique process id (pid) and make temp directories
###########################################################

export pid=$$
# export DATA=${DATA:-${DATAROOT}/${jobid}.${pid}}
# export DATA=${DATA:-${DATAROOT}/${jobid}}
export DATA=${DATA:-${DATAROOT}/${NET}_preproc_rrfs_${NEST}_${cyc}_${refs_ver_2d}_${envir}} 

if [ $fhr -eq '00' -a -s $DATA ]; then
  echo "$DATA existed at fhr=$fhr, move it to hold ..."
  mv $DATA ${DATA}_$(date +%Y%m%d_%H%M).hold;
fi

mkdir -p $DATA

cd $DATA

echo here with DATA $DATA
echo here with DATAROOT $DATAROOT

####################################
# Determine Job Output Name on System
####################################
export pgmout="OUTPUT.$$"

export cycle=${cycle:-t${cyc}z}

##################################################
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
##################################################

export SENDCOM=${SENDCOM:-YES}
export SENDECF=${SENDECF:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDDBN_NTC=${SENDDBN_NTC:-NO}

###################################
# Set up the UTILITIES
###################################

msg="JOB $job HAS BEGUN"
postmsg "$msg"

#
# Run setpdy and initialize PDY variables
#


export cycle=${cycle:-t${cyc}z}

if [ -s ${DATA}/PDY ]; then 
  source ${DATA}/PDY
else
  setpdy.sh
  . ./PDY
fi

echo have PDY as $PDY

##############################################
# Define running directory and COM directories
##############################################
export COMINrrfs=${COMINrrfs:-$(compath.py ${envir}/com/rrfs/${rrfs_ver})}
export COMOUT=${COMOUT:-$(compath.py -o $NET/${refs_ver})/${RUN}.${PDY}/${cyc}}

if [ ! -d $COMOUT ] ; then 
 mkdir -p $COMOUT
fi

export GESROOT=${GESROOT:-$(compath.py -o $NET/${refs_ver})/refsprep}
if [ ! -d $GESROOT ] ; then
 mkdir -p $GESROOT
fi

export GESOUT=${GESOUT:-${GESROOT}/${RUN}}

export pgmout="OUTPUT.$$"

#######################################################
# Pass information which is needed to run the Script
#######################################################

# export VERBOSE=YES
#######################################################
${SCRIPTSrefs}/exrefs_preprocess_rrfs.sh ${fhr}
export err=$?; err_chk 
#################################################################

# Post successful completion message
msg="JOB $job HAS COMPLETED NORMALLY."
postmsg $jlogfile "$msg"

# Print exec output
if [ -e $pgmout ]; then
  cat $pgmout
fi

cd $DATAROOT
#if [ $KEEPDATA = NO -a $fhr -eq '60' ]; then rm -rf $DATA; fi
if [ $KEEPDATA = NO ]; then
#  rm -rf $DATA;
   echo "it is a shared working $DATA and JREFS_CLEANUP job will clean it later.."
fi

date
