#!/bin/ksh 

########################################
# Preliminary data setup step
#
# 05/01/2023, Jun Du: added a timelag version (type=timelag, single)
# 11/21/2025, M. Pyle: eliminated generality to focus on timelag version.
#
########################################
set -xa
export PS4='$SECONDS + ' 
date

########################################################### 
# obtain unique process id (pid) and make temp directories
###########################################################
export pid=$$
export DATA=${DATA:-${DATAROOT}/${jobid}.${pid}}
mkdir -p $DATA
cd $DATA

msg="JOB $job HAS BEGUN"

postmsg  "$msg"

export cycle=${cycle:-t${cyc}z}
setpdy.sh
. ./PDY

##################################################
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
##################################################
export SENDCOM=${SENDCOM:-YES}
export SENDECF=${SENDECF:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDDBN_NTC=${SENDDBN_NTC:-NO}

###############################################################
# This block can be modified for different Production test
# environment. This is used for operational testings
###############################################################

## PDY not included here as pull data from PDYm1 as well

# Save it for time lag ensemble

export HOMErefs=${HOMErefs:-$PACKAGEROOT/refs.${refs_ver}}
export EXECrefs=${EXECrefs:-$HOMErefs/exec}
export PARMrefs=${PARMrefs:-$HOMErefs/parm}
export USHrefs=${USHrefs:-$HOMErefs/ush}
export FIXrefs=${FIXrefs:-$HOMErefs/fix}
export SCRIPTSrefs=${SCRIPTSrefs:-$HOMErefs/scripts}

###################################
# Specify NET and RUN Name and model
####################################
export NET=${NET:-refs}
export RUN=${RUN:-refs}

##############################################
# Define running directory and COM directories
##############################################

export COMINhrrr=${COMINhrrr:-$(compath.py ${envir}/com/$NET/${refs_ver})/refsprep/refs}

export COMOUT=${COMOUT:-$(compath.py -o $NET/${refs_ver})/$RUN.${PDY}/${cyc}}
export COMIN=${COMIN:-$(compath.py -o $NET/${refs_ver})/refsprep/$RUN}

if [ ! -d $COMOUT/ensprod ] ; then 
 mkdir -p $COMOUT/ensprod
fi

export pgmout="OUTPUT.$$"
 
########################################################
# Execute the script.
$HOMErefs/scripts/exrefs_eas.sh
export err=$?; err_chk
#################################################################

# Post successful completion message
msg="JOB $job HAS COMPLETED NORMALLY."
postmsg $jlogfile "$msg"

# Print exec output
if [ -e $pgmout ]; then
  cat $pgmout
fi

cd $DATAROOT
if [ $KEEPDATA = NO ]; then rm -rf $DATA; fi

date
