#!/bin/bash

set -xa
# #### 08/25/1999 ###################
# SET SHELL PROCESSING VARIABLES
# ###################################
export PS4='$SECONDS + ' 
date

###########################################################
# obtain unique process id (pid) and make temp directories
###########################################################
export DATA=${DATA:-${DATAROOT}/${jobid}}
mkdir $DATA
cd $DATA 

# Run setpdy and initialize PDY variables
export cycle=${cycle:-t${cyc}z}
setpdy.sh
. ./PDY

##################################################
# SENDECF  - Flag Events on ecFLOW
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
##################################################
export SENDCOM=${SENDCOM:-YES}
export SENDECF=${SENDECF:-YES}
export SENDDBN=${SENDDBN:-YES}

export HOMErefs=${HOMErefs:-$PACKAGEROOT/refs.${refs_ver}}
export GEMPAKrefs=${GEMPAKrefs:-$HOMErefs/gempak}

if [ $type = single ];then
 export finc=1
 export fend=60
 export fstart=01
else
 export finc=1
 export fend=54
 export fstart=01
fi

export DBN_ALERT_TYPE=${DBN_ALERT_TYPE:-RRFS_GEMPAK}

###############################
# Specify NET and RUN name
###############################
export NET=${NET:-refs}
export RUN=${RUN:-refs} 
  
export COMOUT=${COMOUT:-$(compath.py -o $NET/${refs_ver})/${RUN}.${PDY}/gempak}
export COMIN=${COMIN:-$(compath.py -o $NET/${refs_ver})/${RUN}.${PDY}/ensprod}

if [ ! -f $COMOUT ] ; then
  mkdir -p -m 775 $COMOUT
fi
 
export pgmout="OUTPUT.$$"

env

#################################################################
# Execute the script
rm -f poescript

echo "$HOMErefs/scripts/exrefs_gempak.sh.ecf mean > $DATA/${NEST}_mean.$$ " >>poescript
echo "$HOMErefs/scripts/exrefs_gempak.sh.ecf pmmn > $DATA/${NEST}_pmmn.$$ " >>poescript
echo "$HOMErefs/scripts/exrefs_gempak.sh.ecf avrg > $DATA/${NEST}_avrg.$$ " >>poescript
echo "$HOMErefs/scripts/exrefs_gempak.sh.ecf prob > $DATA/${NEST}_prob.$$ " >>poescript
echo "$HOMErefs/scripts/exrefs_gempak.sh.ecf sprd > $DATA/${NEST}_sprd.$$ " >>poescript
echo "$HOMErefs/scripts/exrefs_gempak.sh.ecf eas  > $DATA/${NEST}_eas.$$  " >>poescript
echo "$HOMErefs/scripts/exrefs_gempak.sh.ecf lpmm  > $DATA/${NEST}_lpmm.$$  " >>poescript

if [ ${NEST} =  'conus' ]
then
if [ $type = single ];then
#export finc=3
#export fend=60
#export fstart=06
export finc=1
export fend=60
export fstart=01
else
export finc=1
export fend=54
export fstart=01
fi
echo "$HOMErefs/scripts/exrefs_gempak.sh.ecf ffri  > $DATA/${NEST}_ffri.$$  " >>poescript
fi

chmod 775 ./poescript

mpiexec -n $NTASK -ppn $PTILE --cpu-bind verbose,core cfp ./poescript
export err=$?; err_chk

cat $DATA/${NEST}_mean.$$
cat $DATA/${NEST}_pmmn.$$
cat $DATA/${NEST}_avrg.$$
cat $DATA/${NEST}_prob.$$
cat $DATA/${NEST}_sprd.$$
cat $DATA/${NEST}_eas.$$
cat $DATA/${NEST}_lpmm.$$
if [ ${NEST} =  'conus' ]
then
cat $DATA/${NEST}_ffri.$$
fi
#################################################################

cd ${DATAROOT}
if [ $KEEPDATA = NO ]; then rm -rf $DATA; fi
date
