#!/bin/sh

#############################################################
# 02/02/2015 Binbin Zhou, create for run all scripts 
# 08/11/2022 Jun Du, added a variable "region"
# 03/20/2023 Jun Du, the package name changed to rrfs_enspost
# 04/10/2023 Jun Du, added variable "name" to rearrange member's order
#                    by naming ctl run as mem01 rather than mem00
# 04/25/2023 Jun Du, added a version of time-lag ensemble (type=single or timelag)
# 09/21/2023 M. Pyle, adding a HRRR preprocessing job
# 02/06/2024 M. Pyle, Switch from rrfs --> refs
#############################################################

########################################
# Preliminary data setup step
########################################

set -xa
export PS4='$SECONDS + ' 
date

###################################
# Specify NET and RUN Name and model
####################################
export NET=${NET:-refs}
export RUN=${RUN:-refs}

export IOBUF_PARAMS='*:size=8M:count=8'

###############################################################
# This block can be modified for different Production test
# environment. This is used for operational testings
###############################################################

## PDY not included here as pull data from PDYm1 as well
# without timelagging maybe should include PDY here?

export COMINhrrr=${COMINhrrr:-$(compath.py ${envir}/com/hrrr/${hrrr_ver}/hrrr)}

export HOMErefs=${HOMErefs:-$NWROOT/refs.${refs_ver}} 
export EXECrefs=${EXECrefs:-$HOMErefs/exec}
export PARMrefs=${PARMrefs:-$HOMErefs/parm}
export USHrefs=${USHrefs:-$HOMErefs/ush}
export FIXrefs=${FIXrefs:-$HOMErefs/fix}
export SCRIPTSrefs=${SCRIPTSrefs:-$HOMErefs/scripts}

# this needs to be generalized
# export ndate=/apps/ops/prod/nco/core/prod_util.v2.0.8/exec/ndate

###########################################################
# obtain unique process id (pid) and make temp directories
###########################################################

export pid=$$
export DATA=${DATA:-${DATAROOT}/${jobid}.${pid}}
mkdir -p $DATA
rm -rf $DATA/*
cd $DATA

####################################
# Determine Job Output Name on System
####################################
export pgmout="OUTPUT.$$"

export cycle=${cycle:-t${cyc}z}

##################################################
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
##################################################

export SENDCOM=${SENDCOM:-YES}
export SENDECF=${SENDECF:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDDBN_NTC=${SENDDBN_NTC:-NO}

###################################
# Set up the UTILITIES
###################################

msg="JOB $job HAS BEGUN"
postmsg "$msg"

#
# Run setpdy and initialize PDY variables
#


export cycle=${cycle:-t${cyc}z}

setpdy.sh
. ./PDY

echo have PDY as $PDY

##############################################
# Define running directory and COM directories
##############################################

export COMOUT=${COMOUT:-$(compath.py -o $NET/${refs_ver})/${RUN}.${PDY}}

if [ ! -d $COMOUT ] ; then 
 mkdir -p $COMOUT/ensprod
 mkdir -p $COMOUT/verf_g2g
fi

export GESOUT=${GESOUT:-${GESROOT}/${RUN}}


###################################################

${SCRIPTSrefs}/exrefs_preprocess_hrrr.sh

cd $DATAROOT
if [ $KEEPDATA = NO ]; then rm -rf $DATA; fi

date
