#!/bin/bash

#############################################################
# 02/02/2015 Binbin Zhou, create for run all scripts 
# 04/26/2023 Jun Du, added a timelag version (type=timelag)
# 02/06/2024 M. Pyle - switches things to REFS
#############################################################

########################################
# Preliminary data setup step
########################################

set -xa
export PS4='$SECONDS + ' 
date

###########################################################
# obtain unique process id (pid) and make temp directories
###########################################################
export DATA=${DATA:-${DATAROOT:?}/${jobid:?}}
mkdir -p $DATA

# temp - need a better option
# if [ $fhr -eq '01' ]
# then
# rm -rf $DATA/*
# fi

cd $DATA

msg="JOB $job HAS BEGUN"
postmsg "$msg"

#
# Run setpdy and initialize PDY variables
#

export cycle=${cycle:-t${cyc}z}

setpdy.sh
. ./PDY

##################################################
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
##################################################
export ndate=/apps/ops/prod/nco/core/prod_util.v2.0.8/exec/ndate

export SENDCOM=${SENDCOM:-YES}
export SENDECF=${SENDECF:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDDBN_NTC=${SENDDBN_NTC:-NO}

export HOMErefs=${HOMErefs:-$PACKAGEROOT/refs.${refs_ver}} 
export EXECrefs=${EXECrefs:-$HOMErefs/exec}
export PARMrefs=${PARMrefs:-$HOMErefs/parm}
export USHrefs=${USHrefs:-$HOMErefs/ush}
export FIXrefs=${FIXrefs:-$HOMErefs/fix}
export SCRIPTSrefs=${SCRIPTSrefs:-$HOMErefs/scripts}

###################################
# Specify NET and RUN Name and model
####################################
export NET=${NET:-refs}
export RUN=${RUN:-refs}

export IOBUF_PARAMS='*:size=8M:count=8'

##############################################
# Define running directory and COM directories
##############################################

## PDY not included here as pull data from PDYm1 as well

# think about this one.  is it COMINrefs?  Or just COMIN, as is internal to system?
export COMINrefs=${COMINrefs:-$GESROOT/${RUN}}

export COMOUT=${COMOUT:-$(compath.py -o $NET/${refs_ver})/$RUN.${PDY}}
export COMINffg=${COMINffg:-$(compath.py -o $NET/${refs_ver})/${RUN}.${PDY}}
export COMINffgm1=${COMINffg:-$(compath.py -o $NET/${refs_ver})/${RUN}.${PDYm1}}

if [ ! -d $COMOUT/ensprod ] ; then 
 mkdir -p $COMOUT/ensprod
 mkdir -p $COMOUT/verf_g2g
 mkdir -p $COMOUT/wmo
fi

export pgmout="OUTPUT.$$"

#######################################################
# Pass information which is needed to run the Script
#######################################################

# export VERBOSE=YES

###################################################
# Execute the Script exrefs_ensprod.sh.ecf

# if [ -e ./poe.* ]
# then
# rm -rf ./poe.*
# fi

echo "$SCRIPTSrefs/exrefs_ensprod_link.sh.ecf $fhr $type" > poe.link.${fhr}
echo "$SCRIPTSrefs/exrefs_ensprod.sh.ecf $fhr $type" > poe.ensprod.${fhr}

chmod 775 poe.link.${fhr}
chmod 775 poe.ensprod.${fhr}

# mpiexec -n $NTASK -ppn $PTILE --cpu-bind verbose,core cfp ./poe.link.${fhr}
./poe.link.${fhr}
export err=$?; err_chk

echo to try running ensprod.all

# mpiexec -n $NTASK -ppn $PTILE --cpu-bind verbose,core cfp ./poe.ensprod.${fhr}
./poe.ensprod.${fhr}
export err=$?; err_chk


msg="JOB $job HAS COMPLETED NORMALLY."
postmsg "$msg"
date

cd $DATAROOT
if [ $KEEPDATA = NO ]; then rm -rf $DATA; fi

date
