#!/bin/bash

#############################################################
# 02/02/2015 Binbin Zhou, create for run all scripts 
# 04/26/2023 Jun Du, added a timelag version (type=timelag)
# 02/06/2024 M. Pyle - switches things to REFS
#############################################################

########################################
# Preliminary data setup step
########################################

set -xa
export PS4='$SECONDS + ' 
date

###################################
# Specify NET and RUN Name and model
####################################
export NET=${NET:-refs}
export RUN=${RUN:-refs}

###########################################################
# obtain unique process id (pid) and make temp directories
###########################################################
#export DATA=${DATA:-${DATAROOT:?}/${jobid:?}}
export DATA=${DATA:-${DATAROOT}/${NET}_ensprod_${NEST}_${cyc}_${refs_ver_2d}_${envir}}

if [ $fhr -eq '01' -a -s $DATA ]; then
  echo "$DATA existed at fhr=$fhr, move it to hold ..."
  mv $DATA ${DATA}_$(date +%Y%m%d_%H%M).hold;
fi

mkdir -p $DATA

cd $DATA

msg="JOB $job HAS BEGUN"
postmsg "$msg"

#
# Run setpdy and initialize PDY variables
#

export cycle=${cycle:-t${cyc}z}

if [ -s ${DATA}/PDY ]; then 
  source ${DATA}/PDY
else
  setpdy.sh
  . ./PDY
fi

##################################################
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
##################################################

export SENDCOM=${SENDCOM:-YES}
export SENDECF=${SENDECF:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDDBN_NTC=${SENDDBN_NTC:-NO}

export HOMErefs=${HOMErefs:-$PACKAGEROOT/refs.${refs_ver}} 
export EXECrefs=${EXECrefs:-$HOMErefs/exec}
export PARMrefs=${PARMrefs:-$HOMErefs/parm}
export USHrefs=${USHrefs:-$HOMErefs/ush}
export FIXrefs=${FIXrefs:-$HOMErefs/fix}
export SCRIPTSrefs=${SCRIPTSrefs:-$HOMErefs/scripts}

##############################################
# Define running directory and COM directories
##############################################

## PDY not included here as pull data from PDYm1 as well

export COMINhrrr=${COMINhrrr:-$(compath.py ${envir}/com/$NET/${refs_ver})/refsprep/refs}
export COMIN=${COMIN:-$(compath.py -o $NET/${refs_ver})/refsprep/$RUN}

export COMOUT=${COMOUT:-$(compath.py -o $NET/${refs_ver})/$RUN.${PDY}/${cyc}}
export COMINffg=${COMINffg:-$(compath.py -o $NET/${refs_ver})/${RUN}.${PDY}/${cyc}}
export COMINffgm1=${COMINffg:-$(compath.py -o $NET/${refs_ver})/${RUN}.${PDYm1}/${cyc}}

if [ ! -d $COMOUT/ensprod ] ; then 
 mkdir -p $COMOUT/ensprod
fi

export pgmout="OUTPUT.$$"

#######################################################
# Pass information which is needed to run the Script
#######################################################

# export VERBOSE=YES

###################################################
# Execute the Script exrefs_ensprod.sh
$SCRIPTSrefs/exrefs_ensprod_link.sh $fhr
export err=$?; err_chk 
$SCRIPTSrefs/exrefs_ensprod.sh $fhr
export err=$?; err_chk 
#################################################################

# Post successful completion message
msg="JOB $job HAS COMPLETED NORMALLY."
postmsg $jlogfile "$msg"

# Print exec output
if [ -e $pgmout ]; then
  cat $pgmout
fi

cd $DATAROOT
#if [ $KEEPDATA = NO ]; then rm -rf $DATA; fi
if [ $KEEPDATA = NO ]; then
#  rm -rf $DATA;
   echo "it is a shared working $DATA and JREFS_CLEANUP job will clean it later.."
fi

date
