#!/bin/bash

set -xa
# #### 08/25/1999 ###################
# SET SHELL PROCESSING VARIABLES
# ###################################
export PS4='$SECONDS + ' 
date

###########################################################
# obtain unique process id (pid) and make temp directories
###########################################################
export DATA=${DATA:-${DATAROOT:?}/${jobid:?}}
mkdir $DATA
cd $DATA 

# Run setpdy and initialize PDY variables
export cycle=${cycle:-t${cyc}z}
setpdy.sh
. ./PDY

##################################################
# SENDECF  - Flag Events on ecFLOW
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
##################################################
export SENDCOM=${SENDCOM:-YES}
export SENDECF=${SENDECF:-YES}
export SENDDBN=${SENDDBN:-YES}

export HOMErrfs=${HOMErrfs:-$PACKAGEROOT/rrfs.${rrfs_ver}}
export USHrrfs=${USHrrfs:-$HOMErrfs/ush}
export PARMwmo=${PARMwmo:-$HOMErrfs/parm/wmo}

###############################
# Specify NET and RUN name
###############################
export NET=${NET:-rrfs}
export RUN=${RUN:-rrfs} 

export COMIN=${COMIN:-$(compath.py -o $NET/${rrfs_ver})/$RUN.${PDY}/$type/ensprod}
export COMOUT=${COMOUT:-$(compath.py -o $NET/${rrfs_ver})/$RUN.${PDY}/$type/wmo}

if [ ! -f $COMOUT ] ; then
  mkdir -p -m 775 $COMOUT
fi

export pgmout=OUTPUT.$$

#################################################################
# Execute the script
$HOMErrfs/scripts/exrrfs_enspost_awips.sh.ecf $type
#################################################################

cd ${DATAROOT}
echo in AWIPS jobs down here with KEEPDATA $KEEPDATA
echo in AWIPS jobs down here with DATA $DATA
if [ $KEEPDATA = NO ]; then rm -rf $DATA; fi
date
