#! /bin/sh


if [ "$#" -ne 3 ]
then
echo wrong number of arguments
echo need cyc and NEST and DATE
exit
fi

cyc=$1
export NEST=${2}
export DATE=${3}

cd /u/$USER    # cron does this for us - this is here just to be safe
. /etc/profile

if [ -a .profile ]; then
   . ./.profile
fi

if [ -a .bashrc ]; then
   . ./.bashrc
fi

echo cyc $cyc

module load prod_util
module load grib_util/1.0.3
module load prod_envir

export COMINhiresw=${COMROOT}/hiresw/prod/hiresw
export COMINnam=${COMROOTp2}/nam/prod/nam
export COMINnam=/gpfs/hps2/ptmp/Matthew.Pyle/com/nam/prod/nam
export COMINhrrr=${COMROOTp2}/hrrr/prod/hrrr
export COMINhrrr=/gpfs/hps2/ptmp/Matthew.Pyle/com/hrrr/prod/hrrr

vers=`cat ~/href_exp`

echo vers is $vers

# DATE=`cat $COMROOT/date/t${cyc}z | cut -c7-14`

export DATEm1=`$NDATE -24 ${DATE}00 | cut -c1-8`

cd /gpfs/hps3/emc/meso/noscrub/Matthew.Pyle/git_repo/EMC_hrw/href.${vers}/launch_info/

if [ $NEST = "conus" ]
then

loop=1
fileone=$COMINhiresw.${DATE}/hiresw.t${cyc}z.nmmb_5km.f36.conus.grib2
filetwo=$COMINhiresw.${DATE}/hiresw.t${cyc}z.arw_5km.f36.conus.grib2
filethree=$COMINhiresw.${DATE}/hiresw.t${cyc}z.arw_5km.f36.conusmem2.grib2

ls -l $fileone $filetwo $filethree


## never wait for 06Z and 18Z CONUS HIRESW as does not exist
if [ $cyc = "00"  -o $cyc = "12" ]
then

while [ $loop -lt 180 ]
do
if [ ! -e $fileone -o ! -e $filetwo -o ! -e $filethree ]
then
echo gonna sleep as missing at least one
sleep 120
echo loop now $loop
fi
let loop=loop+1
done

fi


cat runpoe.sh_in_cray_retro | sed s:_CYC_:${cyc}:g | sed s:_NEST_:${NEST}:g | sed s:_DATE_:${DATE}:g | sed s:_DATEm1_:${DATEm1}:g > launch_hrefrunpoe_${cyc}

elif [ $NEST = "hi" ]
then
cat runpoe.sh_in_cray_smaller | sed s:_CYC_:${cyc}:g | sed s:_NEST_:${NEST}:g > launch_hrefrunpoe_${cyc}
elif [ $NEST = "ak" ]
then

MYCOM=/gpfs/hps2/ptmp/Matthew.Pyle/com/hiresw/test
loop=1
fileone=$COMINhiresw.${DATE}/hiresw.t${cyc}z.nmmb_5km.f36.ak.grib2
filetwo=$COMINhiresw.${DATE}/hiresw.t${cyc}z.arw_5km.f36.ak.grib2
filethree=$COMINhiresw.${DATE}/hiresw.t${cyc}z.arw_5km.f36.akmem2.grib2

ls -l $fileone $filetwo $filethree

while [ $loop -lt 180 ]
do

if [ ! -e $fileone -o ! -e $filetwo -o ! -e $filethree ]
then
echo gonna sleep as missing at least one
echo loop now $loop
sleep 120
fi

let loop=loop+1
done

cat runpoe.sh_in_cray_small | sed s:_CYC_:${cyc}:g | sed s:_NEST_:${NEST}:g > launch_hrefrunpoe_${cyc}

else
cat runpoe.sh_in_cray_small | sed s:_CYC_:${cyc}:g | sed s:_NEST_:${NEST}:g > launch_hrefrunpoe_${cyc}
fi

# cat run_nawips.sh_in_cray  | sed s:_CYC_:${cyc}:g | sed s:_NEST_:${NEST}:g > launch_nawips_${cyc}

# cat runawips.sh_in_cray | sed s:_CYC_:${cyc}:g | sed s:_NEST_:${NEST}:g > launch_awips_${cyc}


cat runpoe.gempaksend.sh_in_cray_retro | sed s:_DATE_:${DATE}:g | sed s:_CYC_:${cyc}:g | sed s:_NEST_:${NEST}:g > launch_gempaksend_${cyc}

bsub < launch_hrefrunpoe_${cyc}
# bsub < launch_nawips_${cyc}
# bsub < launch_awips_${cyc}

# rm launch_hrefrunpoe_${cyc}
