#! /bin/sh


if [ "$#" -ne 2 ]
then
echo wrong number of arguments
echo need cyc and NEST
exit
fi

cyc=$1
export NEST=${2}

cd /u/$USER    # cron does this for us - this is here just to be safe
. /etc/profile

if [ -a .profile ]; then
   . ./.profile
fi

if [ -a .bashrc ]; then
   . ./.bashrc
fi

echo cyc $cyc

module load dev/grib_util/1.1.0

export COMINhiresw=${COMROOT}/hiresw/prod/hiresw
export COMINnam=${COMROOTp2}/nam/prod/nam
export COMINhrrr=${COMROOTp2}/hrrr/prod/hrrr

vers=`cat ~/href_exp`

echo vers is $vers

DATE=`cat $COMROOT/date/t${cyc}z | cut -c7-14`

cd /gpfs/dell2/emc/modeling/noscrub/Matthew.Pyle/EMC_hrw/href.${vers}/launch_info/

if [ $NEST = "conus" -o $NEST = "ak" ]
then
# cat runpoe.preprocget.sh_in_dell | sed s:_CYC_:${cyc}:g | sed s:_NEST_:${NEST}:g > launch_hrefpreprocgetpoe_dell_${cyc}
cat runpoe.preprocv3.sh_in_dell | sed s:_CYC_:${cyc}:g | sed s:_NEST_:${NEST}:g > launch_hrefv3preprocpoe_dell_${cyc}
fi

# bsub < launch_hrefpreprocgetpoe_${cyc}

# sleep 600

echo WGRIB2 is $WGRIB2
bsub < launch_hrefv3preprocpoe_dell_${cyc}
