#! /bin/sh


if [ "$#" -ne 2 ]
then
echo wrong number of arguments
echo need cyc and NEST
exit
fi

cyc=$1
CYC=$1
export NEST=${2}
export dom=${2}

cd /u/$USER    # cron does this for us - this is here just to be safe
. /etc/profile

if [ -a .profile ]; then
   . ./.profile
fi

if [ -a .bashrc ]; then
   . ./.bashrc
fi

echo cyc $cyc

module load prod_util
module load grib_util/1.0.3
module load prod_envir

export COMINhiresw=${COMROOT}/hiresw/prod/hiresw
export COMINnam=${COMROOTp2}/nam/prod/nam
export COMINnam=/gpfs/hps2/ptmp/Matthew.Pyle/com/nam/prod/nam
export COMINhrrr=${COMROOTp2}/hrrr/prod/hrrr
export COMINhrrr=/gpfs/hps2/ptmp/Matthew.Pyle/com/hrrr/prod/hrrr

vers=`cat ~/href_exp`

echo vers is $vers

DATE=`cat $COMROOT/date/t${cyc}z | cut -c7-14`

cd /gpfs/hps3/emc/meso/noscrub/Matthew.Pyle/git_repo/EMC_hrw/href.${vers}/launch_info/

if [ $NEST = "conus" ]
then

../scripts/interp_conv.scr ${DATE}${cyc}
loop=1
fileone=$COMINhiresw.${DATE}/hiresw.t${cyc}z.nmmb_5km.f36.conus.grib2
filetwo=$COMINhiresw.${DATE}/hiresw.t${cyc}z.arw_5km.f36.conus.grib2
filethree=$COMINhiresw.${DATE}/hiresw.t${cyc}z.arw_5km.f36.conusmem2.grib2
filefour=/gpfs/hps2/ptmp/Matthew.Pyle/com/hrrr/prod/hrrr.${DATE}/hrrr.t${cyc}z.f24.grib2

ls -l $fileone $filetwo $filethree $filefour


## never wait for 06Z and 18Z CONUS HIRESW as does not exist
if [ $cyc = "00"  -o $cyc = "12" ]
then

while [ $loop -lt 90 ]
do
if [ ! -e $fileone -o ! -e $filetwo -o ! -e $filethree -o ! -e $filefour ]
then
echo gonna sleep as missing at least one
sleep 2
echo loop now $loop
fi
let loop=loop+1

done

fi


cat runpoe.sh_in_cray | sed s:_CYC_:${cyc}:g | sed s:_NEST_:${NEST}:g > launch_hrefrunpoe_${cyc}
elif [ $NEST = "hi" ]
then
cat runpoe.sh_in_cray_smaller | sed s:_CYC_:${cyc}:g | sed s:_NEST_:${NEST}:g > launch_hrefrunpoe_${cyc}
elif [ $NEST = "ak" ]
then

MYCOM=/gpfs/hps2/ptmp/Matthew.Pyle/com/hiresw/test
loop=1
fileone=$COMINhiresw.${DATE}/hiresw.t${cyc}z.nmmb_5km.f36.ak.grib2
filetwo=$COMINhiresw.${DATE}/hiresw.t${cyc}z.arw_5km.f36.ak.grib2
filethree=$COMINhiresw.${DATE}/hiresw.t${cyc}z.arw_5km.f36.akmem2.grib2

ls -l $fileone $filetwo $filethree

while [ $loop -lt 180 ]
do

if [ ! -e $fileone -o ! -e $filetwo -o ! -e $filethree ]
then
echo gonna sleep as missing at least one
echo loop now $loop
sleep 120
fi

let loop=loop+1
done

cat runpoe.sh_in_cray_small | sed s:_CYC_:${cyc}:g | sed s:_NEST_:${NEST}:g > launch_hrefrunpoe_${cyc}

else
cat runpoe.sh_in_cray_small | sed s:_CYC_:${cyc}:g | sed s:_NEST_:${NEST}:g > launch_hrefrunpoe_${cyc}
fi

cat run_nawips.sh_in_cray  | sed s:_CYC_:${cyc}:g | sed s:_NEST_:${NEST}:g > launch_nawips_${cyc}_${dom}

cat runawips.sh_in_cray | sed s:_CYC_:${cyc}:g | sed s:_NEST_:${NEST}:g > launch_awips_${cyc}_${dom}

## EAS stuff

if [ $dom = "conus" ]
then
cat runpoe.gempaksend.sh_in_cray | sed s:_CYC_:${cyc}:g | sed s:_NEST_:${NEST}:g > launch_gempaksend_${cyc}
chmod 775 launch_gempaksend_${cyc}

cat run_qpfclimo_bin.lsf_in_cray |  sed s:_CYC_:${CYC}:g | sed s:_DOM_:${dom}:g > run_qpfclimo_bin.lsf
cat run_qpfcalibrate_bin.lsf_in_cray |  sed s:_CYC_:${CYC}:g | sed s:_DOM_:${dom}:g > run_qpfcalibrate_bin.lsf
fi

if [ $dom = "conus" -o  $dom = "ak" ]
then
cat run_eas_bin.lsf_in_cray |  sed s:_CYC_:${CYC}:g | sed s:_DOM_:${dom}:g > run_eas_bin.lsf_${dom}
else
cat run_eas_bin.lsf_in_cray_small |  sed s:_CYC_:${CYC}:g | sed s:_DOM_:${dom}:g > run_eas_bin.lsf_${dom}
fi

if [ $dom = "conus" ]
then
bsub < run_qpfclimo_bin.lsf
else
bsub < run_eas_bin.lsf_${dom}
fi


## end EAS stuff

bsub < launch_hrefrunpoe_${cyc}

sleep 1200

bsub < launch_nawips_${cyc}_${dom}

sleep 1200

bsub < launch_awips_${cyc}_${dom}
bsub < launch_gempaksend_${cyc}_${dom}
