#! /bin/sh


if [ "$#" -ne 2 ]
then
echo wrong number of arguments
echo need cyc and NEST
exit
fi

cyc=$1
export NEST=${2}

cd /u/$USER    # cron does this for us - this is here just to be safe
. /etc/profile

if [ -a .profile ]; then
   . ./.profile
fi

if [ -a .bashrc ]; then
   . ./.bashrc
fi

echo cyc $cyc

module load prod_util
module load grib_util/1.0.3
module load prod_envir

export COMINhiresw=${COMROOT}/hiresw/prod/hiresw
export COMINnam=${COMROOTp2}/nam/prod/nam
export COMINhrrr=${COMROOTp2}/hrrr/prod/hrrr

vers=`cat ~/href_exp`

echo vers is $vers

DATE=`cat $COMROOT/date/t${cyc}z | cut -c7-14`

cd /gpfs/hps3/emc/meso/noscrub/Matthew.Pyle/git_repo/EMC_hrw/href.${vers}/launch_info/

cat runpoe.preprocv3.sh_in_cray | sed s:_CYC_:${cyc}:g | sed s:_NEST_:${NEST}:g > launch_hrefv3preprocpoe_${cyc}

if [ $NEST = "conus" ]
then
cat run_ffg_gen.sh_in_cray | sed s:_CYC_:${cyc}:g | sed s:_NEST_:${NEST}:g > launch_ffg_gen_${cyc}
bsub < launch_ffg_gen_${cyc}
fi

# bsub < launch_hrefpreprocgetpoe_${cyc}

# sleep 600

# look for FV3 output

if [ $NEST = "conus" ]

then

# COMINfv3=/gpfs/dell1/ptmp/Benjamin.Blake/com/fv3/prod/fv3
export COMINfv3=/gpfs/dell1/ptmp/Benjamin.Blake/com/fv3sar/prod/fv3
export COMINfv3=/gpfs/dell1/ptmp/Benjamin.Blake/com/fv3sar/para/fv3sar
export COMINfv3=/gpfs/dell1/ptmp/Benjamin.Blake/com/fv3cam/para/fv3sar
export COMINfv3=/gpfs/dell1/ptmp/emc.campara/com/fv3cam/para/fv3sar

looplim=200
loop=1

if [ $cyc -eq 00 ]
then

while [ $loop -le $looplim ]
do

if [ -e ${COMINfv3}.${DATE}/${cyc}/fv3sar.t${cyc}z.conus.f36.grib2 ]
then
echo found it
let loop=loop+200
else
echo still looking for ${COMINfv3}.${DATE}/${cyc}/fv3sar.t00z.conus.f36.grib2
date
sleep 90
let loop=loop+1
fi

done

fi


else # not conus


echo NOT CONUS BLOCK

export COMINfv3=/gpfs/dell1/ptmp/Matthew.Pyle/com/fv3cam/para/fv3sar

fi

echo here with COMINfv3 as $COMINfv3


bsub < launch_hrefv3preprocpoe_${cyc}
