#! /bin/ksh

cd  /gpfs/hps3/emc/meso/noscrub/Matthew.Pyle/git_repo/EMC_hrw/href.v3.0.0/launch_info

CYC=${1}
dom=${2}

if [ $dom = "conus" ]
then
cat run_qpfclimo.lsf_in |  sed s:_CYC_:${CYC}:g | sed s:_DOM_:${dom}:g  > run_qpfclimo.lsf
cat run_qpfclimo_bin.lsf_in |  sed s:_CYC_:${CYC}:g | sed s:_DOM_:${dom}:g > run_qpfclimo_bin.lsf
cat run_qpfcalibrate.lsf_in |  sed s:_CYC_:${CYC}:g | sed s:_DOM_:${dom}:g > run_qpfcalibrate.lsf
fi

cat run_eas.lsf_in |  sed s:_CYC_:${CYC}:g | sed s:_DOM_:${dom}:g > run_eas.lsf_${dom}


if [ $dom = "conus" ]
then
bsub < run_qpfclimo.lsf

elif [ $dom = "conusbin" ]
then
bsub < run_qpfclimo_bin.lsf

else

bsub < run_eas.lsf_${dom}

fi
