#! /bin/sh


if [ "$#" -ne 2 ]
then
echo wrong number of arguments
echo need cyc and NEST
exit
fi

cyc=$1
export NEST=${2}

cd /u/$USER    # cron does this for us - this is here just to be safe
. /etc/profile

if [ -a .profile ]; then
   . ./.profile
fi

if [ -a .bashrc ]; then
   . ./.bashrc
fi

echo cyc $cyc

module load prod_util
module load grib_util/1.0.3
module load prod_envir

export COMINhiresw=${COMROOT}/hiresw/prod/hiresw
export COMINnam=${COMROOTp2}/nam/prod/nam
export COMINhrrr=${COMROOTp2}/hrrr/prod/hrrr

vers=`cat ~/href_exp`

echo vers is $vers

DATE=`cat $COMROOT/date/t${cyc}z | cut -c7-14`

cd /gpfs/hps3/emc/meso/noscrub/Matthew.Pyle/href.${vers}/launch_info/

if [ $NEST = "conus" ]
then
cat runpoe.preprocget.sh_in_cray | sed s:_CYC_:${cyc}:g | sed s:_NEST_:${NEST}:g > launch_hrefpreprocgetpoe_${cyc}
cat runpoe.preproc.sh_in_cray | sed s:_CYC_:${cyc}:g | sed s:_NEST_:${NEST}:g > launch_hrefpreprocpoe_${cyc}
fi

bsub < launch_hrefpreprocgetpoe_${cyc}

sleep 600

bsub < launch_hrefpreprocpoe_${cyc}
