#! /bin/sh

cyc=$1
export NEST=$2

cd /u/$USER    # cron does this for us - this is here just to be safe
. /etc/profile

if [ -a .profile ]; then
   . ./.profile
fi

if [ -a .bashrc ]; then
   . ./.bashrc
fi

echo cyc $cyc

module load prod_util
module load grib_util/1.0.3
module load prod_envir

export COMINhiresw=${COMROOT}/hiresw/prod/hiresw
export COMINnam=${COMROOTp1}/nam/prod/nam
export COMINhrrr=${COMROOTp2}/hrrr/prod/hrrr

vers=`cat ~/href_exp`

echo vers is $vers

DATE=`cat $COMROOT/date/t${cyc}z | cut -c7-14`

cd /gpfs/hps3/emc/meso/noscrub/Matthew.Pyle/href.${vers}/launch_info/
# ../scripts/interp_conv.scr ${DATE}${cyc}

cat runpoe.sh_in_cray_inter | sed s:_CYC_:${cyc}:g | sed s:_NEST_:${NEST}:g  > launch_hrefrunpoe_${cyc}

# bsub < launch_hrefrunpoe_${cyc}

chmod u+x launch_hrefrunpoe_${cyc}

./launch_hrefrunpoe_${cyc}
