#! /bin/sh


if [ "$#" -ne 2 ]
then
echo wrong number of arguments
echo need cyc and NEST
exit
fi

cyc=$1
export NEST=${2}

cd /u/$USER    # cron does this for us - this is here just to be safe
. /etc/profile

if [ -a .profile ]; then
   . ./.profile
fi

if [ -a .bashrc ]; then
   . ./.bashrc
fi

echo cyc $cyc

module load prod_util
module load grib_util/1.0.3
module load prod_envir

export COMINhiresw=${COMROOT}/hiresw/prod/hiresw
export COMINnam=${COMROOTp2}/nam/prod/nam
export COMINhrrr=${COMROOTp2}/hrrr/prod/hrrr

vers=`cat ~/href_exp`

echo vers is $vers

DATE=`cat $COMROOT/date/t${cyc}z | cut -c7-14`

cd /gpfs/hps3/emc/meso/noscrub/Matthew.Pyle/git_repo/EMC_hrw/href.${vers}/launch_info/

if [ $NEST = "conus" -o $NEST = "ak" ]
then
# cat runpoe.preprocget.sh_in_cray | sed s:_CYC_:${cyc}:g | sed s:_NEST_:${NEST}:g > launch_hrefpreprocgetpoe_${cyc}
cat runpoe.preprocv3.sh_in_cray | sed s:_CYC_:${cyc}:g | sed s:_NEST_:${NEST}:g > launch_hrefv3preprocpoe_${cyc}
fi

# bsub < launch_hrefpreprocgetpoe_${cyc}

# sleep 600

# look for FV3 output

if [ -e /gpfs/gd1 ]
then
COMINfv3=/gpfs/gd1/ptmp/Benjamin.Blake/com/fv3/prod/fv3
else
COMINfv3=/gpfs/td1/ptmp/Benjamin.Blake/com/fv3/prod/fv3
fi

looplim=200
loop=1

while [ $loop -le $looplim ]
do

if [ -e ${COMINfv3}.${DATE}/fv3.t00z.conusf36.grib2 ]
then
echo found it
let loop=loop+200
else
echo still looking for ${COMINfv3}.${DATE}/fv3.t00z.conusf36.grib2
date
sleep 90
let loop=loop+1
fi

done

bsub < launch_hrefv3preprocpoe_${cyc}
