#BSUB -oo /gpfs/hps/emc/meso/noscrub/Matthew.Pyle/href.v2.0.0/logs/test_hrefpoegempak_12.out
#BSUB -eo /gpfs/hps/emc/meso/noscrub/Matthew.Pyle/href.v2.0.0/logs/test_hrefpoegempak_12.err
#BSUB -q "devhigh"
#BSUB -J HREF_NAWIPS12
#BSUB -P HRW-T2O
#BSUB -M 1000
#BSUB -cwd /gpfs/hps/emc/meso/noscrub/Matthew.Pyle/
#BSUB -W 0:10
#BSUB -extsched 'CRAYLINUX[]' -R '1*{select[craylinux && !vnode]} + 1*{select[craylinux && vnode]span[ptile=1] cu[type=cabinet]}' rusage[mem=3000]
#

export RUN_ENVIR=test
export envir=test
export SUB_ENVIR=dev
export cyc=12
export NEST=hi

export DATAROOT=/gpfs/hps/stmp/Matthew.Pyle/tmpnwprd
export COMROOT=/gpfs/tp2/nco/ops/com/
export MYCOMROOT=/gpfs/hps/ptmp/Matthew.Pyle/com

module load grib_util
module load prod_util

href_ver=`cat /u/$LOGNAME/href_para`

export HOMEhref=/gpfs/hps/emc/meso/noscrub/Matthew.Pyle/href.${href_ver}

export SENDCOM=YES

${HOMEhref}/jobs/JHREF_GEMPAK
