#!/bin/sh

#############################################################
# HREF RUNALL 
# 02/02/2015 Binbin Zhou, create for run all scripts 
#############################################################

########################################
# Preliminary data setup step
########################################

set -xa
export PS4='$SECONDS + ' 
date

###################################
# Specify NET and RUN Name and model
####################################
export NET=${NET:-hiresw}
export RUN=${RUN:-href}

export IOBUF_PARAMS='*:size=8M:count=8'

###############################################################
# This block can be modified for different Production test
# environment. This is used for operational testings
###############################################################

## PDY not included here as pull data from PDYm1 as well

# export COMINhiresw=${COMINhiresw:-${COMROOT}/${NET}/prod/hiresw}
# export COMINnam=${COMINnam:-${COMROOTp1}/nam/prod/nam}

export HOMEhref=${HOMEhref:-$NWROOT/href.${href_ver}} 
export EXEChref=${EXEChref:-$HOMEhref/exec}
export PARMhref=${PARMhref:-$HOMEhref/parm}
export USHhref=${USHhref:-$HOMEhref/ush}
export FIXhref=${FIXhref:-$HOMEhref/fix}
export SCRIPTShref=${SCRIPTShref:-$HOMEhref/scripts}

###########################################################
# obtain unique process id (pid) and make temp directories
###########################################################

export pid=$$
export DATA=${DATA:-${DATAROOT}/href_ensprod_${cyc}_${envir}.${pid}}
mkdir -p $DATA
rm -rf $DATA/*
cd $DATA

####################################
# File To Log Msgs
####################################
export jlogfile=${jlogfile:-$COMROOT/logs/jlogfile}

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"

export cycle=${cycle:-t${cyc}z}

##################################################
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
##################################################

export SENDCOM=${SENDCOM:-YES}
export SENDECF=${SENDECF:-YES}
export SENDDBN=${SENDDBN:-YES}

###################################
# Set up the UTILITIES
###################################

msg="JOB $job HAS BEGUN"
postmsg "$jlogfile" "$msg"

#
# Run setpdy and initialize PDY variables
#

setpdy.sh
. PDY

# export PDY=20160203
# export PDYm1=20160202

##############################################
# Define running directory and COM directories
##############################################

if [ "$RUN_ENVIR" != nco ] ; then
  export COMOUT=${MYCOMROOT}/${NET}/${envir}/${RUN}.${PDY}_awips2
  export COMOUTPERM=${MYCOMROOTPERM}/${NET}/${envir}/${RUN}.${PDY}_awips2
else
  export COMOUT=${COMOUT:-${COMROOT}/${NET}/${envir}/${RUN}.${PDY}}
fi

# env

if [ ! -d $COMOUT ] ; then 
 mkdir -p $COMOUT
fi

if [ ! -d $COMOUTPERM ] ; then 
 mkdir -p $COMOUTPERM
fi

#######################################################
# Pass information which is needed to run the Script
#######################################################

# export VERBOSE=YES

###################################################
# Execute the Script exhref_ensprod.sh.ecf

rm -rf poe.*

$SCRIPTShref/exhref_ensprod_link.sh.ecf 01
# $SCRIPTShref/exhref_ensprod_link.sh.ecf 02
# $SCRIPTShref/exhref_ensprod_link.sh.ecf 03
# $SCRIPTShref/exhref_ensprod_link.sh.ecf 04
# $SCRIPTShref/exhref_ensprod_link.sh.ecf 05
# $SCRIPTShref/exhref_ensprod_link.sh.ecf 06
# $SCRIPTShref/exhref_ensprod_link.sh.ecf 07
# $SCRIPTShref/exhref_ensprod_link.sh.ecf 08
# $SCRIPTShref/exhref_ensprod_link.sh.ecf 09
# $SCRIPTShref/exhref_ensprod_link.sh.ecf 10
# $SCRIPTShref/exhref_ensprod_link.sh.ecf 11
# $SCRIPTShref/exhref_ensprod_link.sh.ecf 12
# $SCRIPTShref/exhref_ensprod_link.sh.ecf 13


$SCRIPTShref/exhref_ensprod.sh.ecf 01
# $SCRIPTShref/exhref_ensprod.sh.ecf 02
# $SCRIPTShref/exhref_ensprod.sh.ecf 03
# $SCRIPTShref/exhref_ensprod.sh.ecf 04
# $SCRIPTShref/exhref_ensprod.sh.ecf 05
# $SCRIPTShref/exhref_ensprod.sh.ecf 06


msg"JOB $job HAS COMPLETED NORMALLY."
postmsg "$jlogfile" "$msg"
date

# cd $DATAROOT
# if [ $KEEPDATA = NO ]; then rm -rf $DATA; fi
# date
