#!/bin/sh

#############################################################
# HREF RUNALL 
# 02/02/2015 Binbin Zhou, create for run all scripts 
#############################################################

########################################
# Preliminary data setup step
########################################

set -xa
export PS4='$SECONDS + ' 
date

###################################
# Specify NET and RUN Name and model
####################################
export NET=${NET:-hiresw}
export RUN=${RUN:-href}

export IOBUF_PARAMS='*:size=8M:count=8'

###############################################################
# This block can be modified for different Production test
# environment. This is used for operational testings
###############################################################

## PDY not included here as pull data from PDYm1 as well

# export COMINhiresw=${COMINhiresw:-${COMROOT}/${NET}/prod/hiresw}
# export COMINnam=${COMINnam:-${COMROOTp1}/nam/prod/nam}

export HOMEhref=${HOMEhref:-$NWROOT/href.${href_ver}} 
export EXEChref=${EXEChref:-$HOMEhref/exec}
export PARMhref=${PARMhref:-$HOMEhref/parm}
export PARMutil=${PARMutil:-$HOMEhref/util/parm}
export USHhref=${USHhref:-$HOMEhref/ush}
export FIXhref=${FIXhref:-$HOMEhref/fix}
export SCRIPTShref=${SCRIPTShref:-$HOMEhref/scripts}

###########################################################
# obtain unique process id (pid) and make temp directories
###########################################################

export pid=$$
export DATA=${DATA:-${DATAROOT}/href_ensprod_${cyc}_${envir}.${pid}}
mkdir -p $DATA
rm -rf $DATA/*
cd $DATA

####################################
# File To Log Msgs
####################################
export jlogfile=${jlogfile:-$COMROOT/logs/jlogfile}

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"

export cycle=${cycle:-t${cyc}z}

##################################################
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
##################################################

export SENDCOM=${SENDCOM:-YES}
export SENDECF=${SENDECF:-YES}
export SENDDBN=${SENDDBN:-YES}

###################################
# Set up the UTILITIES
###################################

msg="JOB $job HAS BEGUN"
postmsg "$jlogfile" "$msg"

#
# Run setpdy and initialize PDY variables
#

setpdy.sh
. PDY

# export PDY=20160203
# export PDYm1=20160202

##############################################
# Define running directory and COM directories
##############################################

if [ "$RUN_ENVIR" != nco ] ; then
  export COMOUT=${MYCOMROOT}/${NET}/${envir}/${RUN}.${PDY}
  export COMOUTPERM=${MYCOMROOTPERM}/${NET}/${envir}/${RUN}.${PDY}
else
  export COMOUT=${COMOUT:-${COMROOT}/${NET}/${envir}/${RUN}.${PDY}}
fi

# env

if [ ! -d $COMOUT ] ; then 
 mkdir -p $COMOUT
fi

if [ ! -d $COMOUTPERM ] ; then 
 mkdir -p $COMOUTPERM
fi

#######################################################
# Pass information which is needed to run the Script
#######################################################

# export VERBOSE=YES

###################################################
# Execute the Script exhref_ensprod.sh.ecf

rm -rf poe.*

echo "#!/bin/sh  "                             >  poe.aa
echo "$SCRIPTShref/exhref_ensprod_link.sh.ecf 01 &" >> poe.aa
echo "$SCRIPTShref/exhref_ensprod_link.sh.ecf 02 &" >> poe.aa
echo "$SCRIPTShref/exhref_ensprod_link.sh.ecf 03 &" >> poe.aa
echo "$SCRIPTShref/exhref_ensprod_link.sh.ecf 04 &" >> poe.aa
echo "$SCRIPTShref/exhref_ensprod_link.sh.ecf 05 &" >> poe.aa
echo "$SCRIPTShref/exhref_ensprod_link.sh.ecf 06 &" >> poe.aa
echo "wait" >> poe.aa

echo "#!/bin/sh  "                             >  poe.bb
echo "$SCRIPTShref/exhref_ensprod_link.sh.ecf 07 &" >> poe.bb
echo "$SCRIPTShref/exhref_ensprod_link.sh.ecf 08 &" >> poe.bb
echo "$SCRIPTShref/exhref_ensprod_link.sh.ecf 09 &" >> poe.bb
echo "$SCRIPTShref/exhref_ensprod_link.sh.ecf 10 &" >> poe.bb
echo "$SCRIPTShref/exhref_ensprod_link.sh.ecf 11 &" >> poe.bb
echo "$SCRIPTShref/exhref_ensprod_link.sh.ecf 12 &" >> poe.bb
echo "wait" >> poe.bb

echo "#!/bin/sh  "                             >  poe.cc
echo "$SCRIPTShref/exhref_ensprod_link.sh.ecf 13 &" >> poe.cc
echo "$SCRIPTShref/exhref_ensprod_link.sh.ecf 14 &" >> poe.cc
echo "$SCRIPTShref/exhref_ensprod_link.sh.ecf 15 &" >> poe.cc
echo "$SCRIPTShref/exhref_ensprod_link.sh.ecf 16 &" >> poe.cc
echo "$SCRIPTShref/exhref_ensprod_link.sh.ecf 17 &" >> poe.cc
echo "$SCRIPTShref/exhref_ensprod_link.sh.ecf 18 &" >> poe.cc
echo "wait" >> poe.cc

echo "#!/bin/sh  "                             >  poe.dd
echo "$SCRIPTShref/exhref_ensprod_link.sh.ecf 19 &" >> poe.dd
echo "$SCRIPTShref/exhref_ensprod_link.sh.ecf 20 &" >> poe.dd
echo "$SCRIPTShref/exhref_ensprod_link.sh.ecf 21 &" >> poe.dd
echo "$SCRIPTShref/exhref_ensprod_link.sh.ecf 22 &" >> poe.dd
echo "$SCRIPTShref/exhref_ensprod_link.sh.ecf 23 &" >> poe.dd
echo "$SCRIPTShref/exhref_ensprod_link.sh.ecf 24 &" >> poe.dd
echo "wait" >> poe.dd

echo "#!/bin/sh  "                             >  poe.ee
echo "$SCRIPTShref/exhref_ensprod_link.sh.ecf 25 &" >> poe.ee
echo "$SCRIPTShref/exhref_ensprod_link.sh.ecf 26 &" >> poe.ee
echo "$SCRIPTShref/exhref_ensprod_link.sh.ecf 27 &" >> poe.ee
echo "$SCRIPTShref/exhref_ensprod_link.sh.ecf 28 &" >> poe.ee
echo "$SCRIPTShref/exhref_ensprod_link.sh.ecf 29 &" >> poe.ee
echo "$SCRIPTShref/exhref_ensprod_link.sh.ecf 30 &" >> poe.ee
echo "wait" >> poe.ee

echo "#!/bin/sh  "                             >  poe.ff
echo "$SCRIPTShref/exhref_ensprod_link.sh.ecf 31 &" >> poe.ff
echo "$SCRIPTShref/exhref_ensprod_link.sh.ecf 32 &" >> poe.ff
echo "$SCRIPTShref/exhref_ensprod_link.sh.ecf 33 &" >> poe.ff
echo "$SCRIPTShref/exhref_ensprod_link.sh.ecf 34 &" >> poe.ff
echo "$SCRIPTShref/exhref_ensprod_link.sh.ecf 35 &" >> poe.ff
echo "$SCRIPTShref/exhref_ensprod_link.sh.ecf 36 &" >> poe.ff
echo "wait" >> poe.ff

echo "#!/bin/sh  "                             >  poe.a
echo "$SCRIPTShref/exhref_ensprod.sh.ecf 01 &" >> poe.a
echo "$SCRIPTShref/exhref_ensprod.sh.ecf 02 &" >> poe.a
echo "$SCRIPTShref/exhref_ensprod.sh.ecf 03 &" >> poe.a
echo "$SCRIPTShref/exhref_ensprod.sh.ecf 04 &" >> poe.a
echo "$SCRIPTShref/exhref_ensprod.sh.ecf 05 &" >> poe.a
echo "$SCRIPTShref/exhref_ensprod.sh.ecf 06 &" >> poe.a
echo "wait"                                    >> poe.a

echo "#!/bin/sh  "                             >  poe.b
echo "$SCRIPTShref/exhref_ensprod.sh.ecf 07 &" >> poe.b
echo "$SCRIPTShref/exhref_ensprod.sh.ecf 08 &" >> poe.b
echo "$SCRIPTShref/exhref_ensprod.sh.ecf 09 &" >> poe.b
echo "$SCRIPTShref/exhref_ensprod.sh.ecf 10 &" >> poe.b
echo "$SCRIPTShref/exhref_ensprod.sh.ecf 11 &" >> poe.b
echo "$SCRIPTShref/exhref_ensprod.sh.ecf 12 &" >> poe.b
echo "wait"                                    >> poe.b

echo "#!/bin/sh  "                             >  poe.c
echo "$SCRIPTShref/exhref_ensprod.sh.ecf 13 &" >> poe.c
echo "$SCRIPTShref/exhref_ensprod.sh.ecf 14 &" >> poe.c
echo "$SCRIPTShref/exhref_ensprod.sh.ecf 15 &" >> poe.c
echo "$SCRIPTShref/exhref_ensprod.sh.ecf 16 &" >> poe.c
echo "$SCRIPTShref/exhref_ensprod.sh.ecf 17 &" >> poe.c
echo "$SCRIPTShref/exhref_ensprod.sh.ecf 18 &" >> poe.c
echo "wait"                                    >> poe.c

echo "#!/bin/sh  "                             >  poe.d
echo "$SCRIPTShref/exhref_ensprod.sh.ecf 19 &" >> poe.d
echo "$SCRIPTShref/exhref_ensprod.sh.ecf 20 &" >> poe.d
echo "$SCRIPTShref/exhref_ensprod.sh.ecf 21 &" >> poe.d
echo "$SCRIPTShref/exhref_ensprod.sh.ecf 22 &" >> poe.d
echo "$SCRIPTShref/exhref_ensprod.sh.ecf 23 &" >> poe.d
echo "$SCRIPTShref/exhref_ensprod.sh.ecf 24 &" >> poe.d
echo "wait"                                    >> poe.d

echo "#!/bin/sh  "                             >  poe.e
echo "$SCRIPTShref/exhref_ensprod.sh.ecf 25 &" >> poe.e
echo "$SCRIPTShref/exhref_ensprod.sh.ecf 26 &" >> poe.e
echo "$SCRIPTShref/exhref_ensprod.sh.ecf 27 &" >> poe.e
echo "$SCRIPTShref/exhref_ensprod.sh.ecf 28 &" >> poe.e
echo "$SCRIPTShref/exhref_ensprod.sh.ecf 29 &" >> poe.e
echo "$SCRIPTShref/exhref_ensprod.sh.ecf 30 &" >> poe.e
echo "wait"                                    >> poe.e

echo "#!/bin/sh  "                             >  poe.f
echo "$SCRIPTShref/exhref_ensprod.sh.ecf 31 &" >> poe.f
echo "$SCRIPTShref/exhref_ensprod.sh.ecf 32 &" >> poe.f
echo "$SCRIPTShref/exhref_ensprod.sh.ecf 33 &" >> poe.f
echo "$SCRIPTShref/exhref_ensprod.sh.ecf 34 &" >> poe.f
echo "$SCRIPTShref/exhref_ensprod.sh.ecf 35 &" >> poe.f
echo "$SCRIPTShref/exhref_ensprod.sh.ecf 36 &" >> poe.f
echo "wait"                                    >> poe.f


chmod 775 ${DATA}/poe.aa  ${DATA}/poe.bb ${DATA}/poe.cc
chmod 775 ${DATA}/poe.dd  ${DATA}/poe.ee ${DATA}/poe.ff

chmod 775 ${DATA}/poe.a ${DATA}/poe.b ${DATA}/poe.c
chmod 775 ${DATA}/poe.d  ${DATA}/poe.e ${DATA}/poe.f

aprun -n 1 -N 1 -d 6 ${DATA}/poe.aa &
aprun -n 1 -N 1 -d 6 ${DATA}/poe.bb &
aprun -n 1 -N 1 -d 6 ${DATA}/poe.cc &
aprun -n 1 -N 1 -d 6 ${DATA}/poe.dd &
aprun -n 1 -N 1 -d 6 ${DATA}/poe.ee &
aprun -n 1 -N 1 -d 6 ${DATA}/poe.ff &
wait
export err=$?; err_chk

aprun -n 1 -N 1 -d 6 ${DATA}/poe.a &
aprun -n 1 -N 1 -d 6 ${DATA}/poe.b &
aprun -n 1 -N 1 -d 6 ${DATA}/poe.c &
aprun -n 1 -N 1 -d 6 ${DATA}/poe.d &
aprun -n 1 -N 1 -d 6 ${DATA}/poe.e &
aprun -n 1 -N 1 -d 6 ${DATA}/poe.f &
wait
export err=$?; err_chk

msg"JOB $job HAS COMPLETED NORMALLY."
postmsg "$jlogfile" "$msg"
date

cd $DATAROOT
if [ $KEEPDATA = NO ]; then rm -rf $DATA; fi
date
