#! /bin/sh


cd ${DATAROOT}

pwd

ls

echo domain is $domain
echo cyc is $cyc

dom=$NEST


rm -rf ./refs_qpfeasfrac_timelag_singlephys_${dom}_${cyc}_para_??

rm -rf ./refs_awips_timelag_singlephys_${dom}_${cyc}_para 
rm -rf ./refs_ensprodpreprocfv3_timelag_singlephys_${dom}_${cyc}_para
rm -rf ./refs_ensprod_timelag_singlephys_${dom}_${cyc}_para
rm -rf ./refs_gempak_timelag_singlephys_${dom}_${cyc}_para

