#! /bin/sh


cd ${DATAROOT}

pwd

ls

echo domain is $domain
echo cyc is $cyc

dom=$NEST


rm -rf ./refs_qpfeasfrac_${dom}_${cyc}_para_??.*

rm -rf ./refs_awips_${dom}_${cyc}_para.*
rm -rf ./refs_preprocfv3_${dom}_${cyc}_para_??.*
rm -rf ./refs_ensprod_${dom}_${cyc}_para
rm -rf ./refs_gempak_${dom}_${cyc}_para.*

if [ $dom = "conus" ]
then
rm -rf refs_ffggen_${dom}_${cyc}_para.*
rm -rf refs_preprochrrr_${dom}_${cyc}_para.*
fi

if [ $dom = "ak" ]
then
rm -rf refs_preprochrrr_${dom}_${cyc}_para.*
fi
