#!/bin/bash

module purge
module load envvar/1.0
module load prod_util/2.0.10

set -x

CURRENTDATE=$PDY$cyc

mysite=$(cat /etc/cluster_name)
primary=$(head -1 /lfs/h1/ops/prod/config/prodmachinefile | cut -d ":" -f2-)
backup=$(head -2 /lfs/h1/ops/prod/config/prodmachinefile | tail -1 | cut -d ":" -f2-)

if [ "$primary" == "cactus" ]; then
  desmachine=emc.lam@ddxfer.wcoss2.ncep.noaa.gov
else
  desmachine=emc.lam@cdxfer.wcoss2.ncep.noaa.gov
fi

#for hourback  in 1 2 3 4 5 6

indx="00 06 12 18"

for hourback in 0 2 4 6 8 10 12
do
  #YYYYMMDDHH=`date +"%Y%m%d%H" -d "${CURRENTDATE} ${minsback} minute ago"`
  #currentdate=`date +"%Y%m%d %H"`
  YYYYMMDDHH=`$NDATE -$hourback $CURRENTDATE`

  PDY=`echo ${YYYYMMDDHH} | cut -c1-8`
  cyc=`echo ${YYYYMMDDHH} | cut -c9-10`

  for i in $indx
  do
   if [ "$cyc" == $i ]; then
   proddir_enspost_sinphys_tl=/lfs/h2/emc/ptmp/emc.lam/para/com/refs/v1.0/refs.${PDY}
   proddir_enspost_mphys_tl=/lfs/h2/emc/ptmp/emc.lam/testmp/com/refs/v1.0/refs.${PDY}
   proddir_enspost_sinphys_tl_nwges=/lfs/h2/emc/ptmp/emc.lam/para/com/refs/v1.0/nwges/refs.${PDY}


nwges_hrs="00 03 06 09 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60"

# single phys, timelag
     destination_refs=$proddir_enspost_sinphys_tl
     destination_nwges=$proddir_enspost_sinphys_tl_nwges
     proddir_refs=$destination_refs
     destination_refs_cyc=$destination_refs/ensprod
     destination_refs_cyc_g2g=$destination_refs/verf_g2g

     ssh $desmachine "mkdir -p $destination_refs_cyc"
     touch $proddir_refs/dummy
     rsync -aq $proddir_refs/dummy $desmachine:$destination_refs/
     rsync -aq $proddir_refs/dummy $desmachine:$destination_refs_cyc/
     rsync -aq $proddir_refs/dummy $desmachine:$destination_refs_cyc_g2g/
     rsync -aq $proddir_refs/dummy $desmachine:$destination_nwges/
     rsync -arv $destination_refs_cyc/refs.t${cyc}z.*   $desmachine:$destination_refs_cyc/
     rsync -av $proddir_refs/refs.t${cyc}z.*   $desmachine:$destination_refs/
     rsync -arv $destination_refs_cyc_g2g/*   $desmachine:$destination_refs_cyc_g2g/

     for hr in $nwges_hrs
do
     rsync -arv $destination_nwges/fv3s.t${cyc}z.*.m??.f${hr}.grib2  $desmachine:$destination_nwges
     rsync -arv $destination_nwges/hrrr.t${cyc}z.*.f${hr}.grib2  $desmachine:$destination_nwges
done
   fi
  done

done

exit
