#!/bin/bash
set -x

export RUN=rrfs_a

# If the data directory does not exist, then stop the job
export DATA=/lfs/h2/emc/ptmp/emc.lam/testmp/com/rrfs/v1.0/rrfs.${PDY}/timelag/ensprod/

if [ -d $DATA ]; then
  echo "Run directory exists, transferring data inside of it"
  cd $DATA
else
  echo "WARNING: Run directory does not exist, check real-time parallel"
  exit
fi

export pid=$$
export pgmout="OUTPUT.${pid}"

. /lfs/h2/emc/lam/noscrub/Benjamin.Blake/key.bdp

# Copy the bufr sounding file to AWS

types="prob avrg eas ffri lpmm mean pmmn sprd"

for typ in $types
do

posthr=01
while [ $posthr -le 60 ] ; do

  aws s3 cp rrfs.t${cyc}z.conus.${typ}.f${posthr}.grib2  s3://noaa-rrfs-pds/rrfs_a/rrfs_a.${PDY}/${cyc}/multi_physics/enspost_timelag/
  aws s3 cp rrfs.t${cyc}z.conus.${typ}.f${posthr}.grib2.idx  s3://noaa-rrfs-pds/rrfs_a/rrfs_a.${PDY}/${cyc}/multi_physics/enspost_timelag/

  let "posthr=$(( ${posthr#0} + 1 ))"
  if [ $posthr -le 10 ] ; then
    posthr=$(printf "%02d" $posthr)
  fi
done

done


if [ $cyc -eq 00 -o $cyc -eq 06 -o $cyc -eq 12 -o $cyc -eq 18 ]; then
  cd /lfs/h2/emc/ptmp/Benjamin.Blake/logfiles
  echo "I am done" > donefile.enspostaws.${CDATE}
  aws s3 cp donefile.enspostaws.${CDATE} s3://noaa-rrfs-pds/rrfs_a/rrfs_a.${PDY}/multi_physics/enspost_timelag/
fi

date

exit
