#!/bin/bash
set -x

export RUN=rrfs_a

# If the data directory does not exist, then stop the job
export DATA=/lfs/h2/emc/ptmp/emc.lam/para/com/refs/v1.0/refs.${PDY}/ensprod/

if [ -d $DATA ]; then
  echo "Run directory exists, transferring data inside of it"
  cd $DATA
else
  echo "WARNING: Run directory does not exist, check real-time parallel"
  exit
fi

export pid=$$
export pgmout="OUTPUT.${pid}"

. /lfs/h2/emc/lam/noscrub/Benjamin.Blake/key.bdp

types="prob avrg eas ffri lpmm mean pmmn sprd"

aws s3 cp ./ s3://noaa-rrfs-pds/rrfs_a/rrfs_a.${PDY}/${cyc}/enspost_timelag/ --recursive --exclude "*" --include "refs.t${cyc}z.*.grib2*"


if [ $cyc -eq 00 -o $cyc -eq 06 -o $cyc -eq 12 -o $cyc -eq 18 ]; then
  echo "I am done" > donefile.enspostaws.${CDATE}
  aws s3 cp donefile.enspostaws.${CDATE} s3://noaa-rrfs-pds/rrfs_a/rrfs_a.${PDY}/enspost_timelag/
fi

date

exit
