#!/bin/bash
set -x

export RUN=rrfs_a

dom=${DOM}

ff=${fhr}

primary=$(head -1 /lfs/h1/ops/prod/config/prodmachinefile | cut -d ":" -f2-)

# If the data directory does not exist, then stop the job
export DATA=/lfs/h2/emc/ptmp/emc.lam/para/com/refs/v1.0/refs.${PDY}/ensprod/
export DATASNOW=/lfs/h2/emc/ptmp/emc.lam/para/com/refs/v1.2/refs.${PDY}/ensprod/

if [ "$primary" == "cactus" ]; then
  desmachine=emc.lam@ddxfer.wcoss2.ncep.noaa.gov
else
  desmachine=emc.lam@cdxfer.wcoss2.ncep.noaa.gov
fi


if [ -d $DATA ]; then
  echo "Run directory exists, transferring data inside of it"
  cd $DATA
else
  echo "WARNING: Run directory does not exist, check real-time parallel"
  exit
fi

export pid=$$
export pgmout="OUTPUT.${pid}"

. /lfs/h2/emc/lam/noscrub/Benjamin.Blake/key.bdp

types="prob avrg eas ffri lpmm mean pmmn sprd"

echo "[DEBUG] Attempting upload for PDY=${PDY}, cyc=${cyc}, dom=${dom}, ff=${ff}"

MATCHING_FILES=$(ls -1 refs.t${cyc}z.${dom}.*.f${ff}.grib2* 2>/dev/null | wc -l)
echo "[DEBUG] Found $MATCHING_FILES files matching the pattern."

if [ "$MATCHING_FILES" -eq 0 ]; then
    echo "[WARNING] No files found for cycle ${cyc}! AWS CLI will skip this silently."
    exit 99
fi

aws s3 cp ./ s3://noaa-rrfs-pds/rrfs_a/refs.${PDY}/${cyc}/enspost_timelag/ --recursive --exclude "*" --include "refs.t${cyc}z.${dom}.*.f${ff}.grib2*"

# add an rsync here as well?

# rsync -arv "refs.t${cyc}z.${dom}.*.f${ff}.grib2*" ${desmachine}:/lfs/h2/emc/ptmp/emc.lam/para/com/refs/v1.0/refs.${PDY}/ensprod/

# if [ -d $DATASNOW ]; then
# cd $DATASNOW

# aws s3 cp ./ s3://noaa-rrfs-pds/rrfs_a/refs.${PDY}/${cyc}/enspost_timelag/ --recursive --exclude "*" --include "refs.t${cyc}z.*snow*.grib2*"

# else
# echo "WARNING: no snow data"
# exit
# fi


# if [ $cyc -eq 00 -o $cyc -eq 06 -o $cyc -eq 12 -o $cyc -eq 18 ]; then
#   echo "I am done" > donefile.enspostaws.${CDATE}
#   aws s3 cp donefile.enspostaws.${CDATE} s3://noaa-rrfs-pds/rrfs_a/refs.${PDY}/enspost_timelag/
# fi

date

exit
