#!/bin/sh

########################################
# Runs HIRESW WRFBUFR and SNDP programs
########################################

set -xa

ecflow_client -init=${ECF_RID}

export PS4='$SECONDS + ' 
date

# 
# obtain unique process id (pid) and make temp directories
#
export pid=$$
export DATA=/tmpnwprd/hiresw_${NEST}_${MODEL}_${MEMBER}_${cyc}_${envir}

mkdir -p $DATA/smartinit
cd $DATA/smartinit
rm $DATA/smartinit/*

####################################
# File To Log Msgs
####################################
export jlogfile=/com/logs/jlogfile

####################################
# Determine Job Output Name on System
####################################

export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"

export cycle=t${cyc}z 

###############################
# Specify NET and RUN name
###############################

export NET=hiresw
export RUN=${NEST}${MODEL}

###############################

export SENDCOM=YES
export SENDDBN=YES
export SENDSMS=YES

export HOMEhiresw=/meso/save/Matthew.Pyle/hiresw_vert
export EXEChiresw=$HOMEhiresw/exec
export FIXhiresw=$HOMEhiresw/fix
export PARMhiresw=$HOMEhiresw/parm
export USHhiresw=$HOMEhiresw/ush


###################################
# Set up the UTILITIES
###################################

export utilscript=/nwprod/util/ush
export utilexec=/nwprod/util/exec

hrs="00 03 06 09 12 15 18 21 24 27 30 33 36 39 42 45 48"
for hr in $hrs
do
mkdir -p $DATA/smartinit_${hr}
cd $DATA/smartinit_${hr}
rm $DATA/smartinit_${hr}/*

# Run setup to initialize working directory and utility scripts
sh $utilscript/setup.sh

# Run setpdy and initialize PDY variables
sh $utilscript/setpdy.sh
. PDY

done

export COMROOT=/com
export com=/com/${NET}/${envir}
export COMIN=/com/${NET}/${envir}/hiresw.${PDY}
export COMOUT=/com/${NET}/${envir}/hiresw.${PDY}

mkdir -p $COMOUT

let srefcyc=$cyc-3
if [ $srefcyc -lt 0 ] ; then
  let srefcyc=$srefcyc+24
  export SREF_PDY=$PDYm1
else
  export SREF_PDY=$PDY
fi

let gefscyc=$cyc-6
if [ $gefscyc -lt 0 ] ; then
  let gefscyc=$gefscyc+24
  export GEFS_PDY=$PDYm1
else
  export GEFS_PDY=$PDY
fi

export srefcyc
let srefcyc2=$srefcyc

export gefscyc
let gefscyc2=$gefscyc

if [ $srefcyc2 -lt 10 ];then srefcyc2="0"${srefcyc2};fi
if [ $gefscyc2 -lt 10 ];then gefscyc2="0"${gefscyc2};fi

export COM_SREF=${COM_SREF:-/com/sref/prod}
export COMIN_SREF=$COM_SREF/sref.${SREF_PDY}/${srefcyc2}/ensprod
export COMIN_GEFS=$COM_SREF/sref.${GEFS_PDY}/ensprod_gefs

########################################################
# Execute the script.
$HOMEhiresw/scripts/exhiresw_smartinit.sh.ecf
########################################################

date

ecflow_client --complete


