#!/bin/ksh

set -xa
# #### 08/25/1999 ###################
# SET SHELL PROCESSING VARIABLES
# ###################################
export PS4='$SECONDS + ' 
date

##############################
# Get the NEST for this run
##############################
#export NEST=${NEST:-`grep t${cyc}z /nw${envir}/fix/hiresw_nesttimes | awk '{print $2}'`}

###########################################################
# obtain unique process id (pid) and make temp directories
###########################################################
export pid=$$
export DATA=/tmpnwprd/${job}.${pid}
mkdir $DATA
cd $DATA 

####################################
# File To Log Msgs
####################################
export jlogfile=/com/logs/jlogfiles/jlogfile.${job}.${pid}

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"

export cycle=t${cyc}z 

###############################
# Specify NET and RUN name
###############################
export NET=hiresw
export RUN=hiresw

##################################################
# SAVEGES  - Copy Files From TMPDIR to $GESdir
# SENDECF  - Flag Events on ecFLOW
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
# RERUN    - Rerun fcst from beginning (default no)
##################################################
export SENDCOM=YES
export SENDECF=YES
export SENDDBN=YES

export HOMEhiresw=/nw${envir}/hiresw.${model_ver}
export GEMPAKhiresw=$HOMEhiresw/gempak

export finc=1
export fend=48

export fstart=00
export model=${NEST}${MODEL}

if [ $NEST = "conus" ]
then
export GRIB=awp5km
else
export GRIB=awpreg
fi

export EXT=
export DBN_ALERT_TYPE=HIRESW_GEMPAK

#
# Copy model specific GEMPAK tables into working directory
#
cp $GEMPAKhiresw/fix/*.tbl .

#
# Now set up GEMPAK/NTRANS environment
#
. /nwprod/gempak/.gempak

###################################
# Set up the UTILITIES
###################################
export utilscript=/nwprod/util/ush
export utilities=/nwprod/util/ush
export utilexec=/nwprod/util/exec

# Run setup to initialize working directory and utility scripts
sh $utilscript/setup.sh

# Run setpdy and initialize PDY variables
sh $utilscript/setpdy.sh
. PDY

export com=/com/${NET}/${envir}
export COMIN=/com/${NET}/${envir}/hiresw.${PDY}
export COMOUT=/com/nawips/${envir}/hiresw.${PDY}

if [ ! -f $COMOUT ] ; then
  mkdir -p -m 775 $COMOUT
fi
 
env

#################################################################
# Execute the script to make the 10 km GEMPAK grids
$HOMEhiresw/scripts/exnawips_hiresw.sh.ecf
#################################################################

cd /tmpnwprd
rm -rf $DATA

date
