#!/bin/sh

########################################
# Runs HIRESW WRFBUFR and SNDP programs
########################################

set -xa

ecflow_client -init=${ECF_RID}

export PS4='$SECONDS + ' 
date

# 
# obtain unique process id (pid) and make temp directories
#
export pid=$$
export DATA=/tmpnwprd/hiresw_${NEST}_${MODEL}_${MEMBER}_${cyc}_${envir}

mkdir -p $DATA/bufrpost
cd $DATA/bufrpost 
rm $DATA/bufrpost/*
rm $DATA/profilm.c1.tm00*

####################################
# File To Log Msgs
####################################
export jlogfile=/com/logs/jlogfile

####################################
# Determine Job Output Name on System
####################################

export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"

export cycle=t${cyc}z 

###############################
# Specify NET and RUN name
###############################

export NET=hiresw
export RUN=${NEST}${MODEL}

###############################

export SENDCOM=YES
export SENDDBN=YES
export SENDECF=YES

export HOMEhiresw=/nw${envir}/hiresw_v6.0.0
export EXEChiresw=$HOMEhiresw/exec
export FIXhiresw=$HOMEhiresw/fix
export PARMhiresw=$HOMEhiresw/parm
export USHhiresw=$HOMEhiresw/ush


###################################
# Set up the UTILITIES
###################################

export utilscript=/nwprod/util/ush
export utilexec=/nwprod/util/exec

# Run setup to initialize working directory and utility scripts
sh $utilscript/setup.sh

# Run setpdy and initialize PDY variables
sh $utilscript/setpdy.sh

. PDY

export com=/com/${NET}/${envir}
export COMIN=/com/${NET}/${envir}/hiresw.${PDY}
export COMOUT=/com/${NET}/${envir}/hiresw.${PDY}

mkdir -p $COMOUT

### - do we want to add something to generate GEMPAK files on the fly?

# #######################################
# # Define the OUTPUT directory for the 
# # bufr->gempak files
# #######################################
# export COMAWP=/com/nawips/${envir}/${RUN}.${PDY}

########################################################
# Execute the script.
$HOMEhiresw/scripts/exhiresw_wrfbufr.sh.ecf
########################################################

ecflow_client --complete

date

