#!/bin/sh

########################################
# RUNS HIRESW POST JOB
########################################

set -xa

ecflow -init=${ECF_RID}

export PS4='$SECONDS + ' 
date

############################################################# 
# obtain unique process id (pid) and make temp directories
############################################################# 
export pid=$$
export DATA=/tmpnwprd/hiresw_${NEST}_${MODEL}_${MEMBER}_${cyc}_${envir}
mkdir -p $DATA/post
cd $DATA/post 

###############################
# Specify NET and RUN name
###############################
export NET=hiresw
export RUN=${NEST}${MODEL}

##################################################
# SAVEGES  - Copy Files From TMPDIR to $GESdir
# SENDECF  - Flag Events on ecFlow
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
# RERUN    - Rerun fcst from beginning (default no)
##################################################
export SENDCOM=YES
export SENDDBN=YES
export SENDDBN_GB2=NO 
export SENDECF=YES

####################################
# File To Log Msgs
####################################
export jlogfile=/com/logs/jlogfile

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"

export MP_SHARED_MEMORY=yes

export cycle=t${cyc}z 

nestMODEL=`echo ${NEST}${MODEL} | tr '[a-z]' '[A-Z]'`
export nestMODEL
export DBN_NEST=${nestMODEL}
                                                                                                             
export HOMEhiresw=/nw${envir}/hiresw_v6.0.0
export EXEChiresw=$HOMEhiresw/exec
export FIXhiresw=$HOMEhiresw/fix
export PARMhiresw=$HOMEhiresw/parm
export USHhiresw=$HOMEhiresw/ush

###################################
# Set up the UTILITIES
###################################
export utilscript=/nwprod/util/ush
export utilexec=/nwprod/util/exec
# Run setup to initialize working directory and utility scripts
sh $utilscript/setup.sh

# Run setpdy and initialize PDY variables
sh $utilscript/setpdy.sh
. PDY

export com=/com/${NET}/${envir}
export COMIN=/com/${NET}/${envir}/hiresw.${PDY}
export COMOUT=/com/${NET}/${envir}/hiresw.${PDY}

mkdir -p $COMOUT
 
env

################################################
# Copy Forecast files from com
################################################
. $COMIN/${NEST}${MODEL}.t${cyc}z.envir.sh
export tmmark=tm00

########################################################
# Run the ex-script
#
${HOMEhiresw}/scripts/exhiresw_post.sh.ecf
#
########################################################

postmsg "$jlogfile" "$job FOR NEST=${NEST}${MODEL} IS COMPLETE"

endfhr=48

fhr=00
fhr=`printf '%02d' $fhrtst`

while [ $fhr -le $endfhr ]
do
  ic=0
  while [ $ic -le 600 ]
  do
    if [ -s $DATA/postdone${fhr} ]
    then
       break
    else
       let ic=ic+1
       sleep 20
    fi

    if [ $ic -ge 60 ]
    then
       err_exit "COULD NOT LOCATE: $DATA/postdone${fhr}"
    fi
  done
  let fhr=fhr+1
fhr=`printf '%02d' $fhr`
done

cd /tmpnwprd

date

ecflow_client --complete
