#!/bin/sh

set -xa
# #### 07/30/1999 ###################
# SET SHELL PROCESSING VARIABLES
# ###################################
export PS4='$SECONDS + ' 
date

############################################################# 
# obtain unique process id (pid) and make temp directories
############################################################# 
export pid=$$
export DATA=/tmpnwprd/${job}.${pid}
mkdir $DATA
cd $DATA 

###############################
# Specify NET and RUN name
###############################
export NET=hiresw
export RUN=${NEST}${MODEL}

##################################################
# SENDECF  - Flag Events on SMS
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
##################################################
export SENDCOM=YES
export SENDDBN=YES
export SENDECF=YES

####################################
# File To Log Msgs
####################################
export jlogfile=/com/logs/jlogfiles/jlogfile.${job}.${pid}

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"

export cycle=t${cyc}z 

echo ${NEST}${MODEL} > lower
nestMODEL=`cat lower | tr '[a-z]' '[A-Z]'`
export nestMODEL
export DBN_NEST=${nestMODEL}

# these will be used for ensemble mean

export HOMEhiresw=/nw${envir}/hiresw.${model_ver}
export EXEChiresw=$HOMEhiresw/exec
export FIXhiresw=$HOMEhiresw/fix
export PARMhiresw=$HOMEhiresw/parm
export USHhiresw=$HOMEhiresw/ush
export PARMutil=$HOMEhiresw/util/parm
###################################
# Set up the UTILITIES
###################################
export utilscript=/nwprod/util/ush
export utilexec=/nwprod/util/exec
# Run setup to initialize working directory and utility scripts
sh $utilscript/setup.sh

# Run setpdy and initialize PDY variables
sh $utilscript/setpdy.sh
. PDY

export com=/com/${NET}/${envir}
export COMIN=/com/${NET}/${envir}/hiresw.${PDY}
export pcom=/pcom/hiresw

mkdir -p $COMOUT $pcom
 
env

########################################################
# Run the ex-script
#
$HOMEhiresw/scripts/exhiresw_awips.sh.ecf
#
########################################################

postmsg "$jlogfile" "$job FOR NEST=${NEST}${MODEL} IS COMPLETE"

date
