#!/bin/sh 

########################################
# Preliminary data setup step
########################################

set -xa

ecflow_client -init=${ECF_RID}

export PS4='$SECONDS + ' 
date

########################################################### 
# obtain unique process id (pid) and make temp directories
###########################################################
export pid=$$
export DATA=/tmpnwprd/hiresw_${NEST}_${MODEL}_${MEMBER}_${cyc}_${envir}

mkdir -p $DATA
cd $DATA 
####################################
# File To Log Msgs
####################################
export jlogfile=/com/logs/jlogfile

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"

export cycle=t${cyc}z 

###############################
# Specify NET and RUN name
###############################
export NET=hiresw
export RUN=${NEST}${MODEL}

##################################################
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
# RERUN    - Rerun fcst from beginning (default no)
##################################################
export SENDCOM=YES
export SENDDBN=NO
export SENDSMS=NO

export HOMEhiresw=/nw${envir}/hiresw_v6.0.0
export EXEChiresw=$HOMEhiresw/exec
export FIXhiresw=$HOMEhiresw/fix
export PARMhiresw=$HOMEhiresw/parm
export USHhiresw=$HOMEhiresw/ush

###################################
# Set up the UTILITIES
###################################

export utilscript=/nwprod/util/ush
export utilexec=/nwprod/util/exec
# Run setup to initialize working directory and utility scripts
sh $utilscript/setup.sh

# Run setpdy and initialize PDY variables
sh $utilscript/setpdy.sh
. PDY

export COMOUT=/com/${NET}/${envir}/hiresw.${PDY}

mkdir -p -m 775 $COMOUT
 
#export PATH=${PATH}:/usrx/local/netcdf3.5/lib:/usrx/local/netcdf3.5/bin

########################################################
# Execute the script.
${HOMEhiresw}/scripts/exhiresw_prepfinal.sh.ecf
########################################################

cd /tmpnwprd

date

ecflow_client --complete
