#!/bin/sh

########################################
# Set up environment for HIRESW FCST
########################################

set -xa

ecflow_client -init=${ECF_RID}

export PS4='$SECONDS + ' 
date

########################################################### 
# obtain unique process id (pid) and make temp directories
###########################################################
export pid=$$
export DATA=/tmpnwprd/hiresw_${NEST}_${MODEL}_${MEMBER}_${cyc}_${envir}
mkdir $DATA
cd $DATA 

############################################################
# Remove files in the forecast directory before starting
############################################################
rm $DATA/*

####################################
# File To Log Msgs
####################################
export jlogfile=/com/logs/jlogfile

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"

export cycle=t${cyc}z 
export MP_LABELIO=YES
# export MP_HOLDTIME=1000

#################################
# Setup the NET and RUN name
#################################
export NET=hiresw
export RUN=${NEST}${MODEL}

############################################
#SENDCOM=YES       copy output file to /com
#SENDDBN=YES       alert data out to TOC
#SENDECF=YES       send message back to ecFlow
############################################
export SENDCOM=YES
export SENDDBN=YES
export SENDECF=YES

###################################
# Set up restart variable RERUN (default = NO)
# (YES means start from the beginning,
# NO means pick up where forecast left off, if able to)
###################################
export RERUN=NO

export HOMEhiresw=/nw${envir}/hiresw_v6.0.0
export EXEChiresw=$HOMEhiresw/exec
export FIXhiresw=$HOMEhiresw/fix
export PARMhiresw=$HOMEhiresw/parm
export USHhiresw=$HOMEhiresw/ush

###################################
# Set up the UTILITIES
###################################
export utilscript=/nwprod/util/ush
export utilexec=/nwprod/util/exec
# Run setup to initialize working directory and utility scripts
sh $utilscript/setup.sh
msg="JOB $job HAS BEGUN FOR NEST=$NEST"
postmsg "$jlogfile" "$msg"

# Run setpdy and initialize PDY variables
sh $utilscript/setpdy.sh
. PDY

export com=/com/${NET}/${envir}
export COMIN=/com/${NET}/${envir}/hiresw.${PDY}
export COMOUT=/com/${NET}/${envir}/hiresw.${PDY}

if [ ${MODEL} = "arw" ]
then
# causing post problems???
##### export MP_USE_BULK_XFER=yes
export MP_SHARED_MEMORY=yes
export MP_USE_TOKEN_FLOW_CONTROL=yes
export MP_INSTANCES=2
fi

 
env

###################################################
# Execute the Script
#
/${HOMEhiresw}/scripts/exhiresw_fcst.sh.ecf
#
###################################################

cat $pgmout

msg="JOB $job FOR NEST=${NEST}${MODEL}_${MEMBER} HAS COMPLETED NORMALLY."
postmsg "$jlogfile" "$msg"

date

ecflow_client --complete
