#!/bin/sh

########################################
# HiresW prdgen step
########################################

set -xa

ecflow_client -init=${ECF_RID}

export PS4='$SECONDS + ' 
date

############################################################# 
# obtain unique process id (pid) and make temp directories
############################################################# 
export pid=$$
export DATA=/tmpnwprd/hiresw_${NEST}_${MODEL}_${MEMBER}_${cyc}_${envir}
mkdir -p $DATA/prdgen_full
cd $DATA/prdgen_full

###############################
# Specify NET and RUN name
###############################
export NET=hiresw
export RUN=${NEST}${MODEL}

##################################################
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
# RERUN    - Rerun fcst from beginning (default no)
##################################################
export SENDCOM=YES
export SENDDBN=NO

export DBNROOT=DBNROOT_OFF

# Do not send alerts if DBNROOT is set to DBNROOT_OFF
# The alerts cause an error to be returned from the ush script that is
# poe'd when the DBNROOT path is not resolved

if [ $DBNROOT = "DBNROOT_OFF" ]; then
   export SENDDBN_GB2=NO
else
   export SENDDBN_GB2=YES
fi

export SENDSMS=NO

####################################
# File To Log Msgs
####################################
export jlogfile=/com/logs/jlogfile

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"

export cycle=t${cyc}z 

nestMODEL=`echo ${NEST}${MODEL} | tr '[a-z]' '[A-Z]'`
export nestMODEL
export DBN_NEST=${nestMODEL}
                                                                                                             
export HOMEhiresw=/nw${envir}/hiresw_v6.0.0

export EXEChiresw=$HOMEhiresw/exec
export FIXhiresw=$HOMEhiresw/fix
export PARMhiresw=$HOMEhiresw/parm
export USHhiresw=$HOMEhiresw/ush

###################################
# Set up the UTILITIES
###################################


export utilscript=/nwprod/util/ush

export utilexec=/nwprod/util/exec
# Run setup to initialize working directory and utility scripts
sh $utilscript/setup.sh

# Run setpdy and initialize PDY variables
sh $utilscript/setpdy.sh
. PDY

export com=/com/${NET}/${envir}
export COMIN=/com/${NET}/${envir}/hiresw.${PDY}
export COMOUT=/com/${NET}/${envir}/hiresw.${PDY}

mkdir -p $COMOUT

########################################################
# Run the ex-script
#
$HOMEhiresw/scripts/exhiresw_prdgenmgr.sh.ecf
#
########################################################

postmsg "$jlogfile" "$job FOR NEST=${NEST}${MODEL} IS COMPLETE"

date

while [ ! -e $DATA/sndpostdone48.tm00 ]
do
sleep 5
done

# prelim cleanup (cannot completely purge as smartinit jobs may still be running)

if [ $MODEL = "arw" ]
then
rm $DATA/wrfo*
rm $DATA/rsl.*
else
rm $DATA/*hst*
rm $DATA/*boco*
rm $DATA/*nemsio
fi

# if [ -e $DATA ]
# then
# rm -rf $DATA
# fi

ecflow_client --complete
