#!/bin/sh

########################################
# RUNS HIRESW_PRDGEN JOB
########################################

set -xa

ecflow_client -init=${ECF_RID}

export PS4='$SECONDS + ' 
date

############################################################# 
# obtain unique process id (pid) and make temp directories
############################################################# 
export pid=$$
export DATA=/tmpnwprd/hiresw_${NEST}_${MODEL}_${MEMBER}_${cyc}_${envir}
mkdir -p $DATA/prdgen_full
cd $DATA/prdgen_full

###############################
# Specify NET and RUN name
###############################
export NET=hiresw
export RUN=${NEST}${MODEL}

##################################################
# SAVEGES  - Copy Files From TMPDIR to $GESdir
# SENDECF  - Flag Events on ecFlow
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
# RERUN    - Rerun fcst from beginning (default no)
##################################################
export SENDCOM=YES
export SENDDBN=YES

# Do not send alerts if DBNROOT is set to DBNROOT_OFF
# The alerts cause an error to be returned from the ush script that is
# poe'd when the DBNROOT path is not resolved

if [ $DBNROOT = "DBNROOT_OFF" ]; then
   export SENDDBN_GB2=NO
else
   export SENDDBN_GB2=YES
fi

export SENDECF=YES

####################################
# File To Log Msgs
####################################
export jlogfile=/com/logs/jlogfile

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"

export cycle=t${cyc}z 

nestMODEL=`echo ${NEST}${MODEL} | tr '[a-z]' '[A-Z]'`
export nestMODEL
export DBN_NEST=${nestMODEL}
                                                                                                             
export HOMEhiresw=/nw${envir}/hiresw_v6.0.0
export EXEChiresw=$HOMEhiresw/exec
export FIXhiresw=$HOMEhiresw/fix
export PARMhiresw=$HOMEhiresw/parm
export USHhiresw=$HOMEhiresw/ush

###################################
# Set up the UTILITIES
###################################
export utilscript=/nwprod/util/ush
export utilexec=/nwprod/util/exec
# Run setup to initialize working directory and utility scripts
sh $utilscript/setup.sh

# Run setpdy and initialize PDY variables
sh $utilscript/setpdy.sh
. PDY

export com=/com/${NET}/${envir}
export COMIN=/com/${NET}/${envir}/hiresw.${PDY}
export COMOUT=/com/${NET}/${envir}/hiresw.${PDY}
mkdir -p $COMOUT
 
env

########################################################
# Run the ex-script
#
/${HOMEhiresw}/scripts/exhiresw_prdgen.sh.ecf
#
########################################################

postmsg "$jlogfile" "$job FOR NEST=${NEST}${MODEL} IS COMPLETE"

date

cd /tmpnwprd

# Be sure that the wrfbufrsnd job is done before scrubbing $DATA
#
while [ ! -e $DATA/sndpostdone48.tm00 ]
do
sleep 5
done

if [ $MODEL = "arw" ]
then
rm $DATA/wrfo*
rm $DATA/wrfi*
rm $DATA/wrfb*
else
rm $DATA/*hst*
rm $DATA/*nemsio
fi

# rm $DATA/post/WRFPRS*
# rm $DATA/prdgen_full/*awpreg*
# rm $DATA/prdgen_full/wrf*

ecflow_client --complete
