





MODULE module_state_description
  
  INTEGER, PARAMETER :: passiveqv = 0
  INTEGER, PARAMETER :: kesslerscheme = 1
  INTEGER, PARAMETER :: linscheme = 2
  INTEGER, PARAMETER :: wsm3scheme = 3
  INTEGER, PARAMETER :: wsm5scheme = 4
  INTEGER, PARAMETER :: etampnew = 5
  INTEGER, PARAMETER :: wsm6scheme = 6
  INTEGER, PARAMETER :: gsfcgcescheme = 7
  INTEGER, PARAMETER :: thompson = 8
  INTEGER, PARAMETER :: morr_two_moment = 10
  INTEGER, PARAMETER :: wdm5scheme = 14
  INTEGER, PARAMETER :: wdm6scheme = 16
  INTEGER, PARAMETER :: thompson07 = 98
  INTEGER, PARAMETER :: nodfimoist = -1
  INTEGER, PARAMETER :: passiveqv_dfi = 0
  INTEGER, PARAMETER :: kesslerscheme_dfi = 1
  INTEGER, PARAMETER :: linscheme_dfi = 2
  INTEGER, PARAMETER :: wsm3scheme_dfi = 3
  INTEGER, PARAMETER :: wsm5scheme_dfi = 4
  INTEGER, PARAMETER :: etampnew_dfi = 5
  INTEGER, PARAMETER :: wsm6scheme_dfi = 6
  INTEGER, PARAMETER :: gsfcgcescheme_dfi = 7
  INTEGER, PARAMETER :: thompson_dfi = 8
  INTEGER, PARAMETER :: morr_two_moment_dfi = 10
  INTEGER, PARAMETER :: wdm5scheme_dfi = 14
  INTEGER, PARAMETER :: wdm6scheme_dfi = 16
  INTEGER, PARAMETER :: thompson07_dfi = 98
  INTEGER, PARAMETER :: rrtmscheme = 1
  INTEGER, PARAMETER :: camlwscheme = 3
  INTEGER, PARAMETER :: rrtmg_lwscheme = 4
  INTEGER, PARAMETER :: gfdllwscheme = 99
  INTEGER, PARAMETER :: heldsuarez = 31
  INTEGER, PARAMETER :: swradscheme = 1
  INTEGER, PARAMETER :: gsfcswscheme = 2
  INTEGER, PARAMETER :: camswscheme = 3
  INTEGER, PARAMETER :: rrtmg_swscheme = 4
  INTEGER, PARAMETER :: gfdlswscheme = 99
  INTEGER, PARAMETER :: sfclayscheme = 1
  INTEGER, PARAMETER :: myjsfcscheme = 2
  INTEGER, PARAMETER :: gfssfcscheme = 3
  INTEGER, PARAMETER :: gfdlsfcscheme = 88
  INTEGER, PARAMETER :: qnsesfcscheme = 4
  INTEGER, PARAMETER :: pxsfcscheme = 7
  INTEGER, PARAMETER :: slabscheme = 1
  INTEGER, PARAMETER :: lsmscheme = 2
  INTEGER, PARAMETER :: ruclsmscheme = 3
  INTEGER, PARAMETER :: gfdlslab = 88
  INTEGER, PARAMETER :: pxlsmscheme = 7
  INTEGER, PARAMETER :: ysuscheme = 1
  INTEGER, PARAMETER :: myjpblscheme = 2
  INTEGER, PARAMETER :: gfsscheme = 3
  INTEGER, PARAMETER :: qnsepblscheme = 4
  INTEGER, PARAMETER :: acmpblscheme = 7
  INTEGER, PARAMETER :: boulacscheme = 8
  INTEGER, PARAMETER :: mrfscheme = 99
  INTEGER, PARAMETER :: kfetascheme = 1
  INTEGER, PARAMETER :: bmjscheme = 2
  INTEGER, PARAMETER :: gdscheme = 3
  INTEGER, PARAMETER :: sasscheme = 4
  INTEGER, PARAMETER :: g3scheme = 5
  INTEGER, PARAMETER :: kfscheme = 99
  INTEGER, PARAMETER :: io_intio = 1
  INTEGER, PARAMETER :: io_netcdf = 2
  INTEGER, PARAMETER :: io_hdf = 3
  INTEGER, PARAMETER :: io_phdf5 = 4
  INTEGER, PARAMETER :: io_grib1 = 5
  INTEGER, PARAMETER :: io_mcel = 6
  INTEGER, PARAMETER :: io_esmf = 7
  INTEGER, PARAMETER :: io_yyy = 8
  INTEGER, PARAMETER :: io_zzz = 9
  INTEGER, PARAMETER :: io_grib2 = 10
  INTEGER, PARAMETER :: io_pnetcdf = 11
  INTEGER, PARAMETER :: dfi_nodfi = 0
  INTEGER, PARAMETER :: dfi_dfl = 1
  INTEGER, PARAMETER :: dfi_ddfi = 2
  INTEGER, PARAMETER :: dfi_tdfi = 3
  INTEGER, PARAMETER :: dfi_setup = 0
  INTEGER, PARAMETER :: dfi_bck = 1
  INTEGER, PARAMETER :: dfi_fwd = 2
  INTEGER, PARAMETER :: dfi_fst = 3
  
  INTEGER, PARAMETER :: PARAM_qv = 1
  INTEGER            ::     P_qv = 1
  LOGICAL            ::     F_qv = .FALSE.
  INTEGER, PARAMETER :: PARAM_qc = 2
  INTEGER            ::     P_qc = 1
  LOGICAL            ::     F_qc = .FALSE.
  INTEGER, PARAMETER :: PARAM_qr = 3
  INTEGER            ::     P_qr = 1
  LOGICAL            ::     F_qr = .FALSE.
  INTEGER, PARAMETER :: PARAM_qi = 4
  INTEGER            ::     P_qi = 1
  LOGICAL            ::     F_qi = .FALSE.
  INTEGER, PARAMETER :: PARAM_qs = 5
  INTEGER            ::     P_qs = 1
  LOGICAL            ::     F_qs = .FALSE.
  INTEGER, PARAMETER :: PARAM_qg = 6
  INTEGER            ::     P_qg = 1
  LOGICAL            ::     F_qg = .FALSE.
  INTEGER, PARAMETER :: PARAM_NUM_moist = 7
  INTEGER            ::       NUM_moist = 1
  INTEGER, PARAMETER :: PARAM_dfi_qv = 1
  INTEGER            ::     P_dfi_qv = 1
  LOGICAL            ::     F_dfi_qv = .FALSE.
  INTEGER, PARAMETER :: PARAM_dfi_qc = 2
  INTEGER            ::     P_dfi_qc = 1
  LOGICAL            ::     F_dfi_qc = .FALSE.
  INTEGER, PARAMETER :: PARAM_dfi_qr = 3
  INTEGER            ::     P_dfi_qr = 1
  LOGICAL            ::     F_dfi_qr = .FALSE.
  INTEGER, PARAMETER :: PARAM_dfi_qi = 4
  INTEGER            ::     P_dfi_qi = 1
  LOGICAL            ::     F_dfi_qi = .FALSE.
  INTEGER, PARAMETER :: PARAM_dfi_qs = 5
  INTEGER            ::     P_dfi_qs = 1
  LOGICAL            ::     F_dfi_qs = .FALSE.
  INTEGER, PARAMETER :: PARAM_dfi_qg = 6
  INTEGER            ::     P_dfi_qg = 1
  LOGICAL            ::     F_dfi_qg = .FALSE.
  INTEGER, PARAMETER :: PARAM_NUM_dfi_moist = 7
  INTEGER            ::       NUM_dfi_moist = 1
  INTEGER, PARAMETER :: PARAM_qni = 1
  INTEGER            ::     P_qni = 1
  LOGICAL            ::     F_qni = .FALSE.
  INTEGER, PARAMETER :: PARAM_qns = 2
  INTEGER            ::     P_qns = 1
  LOGICAL            ::     F_qns = .FALSE.
  INTEGER, PARAMETER :: PARAM_qnr = 3
  INTEGER            ::     P_qnr = 1
  LOGICAL            ::     F_qnr = .FALSE.
  INTEGER, PARAMETER :: PARAM_qng = 4
  INTEGER            ::     P_qng = 1
  LOGICAL            ::     F_qng = .FALSE.
  INTEGER, PARAMETER :: PARAM_qnn = 5
  INTEGER            ::     P_qnn = 1
  LOGICAL            ::     F_qnn = .FALSE.
  INTEGER, PARAMETER :: PARAM_qnc = 6
  INTEGER            ::     P_qnc = 1
  LOGICAL            ::     F_qnc = .FALSE.
  INTEGER, PARAMETER :: PARAM_NUM_scalar = 7
  INTEGER            ::       NUM_scalar = 1
  INTEGER, PARAMETER :: PARAM_dfi_qndrop = 1
  INTEGER            ::     P_dfi_qndrop = 1
  LOGICAL            ::     F_dfi_qndrop = .FALSE.
  INTEGER, PARAMETER :: PARAM_dfi_qni = 2
  INTEGER            ::     P_dfi_qni = 1
  LOGICAL            ::     F_dfi_qni = .FALSE.
  INTEGER, PARAMETER :: PARAM_dfi_qt = 3
  INTEGER            ::     P_dfi_qt = 1
  LOGICAL            ::     F_dfi_qt = .FALSE.
  INTEGER, PARAMETER :: PARAM_dfi_qns = 4
  INTEGER            ::     P_dfi_qns = 1
  LOGICAL            ::     F_dfi_qns = .FALSE.
  INTEGER, PARAMETER :: PARAM_dfi_qnr = 5
  INTEGER            ::     P_dfi_qnr = 1
  LOGICAL            ::     F_dfi_qnr = .FALSE.
  INTEGER, PARAMETER :: PARAM_dfi_qng = 6
  INTEGER            ::     P_dfi_qng = 1
  LOGICAL            ::     F_dfi_qng = .FALSE.
  INTEGER, PARAMETER :: PARAM_dfi_qnn = 7
  INTEGER            ::     P_dfi_qnn = 1
  LOGICAL            ::     F_dfi_qnn = .FALSE.
  INTEGER, PARAMETER :: PARAM_dfi_qnc = 8
  INTEGER            ::     P_dfi_qnc = 1
  LOGICAL            ::     F_dfi_qnc = .FALSE.
  INTEGER, PARAMETER :: PARAM_NUM_dfi_scalar = 9
  INTEGER            ::       NUM_dfi_scalar = 1
  INTEGER, PARAMETER :: PARAM_NUM_chem = 1
  INTEGER            ::       NUM_chem = 1
  INTEGER, PARAMETER :: P_XSB                          = 1
  INTEGER, PARAMETER :: P_XEB                          = 2
  INTEGER, PARAMETER :: P_YSB                          = 3
  INTEGER, PARAMETER :: P_YEB                          = 4
  INTEGER, PARAMETER :: NUM_TIME_LEVELS = 2
  INTEGER , PARAMETER :: PARAM_FIRST_SCALAR = 2
CONTAINS
SUBROUTINE init_module_state_description
END SUBROUTINE init_module_state_description
END MODULE module_state_description

