 
**** Compiling WPS and all utilities ****
 
	( cd src ;  make -i -r geogrid.exe  WRF_DIR="/gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2"  FC="mpxlf90_r"  CC="mpcc_r"  CPP="/usr/lib/cpp -C -P"  FFLAGS="-qfree=f90"  CFLAGS=""  LDFLAGS=""  CPPFLAGS="-DAIX -DIBM4 -DIO_NETCDF -DIO_BINARY -DIO_GRIB1 -D_MPI -DBIT32 -D_GEOGRID" )
	/bin/rm -f interp_module.o interp_module.mod
	/bin/cp interp_module.f90 interp_module.f
	mpxlf90_r -qfree=f90 -c interp_module.f -I/gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2/external/io_netcdf  -I/gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2/external/io_grib_share  -I/gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2/external/io_grib1  -I/gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2/external/io_int  -I/gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2/inc
	/bin/rm -f interp_module.f
	/bin/rm -f proc_point_module.o proc_point_module.mod
	/bin/cp proc_point_module.f90 proc_point_module.f
	mpxlf90_r -qfree=f90 -c proc_point_module.f -I/gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2/external/io_netcdf  -I/gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2/external/io_grib_share  -I/gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2/external/io_grib1  -I/gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2/external/io_int  -I/gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2/inc
	/bin/rm -f proc_point_module.f
	/bin/rm -f process_tile_module.o process_tile_module.mod
	/usr/lib/cpp -C -P -DAIX -DIBM4 -DIO_NETCDF -DIO_BINARY -DIO_GRIB1 -D_MPI -DBIT32 -D_GEOGRID  -I/gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2/external/io_netcdf  -I/gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2/external/io_grib_share  -I/gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2/external/io_grib1  -I/gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2/external/io_int  -I/gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2/inc process_tile_module.F90 > process_tile_module.f
	mpxlf90_r -qfree=f90 -c process_tile_module.f -I/gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2/external/io_netcdf  -I/gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2/external/io_grib_share  -I/gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2/external/io_grib1  -I/gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2/external/io_int  -I/gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2/inc
	/bin/rm -f process_tile_module.f
	/bin/rm -f geogrid.o geogrid.mod
	/usr/lib/cpp -C -P -DAIX -DIBM4 -DIO_NETCDF -DIO_BINARY -DIO_GRIB1 -D_MPI -DBIT32 -D_GEOGRID  -I/gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2/external/io_netcdf  -I/gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2/external/io_grib_share  -I/gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2/external/io_grib1  -I/gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2/external/io_int  -I/gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2/inc geogrid.F90 > geogrid.f
	mpxlf90_r -qfree=f90 -c geogrid.f -I/gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2/external/io_netcdf  -I/gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2/external/io_grib_share  -I/gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2/external/io_grib1  -I/gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2/external/io_int  -I/gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2/inc
	/bin/rm -f geogrid.f
	mpxlf90_r  -o geogrid.exe cio.o wrf_debug.o bitarray_module.o constants_module.o despace.o geogrid.o gridinfo_module.o hash_module.o interp_module.o list_module.o llxy_module.o misc_definitions_module.o module_debug.o module_map_utils.o output_module.o parallel_module.o process_tile_module.o proc_point_module.o queue_module.o read_binary_field.o smooth_module.o source_data_module.o  /gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2/frame/pack_utils.o /gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2/frame/module_machine.o  /gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2/frame/module_internal_header_util.o  -I/gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2/external/io_grib1  -I/gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2/external/io_grib_share  -I/gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2/external/io_int  -I/usrx/local/netcdf.3.5.0/include  -I/gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2/external/io_netcdf  -L/gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2/external/io_grib1 -lio_grib1  -L/gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2/external/io_grib_share -lio_grib_share  -L/gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2/external/io_int -lwrfio_int  -L/gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2/external/io_netcdf -lwrfio_nf  -L/usrx/local/netcdf.3.5.0/lib -lnetcdf
	if [ -e geogrid.exe ] ; then  /bin/rm -f geogrid.exe ;  fi ;  if [ -e ../geogrid.exe ] ; then  /bin/rm -f ../geogrid.exe ;  fi ;  if [ -e src/geogrid.exe ] ; then  ln -sf src/geogrid.exe . ;  fi
	( cd src/ngl ; make -i -r DEV_TOP="/gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd" CC="cc" FC="xlf90_r" all )
Target "all" is up to date.
	( cd src ;  make -i -r ungrib.exe  WRF_DIR="/gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2"  FC="xlf90_r"  CC="mpcc_r"  CPP="/usr/lib/cpp -C -P"  FFLAGS="-qfree=f90"  CFLAGS=""  LDFLAGS=""  CPPFLAGS="-DAIX -DIBM4 -DIO_NETCDF -DIO_BINARY -DIO_GRIB1 -D_MPI -DBIT32 -D_UNGRIB" )
Target "ungrib.exe" is up to date.
	if [ -h ungrib.exe ] ; then  /bin/rm -f ungrib.exe ;  fi ;  if [ -h ../ungrib.exe ] ; then  /bin/rm -f ../ungrib.exe ;  fi ;  if [ -e src/ungrib.exe ] ; then  ln -sf src/ungrib.exe . ;  fi
	( cd src ;  make -i -r metgrid.exe  WRF_DIR="/gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2"  FC="mpxlf90_r"  CC="mpcc_r"  CPP="/usr/lib/cpp -C -P"  FFLAGS="-qfree=f90"  CFLAGS=""  LDFLAGS=""  CPPFLAGS="-DAIX -DIBM4 -DIO_NETCDF -DIO_BINARY -DIO_GRIB1 -D_MPI -DBIT32 -D_METGRID" )
	/bin/rm -f rotate_winds_module.o rotate_winds_module.mod
	/bin/cp rotate_winds_module.f90 rotate_winds_module.f
	mpxlf90_r -qfree=f90 -c rotate_winds_module.f -I/gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2/external/io_netcdf  -I/gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2/external/io_grib_share  -I/gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2/external/io_grib1  -I/gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2/external/io_int  -I/gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2/inc
	/bin/rm -f rotate_winds_module.f
	/bin/rm -f process_domain_module.o process_domain_module.mod
	/usr/lib/cpp -C -P -DAIX -DIBM4 -DIO_NETCDF -DIO_BINARY -DIO_GRIB1 -D_MPI -DBIT32 -D_METGRID  -I/gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2/external/io_netcdf  -I/gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2/external/io_grib_share  -I/gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2/external/io_grib1  -I/gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2/external/io_int  -I/gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2/inc process_domain_module.F90 > process_domain_module.f
	mpxlf90_r -qfree=f90 -c process_domain_module.f -I/gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2/external/io_netcdf  -I/gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2/external/io_grib_share  -I/gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2/external/io_grib1  -I/gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2/external/io_int  -I/gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2/inc
	/bin/rm -f process_domain_module.f
	/bin/rm -f metgrid.o metgrid.mod
	/usr/lib/cpp -C -P -DAIX -DIBM4 -DIO_NETCDF -DIO_BINARY -DIO_GRIB1 -D_MPI -DBIT32 -D_METGRID  -I/gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2/external/io_netcdf  -I/gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2/external/io_grib_share  -I/gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2/external/io_grib1  -I/gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2/external/io_int  -I/gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2/inc metgrid.F90 > metgrid.f
	mpxlf90_r -qfree=f90 -c metgrid.f -I/gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2/external/io_netcdf  -I/gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2/external/io_grib_share  -I/gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2/external/io_grib1  -I/gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2/external/io_int  -I/gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2/inc
	/bin/rm -f metgrid.f
	mpxlf90_r  -o metgrid.exe cio.o wrf_debug.o bitarray_module.o constants_module.o datatype_module.o despace.o gridinfo_module.o metgrid.o input_module.o interp_module.o interp_option_module.o list_module.o llxy_module.o minheap_module.o misc_definitions_module.o module_date_pack.o module_debug.o module_map_utils.o module_mergesort.o output_module.o parallel_module.o process_domain_module.o queue_module.o read_met_module.o rotate_winds_module.o storage_module.o write_met_module.o  /gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2/frame/pack_utils.o /gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2/frame/module_machine.o  /gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2/frame/module_internal_header_util.o  -I/gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2/external/io_grib1  -I/gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2/external/io_grib_share  -I/gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2/external/io_int  -I/usrx/local/netcdf.3.5.0/include  -I/gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2/external/io_netcdf  -L/gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2/external/io_grib1 -lio_grib1  -L/gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2/external/io_grib_share -lio_grib_share  -L/gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2/external/io_int -lwrfio_int  -L/gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2/external/io_netcdf -lwrfio_nf  -L/usrx/local/netcdf.3.5.0/lib -lnetcdf
	if [ -e metgrid.exe ] ; then  /bin/rm -f metgrid.exe ;  fi ;  if [ -e ../metgrid.exe ] ; then  /bin/rm -f ../metgrid.exe ;  fi ;  if [ -e src/metgrid.exe ] ; then  ln -sf src/metgrid.exe . ;  fi
	( cd src/ngl ; make -i -r DEV_TOP="/gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd" CC="cc" FC="xlf90_r" all )
Target "all" is up to date.
	( cd src ;  make -i -r g1print.exe  WRF_DIR="/gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2"  FC="xlf90_r"  CC="mpcc_r"  CPP="/usr/lib/cpp -C -P"  FFLAGS="-qfree=f90"  CFLAGS=""  LDFLAGS=""  CPPFLAGS="-DAIX -DIBM4 -DIO_NETCDF -DIO_BINARY -DIO_GRIB1 -D_MPI -DBIT32 -D_GRIBUTIL" )
Target "g1print.exe" is up to date.
	if [ -h g1print.exe ] ; then  /bin/rm -f g1print.exe ;  fi ;  if [ -h ../g1print.exe ] ; then  /bin/rm -f ../g1print.exe ;  fi ;  if [ -e src/g1print.exe ] ; then  ln -sf src/g1print.exe . ;  fi
	( cd src/ngl ; make -i -r DEV_TOP="/gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd" CC="cc" FC="xlf90_r" all )
Target "all" is up to date.
	( cd src ;  make -i -r g2print.exe  WRF_DIR="/gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2"  FC="xlf90_r"  CC="mpcc_r"  CPP="/usr/lib/cpp -C -P"  FFLAGS="-qfree=f90"  CFLAGS=""  LDFLAGS=""  CPPFLAGS="-DAIX -DIBM4 -DIO_NETCDF -DIO_BINARY -DIO_GRIB1 -D_MPI -DBIT32 -D_GRIBUTIL" )
	xlf90_r -o g2print.exe  g2print.o  -L. -lpgu  -L./ngl -lw3 -lg2_4  
	if [ -h g2print.exe ] ; then  /bin/rm -f g2print.exe ;  fi ;  if [ -h ../g2print.exe ] ; then  /bin/rm -f ../g2print.exe ;  fi ;  if [ -e src/g2print.exe ] ; then  ln -sf src/g2print.exe . ;  fi
	( cd src ;  make -i -r plotfmt.exe  WRF_DIR="/gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2"  FC="mpxlf90_r"  CC="mpcc_r"  CPP="/usr/lib/cpp -C -P"  FFLAGS="-qfree=f90"  CFLAGS=""  LDFLAGS=""  CPPFLAGS="-DAIX -DIBM4 -DIO_NETCDF -DIO_BINARY -DIO_GRIB1 -D_MPI -DBIT32 -D_UTIL" )
	xlf90_r -o plotfmt.exe  plotfmt.o read_met_module.o module_debug.o  misc_definitions_module.o cio.o   -L/usr/local/lib64/r4i4 -lncarg -lncarg_gks -lncarg_c  -L/usr/X11R6/lib -lX11
	if [ -h plotfmt.exe ] ; then  /bin/rm -f plotfmt.exe ;  fi ;  if [ -h ../plotfmt.exe ] ; then  /bin/rm -f ../plotfmt.exe ;  fi ;  if [ -e src/plotfmt.exe ] ; then  ln -sf src/plotfmt.exe . ;  fi
	( cd src ;  make -i -r rd_intermediate.exe  WRF_DIR="/gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2"  FC="mpxlf90_r"  CC="mpcc_r"  CPP="/usr/lib/cpp -C -P"  FFLAGS="-qfree=f90"  CFLAGS=""  LDFLAGS=""  CPPFLAGS="-DAIX -DIBM4 -DIO_NETCDF -DIO_BINARY -DIO_GRIB1 -D_MPI -DBIT32 -D_UTIL" )
	xlf90_r -o rd_intermediate.exe  rd_intermediate.o read_met_module.o  module_debug.o misc_definitions_module.o cio.o
	if [ -h rd_intermediate.exe ] ; then  /bin/rm -f rd_intermediate.exe ;  fi ;  if [ -h ../rd_intermediate.exe ] ; then  /bin/rm -f ../rd_intermediate.exe ;  fi ;  if [ -e src/rd_intermediate.exe ] ; then  ln -sf src/rd_intermediate.exe . ;  fi
	( cd src ;  make -i -r plotgrids.exe  WRF_DIR="/gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2"  FC="mpxlf90_r"  CC="mpcc_r"  CPP="/usr/lib/cpp -C -P"  FFLAGS="-qfree=f90"  CFLAGS=""  LDFLAGS=""  CPPFLAGS="-DAIX -DIBM4 -DIO_NETCDF -DIO_BINARY -DIO_GRIB1 -D_MPI -DBIT32 -D_UTIL" )
	xlf90_r -o plotgrids.exe  module_map_utils.o module_debug.o cio.o constants_module.o misc_definitions_module.o  plotgrids.o  -L/usr/local/lib64/r4i4 -lncarg -lncarg_gks -lncarg_c  -L/usr/X11R6/lib -lX11
	if [ -h plotgrids.exe ] ; then  /bin/rm -f plotgrids.exe ;  fi ;  if [ -h ../plotgrids.exe ] ; then  /bin/rm -f ../plotgrids.exe ;  fi ;  if [ -e src/plotgrids.exe ] ; then  ln -sf src/plotgrids.exe . ;  fi
	( cd src ;  make -i -r mod_levs.exe  WRF_DIR="/gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2"  FC="mpxlf90_r"  CC="mpcc_r"  CPP="/usr/lib/cpp -C -P"  FFLAGS="-qfree=f90"  CFLAGS=""  LDFLAGS=""  CPPFLAGS="-DAIX -DIBM4 -DIO_NETCDF -DIO_BINARY -DIO_GRIB1 -D_MPI -DBIT32 -D_UTIL" )
	xlf90_r -o mod_levs.exe  mod_levs.o module_debug.o read_met_module.o  write_met_module.o misc_definitions_module.o cio.o
	if [ -h mod_levs.exe ] ; then  /bin/rm -f mod_levs.exe ;  fi ;  if [ -h ../mod_levs.exe ] ; then  /bin/rm -f ../mod_levs.exe ;  fi ;  if [ -e src/mod_levs.exe ] ; then  ln -sf src/mod_levs.exe . ;  fi
	( cd src ;  make -i -r avg_tsfc.exe  WRF_DIR="/gpfs/m/nco/ops/nwtest/sorc/hiresw_wps.fd/../WRFV2"  FC="mpxlf90_r"  CC="mpcc_r"  CPP="/usr/lib/cpp -C -P"  FFLAGS="-qfree=f90"  CFLAGS=""  LDFLAGS=""  CPPFLAGS="-DAIX -DIBM4 -DIO_NETCDF -DIO_BINARY -DIO_GRIB1 -D_MPI -DBIT32 -D_UTIL" )
	xlf90_r  -o avg_tsfc.exe avg_tsfc.o cio.o module_debug.o gridinfo_module.o  read_met_module.o write_met_module.o module_date_pack.o  misc_definitions_module.o
	if [ -h avg_tsfc.exe ] ; then  /bin/rm -f avg_tsfc.exe ;  fi ;  if [ -h ../avg_tsfc.exe ] ; then  /bin/rm -f ../avg_tsfc.exe ;  fi ;  if [ -e src/avg_tsfc.exe ] ; then  ln -sf src/avg_tsfc.exe . ;  fi
