#!/bin/sh

########################################
# Set up environment for HIRESW FCST
########################################
set -xa
export PS4='$SECONDS + ' 
date

######################################################
# Default to NCO production run environment
#######################################################
export RUN_ENVIR=${RUN_ENVIR:-prod}

###############################
# Specify NET and RUN name
###############################
export NET=${NET:-hiresw}
export RUN=${RUN:-hiresw}

###############################################################
# This block can be modified for different Production test
# environment. This is used for operational testings
###############################################################
if [ "$RUN_ENVIR" = prod -a $envir != prod ]; then
  export jlogfile=/com/logs/${envir}/jlogfile
  export SENDDBN=NO
fi

########################################################### 
# obtain unique process id (pid) and make temp directories
###########################################################
export pid=$$
export DATA=${DATA:-$DATAROOT/hiresw.forecast_${NEST}_${MODEL}_${cyc}_${envir}}

mkdir $DATA
cd $DATA 

ecflow_client --event release_downstream

####################################
# File To Log Msgs
####################################
export jlogfile=${jlogfile:-/com/logs/jlogfiles/jlogfile.$job.$pid}

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"

export cycle=${cycle:-t${cyc}z} 
export MP_LABELIO=YES
export MP_USE_BULK_XFER=yes

############################################
#SENDCOM=YES       copy output file to /com
#SENDDBN=YES       alert data out to TOC
#SENDECF=YES       send message back to ecFlow
############################################
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDECF=${SENDECF:-YES}

export HOMEhiresw=${HOMEhiresw:-/nw${envir}/hiresw.${model_ver}}
export EXEChiresw=${EXEChiresw:-$HOMEhiresw/exec}
export FIXhiresw=${FIXhiresw:-$HOMEhiresw/fix}
export PARMhiresw=${PARMhiresw:-$HOMEhiresw/parm}
export USHhiresw=${USHhiresw:-$HOMEhiresw/ush}

export HOMEprod=${HOMEprod:-/nwprod}
export FIXprod=${FIXprod:-${HOMEprod}/fix}

###################################
# Set up the UTILITIES
###################################

module load prod_util

# Run setpdy and initialize PDY variables
setpdy.sh
. PDY

export COMROOT=${COMROOT:-/com2}
export COMIN=${COMIN:-/${COMROOT}/${NET}/${envir}/${RUN}.${PDY}}
export COMOUT=${COMOUT:-/${COMROOT}/${NET}/${envir}/${RUN}.${PDY}}

if [ ${MODEL} = "arw" ]
then
export MP_SHARED_MEMORY=yes
export MP_USE_TOKEN_FLOW_CONTROL=yes
export MP_INSTANCES=2
fi

# bsub post scripts  - clean these out before commit
bsub < ${HOMEhiresw}/launch/sub_post.lsf_${NEST}_${MODEL}_${cyc}
bsub < ${HOMEhiresw}/launch/sub_prdgen.lsf_${NEST}_${MODEL}_${cyc}
bsub < ${HOMEhiresw}/launch/sub_wrfbufrsnd.lsf_${NEST}_${MODEL}_${cyc}
bsub < ${HOMEhiresw}/launch/sub_smartinit.lsf_${NEST}_${MODEL}_${cyc}
bsub < ${HOMEhiresw}/launch/sub_smartinitb.lsf_${NEST}_${MODEL}_${cyc}
### end bsub post scripts

 
###################################################
# Execute the Script
#
${HOMEhiresw}/scripts/exhiresw_fcst.sh.ecf
#
###################################################

cat $pgmout

msg="JOB $job FOR NEST=${NEST}${MODEL} HAS COMPLETED NORMALLY."
postmsg "$jlogfile" "$msg"
date
