#!/bin/sh

########################################
# RUNS HIRESW POST JOB
########################################
set -xa
export PS4='$SECONDS + ' 
date

###############################
# Specify NET and RUN name
###############################
export NET=${NET:-hiresw}
export RUN=${RUN:-hiresw}

############################################################# 
# obtain unique process id (pid) and make temp directories
############################################################# 
export pid=$$
export DATA=${DATA:-$DATAROOT/hiresw.post_${NEST}_${MODEL}_${cyc}_${envir}}
export INPUT_DATA=${INPUT_DATA:-${DATAROOT}/hiresw.forecast_${NEST}_${MODEL}_${cyc}_${envir}}
mkdir -p $DATA
cd $DATA

####################################
# File To Log Msgs
####################################
export jlogfile=${jlogfile:-/com/logs/jlogfiles/jlogfile.$job.$pid}

##################################################
# SENDECF  - Flag Events on ecFlow
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
##################################################
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDECF=${SENDECF:-YES}

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"

export cycle=${cycle:-t${cyc}z}

export DBN_NEST=`echo ${NEST}_${MODEL} | tr '[a-z]' '[A-Z]'`
                                                                                                             
export HOMEhiresw=${HOMEhiresw:-$NWROOT/hiresw.${hiresw_ver}}
export EXEChiresw=${EXEChiresw:-$HOMEhiresw/exec}
export FIXhiresw=${FIXhiresw:-$HOMEhiresw/fix}
export PARMhiresw=${PARMhiresw:-$HOMEhiresw/parm}
export USHhiresw=${USHhiresw:-$HOMEhiresw/ush}

# Run setpdy and initialize PDY variables
setpdy.sh
. PDY

export COMROOT=${COMROOT:-/com2}
export COMIN=${COMIN:-${COMROOT}/${NET}/${envir}/${RUN}.${PDY}}

################################################
# Copy Forecast files from com
################################################
. $COMIN/hiresw.t${cyc}z.${NEST}${MODEL}.envir.sh
export tmmark=tm00

########################################################
# Run the ex-script
#
${HOMEhiresw}/scripts/exhiresw_postg2.sh.ecf
#
########################################################

postmsg "$jlogfile" "$job FOR NEST=${NEST}${MODEL} IS COMPLETE"

date
