#! /bin/ksh

DOM=${1}
CORE=${2}
CYC=${3}

NPROC_NCASE=1

cat sub_ncase.lsf_in | sed s:_DOM_:${DOM}:g | sed s:_CORE_:${CORE}:g | sed s:_CYC_:${CYC}:g | \
  sed s:_NPROCNCASE_:${NPROC_NCASE}:g |  sed s:_NPROCNCASE_:${NRPOC_NCASE}:g  > sub_ncase.lsf_${DOM}_${CORE}_${CYC}


bsub < sub_ncase.lsf_${DOM}_${CORE}_${CYC}

