#!/bin/sh

#############################################################
# HREF RUNALL 
# 02/02/2015 Binbin Zhou, create for run all scripts 
#############################################################

########################################
# Preliminary data setup step
########################################

set -xa
export PS4='$SECONDS + ' 
date

###################################
# Specify NET and RUN Name and model
####################################
export NET=${NET:-href}
export RUN=${RUN:-href}

export IOBUF_PARAMS='*:size=8M:count=8'

###############################################################
# This block can be modified for different Production test
# environment. This is used for operational testings
###############################################################

## PDY not included here as pull data from PDYm1 as well
# without timelagging maybe should include PDY here?

export COMINrrfs=${COMINrrfs:-$(compath.py ${envir}/com/rrfs/${rrfs_ver}/rrfs)}

export GESIN=${GESIN:-${GESROOT}/${envir}/hiresw/href}

export HOMEhref=${HOMEhref:-$NWROOT/href.${href_ver}} 
export EXEChref=${EXEChref:-$HOMEhref/exec}
export PARMhref=${PARMhref:-$HOMEhref/parm}
export USHhref=${USHhref:-$HOMEhref/ush}
export FIXhref=${FIXhref:-$HOMEhref/fix}
export SCRIPTShref=${SCRIPTShref:-$HOMEhref/scripts}

###########################################################
# obtain unique process id (pid) and make temp directories
###########################################################

export pid=$$
export DATA=${DATA:-${DATAROOT}/href_ensprodpreproc_${NEST}_${cyc}_${envir}.${pid}}
mkdir -p $DATA
rm -rf $DATA/*
cd $DATA

####################################
# Determine Job Output Name on System
####################################
export pgmout="OUTPUT.$$"

export cycle=${cycle:-t${cyc}z}

##################################################
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
##################################################

export SENDCOM=${SENDCOM:-YES}
export SENDECF=${SENDECF:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDDBN_NTC=${SENDDBN_NTC:-NO}

###################################
# Set up the UTILITIES
###################################

msg="JOB $job HAS BEGUN"
postmsg "$msg"

#
# Run setpdy and initialize PDY variables
#


export cycle=${cycle:-t${cyc}z}

setpdy.sh
. ./PDY

echo have PDY as $PDY

##############################################
# Define running directory and COM directories
##############################################


export COMOUT=${COMOUT:-$(compath.py -o $NET/${href_ver})/${RUN}.${PDY}}


if [ ! -d $COMOUT ] ; then 
 mkdir -p $COMOUT/ensprod
 mkdir -p $COMOUT/verf_g2g
fi

if [ ! -e ${GESIN}.${PDY} ] ; then
  mkdir -p ${GESIN}.${PDY}
fi

#######################################################
# Pass information which is needed to run the Script
#######################################################

# export VERBOSE=YES

###################################################
# Execute the Script exhref_ensprod.sh

hrlist="00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 \
21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 \
41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60"

mems="01 02 03 04 05 06 07 08 09"

for mem in $mems
do

if [ -e poe.fv3 ]
then
rm poe.fv3
fi

for hr in $hrlist
do
echo "$USHhref/preprocess_fv3_1h.sh ${cyc} ${mem} $hr" >> poe.fv3
done

chmod 775 poe.fv3  
# export NODES=6

# ./poe.fv3
mpiexec -n $NTASK -ppn $PTILE --cpu-bind verbose,core cfp ./poe.fv3
export err=$?; err_chk

done

# need to generate 3 h QPF

for mem in $mems
do
echo " calling preprocess_fv3_3hapcp.sh for mem " $mem
$USHhref/preprocess_fv3_3hapcp.sh ${cyc}  ${mem}
done

# end QPF

cd $DATAROOT
if [ $KEEPDATA = NO ]; then rm -rf $DATA; fi

date
