!STARTOFREGISTRYGENERATEDINCLUDE frame/module_state_description.F
!
! WARNING This file is generated automatically by use_registry
! using the data base in the file named Registry.
! Do not edit.  Your changes to this file will be lost.
!
MODULE module_state_description
  ! package constants
  INTEGER, PARAMETER :: dyn_nodyn = 0
  INTEGER, PARAMETER :: dyn_em = 2
  INTEGER, PARAMETER :: passiveqv = 0
  INTEGER, PARAMETER :: kesslerscheme = 1
  INTEGER, PARAMETER :: linscheme = 2
  INTEGER, PARAMETER :: wsm3scheme = 3
  INTEGER, PARAMETER :: wsm5scheme = 4
  INTEGER, PARAMETER :: etampnew = 5
  INTEGER, PARAMETER :: wsm6scheme = 6
  INTEGER, PARAMETER :: ncepcloud3 = 98
  INTEGER, PARAMETER :: ncepcloud5 = 99
  INTEGER, PARAMETER :: thompson = 8
  INTEGER, PARAMETER :: rrtmscheme = 1
  INTEGER, PARAMETER :: camlwscheme = 3
  INTEGER, PARAMETER :: gfdllwscheme = 99
  INTEGER, PARAMETER :: swradscheme = 1
  INTEGER, PARAMETER :: gsfcswscheme = 2
  INTEGER, PARAMETER :: camswscheme = 3
  INTEGER, PARAMETER :: gfdlswscheme = 99
  INTEGER, PARAMETER :: sfclayscheme = 1
  INTEGER, PARAMETER :: myjsfcscheme = 2
  INTEGER, PARAMETER :: gfssfcscheme = 3
  INTEGER, PARAMETER :: slabscheme = 1
  INTEGER, PARAMETER :: lsmscheme = 2
  INTEGER, PARAMETER :: ruclsmscheme = 3
  INTEGER, PARAMETER :: ysuscheme = 1
  INTEGER, PARAMETER :: myjpblscheme = 2
  INTEGER, PARAMETER :: gfsscheme = 3
  INTEGER, PARAMETER :: mrfscheme = 99
  INTEGER, PARAMETER :: kfetascheme = 1
  INTEGER, PARAMETER :: bmjscheme = 2
  INTEGER, PARAMETER :: gdscheme = 3
  INTEGER, PARAMETER :: sasscheme = 4
  INTEGER, PARAMETER :: kfscheme = 99
  INTEGER, PARAMETER :: psufddagd = 1
  INTEGER, PARAMETER :: io_intio = 1
  INTEGER, PARAMETER :: io_netcdf = 2
  INTEGER, PARAMETER :: io_hdf = 3
  INTEGER, PARAMETER :: io_phdf5 = 4
  INTEGER, PARAMETER :: io_grib1 = 5
  INTEGER, PARAMETER :: io_mcel = 6
  INTEGER, PARAMETER :: io_esmf = 7
  INTEGER, PARAMETER :: io_yyy = 8
  INTEGER, PARAMETER :: io_zzz = 9
  INTEGER, PARAMETER :: io_grib2 = 10
  INTEGER, PARAMETER :: io_pnetcdf = 11
  ! 4D array constants
  INTEGER, PARAMETER :: PARAM_qv = 1
  INTEGER            ::     P_qv = 1
  LOGICAL            ::     F_qv = .FALSE.
  INTEGER, PARAMETER :: PARAM_qc = 2
  INTEGER            ::     P_qc = 1
  LOGICAL            ::     F_qc = .FALSE.
  INTEGER, PARAMETER :: PARAM_qr = 3
  INTEGER            ::     P_qr = 1
  LOGICAL            ::     F_qr = .FALSE.
  INTEGER, PARAMETER :: PARAM_qi = 4
  INTEGER            ::     P_qi = 1
  LOGICAL            ::     F_qi = .FALSE.
  INTEGER, PARAMETER :: PARAM_qs = 5
  INTEGER            ::     P_qs = 1
  LOGICAL            ::     F_qs = .FALSE.
  INTEGER, PARAMETER :: PARAM_qg = 6
  INTEGER            ::     P_qg = 1
  LOGICAL            ::     F_qg = .FALSE.
  INTEGER, PARAMETER :: PARAM_NUM_moist = 7
  INTEGER            ::       NUM_moist = 1
  INTEGER, PARAMETER :: PARAM_NUM_chem = 1
  INTEGER            ::       NUM_chem = 1
  INTEGER, PARAMETER :: PARAM_qni = 1
  INTEGER            ::     P_qni = 1
  LOGICAL            ::     F_qni = .FALSE.
  INTEGER, PARAMETER :: PARAM_qt = 2
  INTEGER            ::     P_qt = 1
  LOGICAL            ::     F_qt = .FALSE.
  INTEGER, PARAMETER :: PARAM_NUM_scalar = 3
  INTEGER            ::       NUM_scalar = 1
  INTEGER, PARAMETER :: PARAM_mth01 = 1
  INTEGER            ::     P_mth01 = 1
  LOGICAL            ::     F_mth01 = .FALSE.
  INTEGER, PARAMETER :: PARAM_mth02 = 2
  INTEGER            ::     P_mth02 = 1
  LOGICAL            ::     F_mth02 = .FALSE.
  INTEGER, PARAMETER :: PARAM_mth03 = 3
  INTEGER            ::     P_mth03 = 1
  LOGICAL            ::     F_mth03 = .FALSE.
  INTEGER, PARAMETER :: PARAM_mth04 = 4
  INTEGER            ::     P_mth04 = 1
  LOGICAL            ::     F_mth04 = .FALSE.
  INTEGER, PARAMETER :: PARAM_mth05 = 5
  INTEGER            ::     P_mth05 = 1
  LOGICAL            ::     F_mth05 = .FALSE.
  INTEGER, PARAMETER :: PARAM_mth06 = 6
  INTEGER            ::     P_mth06 = 1
  LOGICAL            ::     F_mth06 = .FALSE.
  INTEGER, PARAMETER :: PARAM_mth07 = 7
  INTEGER            ::     P_mth07 = 1
  LOGICAL            ::     F_mth07 = .FALSE.
  INTEGER, PARAMETER :: PARAM_mth08 = 8
  INTEGER            ::     P_mth08 = 1
  LOGICAL            ::     F_mth08 = .FALSE.
  INTEGER, PARAMETER :: PARAM_mth09 = 9
  INTEGER            ::     P_mth09 = 1
  LOGICAL            ::     F_mth09 = .FALSE.
  INTEGER, PARAMETER :: PARAM_mth10 = 10
  INTEGER            ::     P_mth10 = 1
  LOGICAL            ::     F_mth10 = .FALSE.
  INTEGER, PARAMETER :: PARAM_mth11 = 11
  INTEGER            ::     P_mth11 = 1
  LOGICAL            ::     F_mth11 = .FALSE.
  INTEGER, PARAMETER :: PARAM_mth12 = 12
  INTEGER            ::     P_mth12 = 1
  LOGICAL            ::     F_mth12 = .FALSE.
  INTEGER, PARAMETER :: PARAM_NUM_ozmixm = 13
  INTEGER            ::       NUM_ozmixm = 1
  INTEGER, PARAMETER :: PARAM_sul = 1
  INTEGER            ::     P_sul = 1
  LOGICAL            ::     F_sul = .FALSE.
  INTEGER, PARAMETER :: PARAM_sslt = 2
  INTEGER            ::     P_sslt = 1
  LOGICAL            ::     F_sslt = .FALSE.
  INTEGER, PARAMETER :: PARAM_dust1 = 3
  INTEGER            ::     P_dust1 = 1
  LOGICAL            ::     F_dust1 = .FALSE.
  INTEGER, PARAMETER :: PARAM_dust2 = 4
  INTEGER            ::     P_dust2 = 1
  LOGICAL            ::     F_dust2 = .FALSE.
  INTEGER, PARAMETER :: PARAM_dust3 = 5
  INTEGER            ::     P_dust3 = 1
  LOGICAL            ::     F_dust3 = .FALSE.
  INTEGER, PARAMETER :: PARAM_dust4 = 6
  INTEGER            ::     P_dust4 = 1
  LOGICAL            ::     F_dust4 = .FALSE.
  INTEGER, PARAMETER :: PARAM_ocpho = 7
  INTEGER            ::     P_ocpho = 1
  LOGICAL            ::     F_ocpho = .FALSE.
  INTEGER, PARAMETER :: PARAM_bcpho = 8
  INTEGER            ::     P_bcpho = 1
  LOGICAL            ::     F_bcpho = .FALSE.
  INTEGER, PARAMETER :: PARAM_ocphi = 9
  INTEGER            ::     P_ocphi = 1
  LOGICAL            ::     F_ocphi = .FALSE.
  INTEGER, PARAMETER :: PARAM_bcphi = 10
  INTEGER            ::     P_bcphi = 1
  LOGICAL            ::     F_bcphi = .FALSE.
  INTEGER, PARAMETER :: PARAM_bg = 11
  INTEGER            ::     P_bg = 1
  LOGICAL            ::     F_bg = .FALSE.
  INTEGER, PARAMETER :: PARAM_volc = 12
  INTEGER            ::     P_volc = 1
  LOGICAL            ::     F_volc = .FALSE.
  INTEGER, PARAMETER :: PARAM_NUM_aerosolc = 13
  INTEGER            ::       NUM_aerosolc = 1
  INTEGER, PARAMETER :: PARAM_u_ndg_new = 1
  INTEGER            ::     P_u_ndg_new = 1
  LOGICAL            ::     F_u_ndg_new = .FALSE.
  INTEGER, PARAMETER :: PARAM_v_ndg_new = 2
  INTEGER            ::     P_v_ndg_new = 1
  LOGICAL            ::     F_v_ndg_new = .FALSE.
  INTEGER, PARAMETER :: PARAM_t_ndg_new = 3
  INTEGER            ::     P_t_ndg_new = 1
  LOGICAL            ::     F_t_ndg_new = .FALSE.
  INTEGER, PARAMETER :: PARAM_q_ndg_new = 4
  INTEGER            ::     P_q_ndg_new = 1
  LOGICAL            ::     F_q_ndg_new = .FALSE.
  INTEGER, PARAMETER :: PARAM_ph_ndg_new = 5
  INTEGER            ::     P_ph_ndg_new = 1
  LOGICAL            ::     F_ph_ndg_new = .FALSE.
  INTEGER, PARAMETER :: PARAM_u_ndg_old = 6
  INTEGER            ::     P_u_ndg_old = 1
  LOGICAL            ::     F_u_ndg_old = .FALSE.
  INTEGER, PARAMETER :: PARAM_v_ndg_old = 7
  INTEGER            ::     P_v_ndg_old = 1
  LOGICAL            ::     F_v_ndg_old = .FALSE.
  INTEGER, PARAMETER :: PARAM_t_ndg_old = 8
  INTEGER            ::     P_t_ndg_old = 1
  LOGICAL            ::     F_t_ndg_old = .FALSE.
  INTEGER, PARAMETER :: PARAM_q_ndg_old = 9
  INTEGER            ::     P_q_ndg_old = 1
  LOGICAL            ::     F_q_ndg_old = .FALSE.
  INTEGER, PARAMETER :: PARAM_ph_ndg_old = 10
  INTEGER            ::     P_ph_ndg_old = 1
  LOGICAL            ::     F_ph_ndg_old = .FALSE.
  INTEGER, PARAMETER :: PARAM_NUM_fdda3d = 11
  INTEGER            ::       NUM_fdda3d = 1
  INTEGER, PARAMETER :: PARAM_mu_ndg_new = 1
  INTEGER            ::     P_mu_ndg_new = 1
  LOGICAL            ::     F_mu_ndg_new = .FALSE.
  INTEGER, PARAMETER :: PARAM_mu_ndg_old = 2
  INTEGER            ::     P_mu_ndg_old = 1
  LOGICAL            ::     F_mu_ndg_old = .FALSE.
  INTEGER, PARAMETER :: PARAM_NUM_fdda2d = 3
  INTEGER            ::       NUM_fdda2d = 1
  INTEGER, PARAMETER :: P_XSB                          = 1
  INTEGER, PARAMETER :: P_XEB                          = 2
  INTEGER, PARAMETER :: P_YSB                          = 3
  INTEGER, PARAMETER :: P_YEB                          = 4
  INTEGER, PARAMETER :: NUM_TIME_LEVELS = 2
  INTEGER , PARAMETER :: PARAM_FIRST_SCALAR = 2
CONTAINS
SUBROUTINE init_module_state_description
END SUBROUTINE init_module_state_description
END MODULE module_state_description
!ENDOFREGISTRYGENERATEDINCLUDE
